const en = {
  'agent-tools': {
    title: 'Connect your coding tools',
    description: 'Choose a tool and use your available models through Antigravity Manager.',
    loading: 'Reading settings…',
    installed: 'Installed',
    'not-installed': 'Installation not detected',
    'read-error': 'Could not read the existing settings. Retry before making changes.',
    retry: 'Retry',
    configured: 'Configuration saved',
    'custom-address': 'Using another address',
    'not-configured': 'Not configured',
    'not-verified': 'Requests not verified',
    address: 'Manager address',
    model: 'Model',
    'not-set': 'Not set',
    'choose-model': 'Choose during setup',
    update: 'Update configuration',
    configure: 'Configure',
    view: 'View configuration',
    restore: 'Restore backup',
    remove: 'Remove connection',
    'install-notice':
      'You can save settings before installing the tool. Reopen it after installation.',
    'action-error': 'Could not update tool settings',
    saved: 'Settings updated',
    reopen: 'Reopen {{name}} to load the settings.',
    'configure-title': 'Connect {{name}}',
    'configure-description':
      'Requests will use Manager. The existing settings are backed up before the first change.',
    'restore-title': 'Restore {{name}} settings?',
    'restore-description':
      'This replaces the whole settings file with its original backup, including any later edits. If Manager created the file, it will be removed. The backup is used once.',
    'remove-title': 'Remove the Manager connection?',
    'remove-description':
      'Restore the previous connection settings while keeping unrelated settings and the backup.',
    'preview-title': '{{name}} settings',
    'preview-description':
      'Only the settings needed to connect to Manager are shown. Connection keys are hidden.',
    confirm: 'Confirm',
    advanced: 'Address and configuration file',
    'reset-address': 'Use current Manager address',
    'backend-files':
      'These settings are saved on the computer running the Manager service, under the user running it.',
    'backup-notice': 'The first backup is retained across updates. Reopen the tool after saving.',
    'toml-notice':
      'Formatting and comments in the Codex settings file may change. A full backup is saved for recovery. Existing sign-in and permission settings are kept.',
    'codex-review':
      'Configure both task and automatic review requests. Existing enabled review routes and approval settings are kept.',
    'model-count': '{{count}} model(s)',
    'plugin-notice':
      'A direct-login plugin is installed. It can use a different connection; check the selected provider in OpenCode.',
    'revoke-key': 'Disable the OpenCode connection key',
    errors: {
      unavailable: 'Tool settings are unavailable. Please retry.',
      'invalid-config':
        'The settings file is invalid or too large. Fix it before configuring the tool.',
      'read-failed': 'Could not read the settings file. Check access and retry.',
      'write-failed': 'Could not save the settings. The recovery backup is retained.',
      'backup-failed': 'Could not create the backup. The tool settings were not changed.',
      'backup-missing': 'No recovery backup is available.',
      'configuration-changed':
        'The settings changed during this operation. Read them again and retry.',
      'key-missing': 'Generate a connection key on the proxy page first.',
      'review-route-disabled':
        'The Codex review route is disabled. Enable it in model routing before configuration.',
    },

    'address-help': 'Use the current Manager address unless the service runs on another computer.',
    'invalid-address':
      'Use a Manager address starting with http:// or https://, without sign-in details or extra parameters.',
    'model-required': 'Choose a model before saving.',
  },
  appName: 'Antigravity Manager',
  'process-runtime': {
    'close-failed':
      'Could not close Antigravity. Save your chats and files, close the app manually, and retry.',
    'exit-unconfirmed':
      'Antigravity has not finished closing. Save your chats and files, close the app manually, and retry.',
    working: 'Processing...',
    busy: 'Antigravity is busy. Wait for the current operation to finish.',
    'missing-executable':
      'Antigravity could not be found or opened. Check its application location in Settings.',
    'target-conflict':
      'The running Antigravity app is from a different installation than the one selected in Settings. Close it or select the matching installation before switching accounts.',
    'directory-conflict':
      'Antigravity is using a different data folder than the one selected in Settings. Close it or check the folder setting before switching accounts.',
    'probe-failed':
      'Antigravity status could not be checked in time. Check whether the app is open and try again.',
    'launch-failed':
      'Antigravity could not be opened. Check its application location and access permissions.',
    'startup-unconfirmed':
      'Antigravity has not been confirmed open yet. To avoid opening it twice, no second launch was attempted. Check the app before trying again.',
    'switched-hot-unconfirmed':
      'The new account was saved, but the change in Antigravity IDE could not be confirmed. Check the account shown in the IDE before trying again.',
    'switched-startup-unconfirmed':
      'The new account was saved, but Antigravity has not been confirmed open yet. No second launch was attempted. Check the app before trying again.',
  },
  common: {
    close: 'Close',
    cancel: 'Cancel',
    'core-unavailable-title': "Can't connect to Antigravity Manager",
    'core-unavailable-body':
      'Accounts and proxy are unavailable right now. Close and reopen Antigravity Manager. If the problem continues, install the latest version.',
    'account-data-unavailable-title': "Can't open saved accounts",
    'account-data-unavailable-body':
      "Your saved accounts can't be read right now. Make sure you're signed in to your usual computer account, then reopen Antigravity Manager. Your account data has not been changed.",
    'already-running-title': 'Antigravity Manager is already running',
    'already-running-body':
      "Close the other Antigravity Manager window and try again. If you can't find it, restart your computer.",
    loading: 'Loading...',
    error: 'Error',
    unknown: 'Unknown',
    notAvailable: 'N/A',
    openMenu: 'Open menu',

    'dismiss-notification': 'Dismiss notification',
    'reading-settings': 'Reading your settings…',
  },
  status: {
    checking: 'Checking status...',
    running: 'Antigravity is running in background',
    stopped: 'Antigravity service stopped',
    services: 'Services',
    dashboard_title: 'Service status',
    open_dashboard: 'Open service status',
    checking_short: 'Checking...',
    running_short: 'Running',
    stopped_short: 'Stopped',
    all_running: 'All services running',
    all_stopped: 'All services stopped',
    partial_running: '{{running}}/{{total}} services running',
  },
  action: {
    stop: 'Stop',
    start: 'Start',
    switch: 'Switch',
    deleteBackup: 'Delete Backup',
    backupCurrent: 'Backup Current',
    retry: 'Retry',
    details: 'Details',
    openLogs: 'Open Log Directory',
  },
  update: {
    title: 'Updates',
    checking: 'Checking...',
    checkNow: 'Check for Updates',
    checkFailed: 'Unable to check for updates',
    upToDate: "You're up to date.",
    unsupported: 'Automatic update checks are not available on this platform.',
    available: {
      title: 'Update available',
      description: 'Version {{version}} is available on GitHub.',
      download: 'Download',
      downloading: 'Downloading...',
      dismiss: 'Dismiss',
      macosUnsignedNote:
        'This macOS build is not officially signed. If macOS blocks the app, follow the manual signing steps in the GitHub README or related issues.',
    },
    downloaded: {
      title: 'Update ready',
      description: 'Version {{version}} has been downloaded.',
      restart: 'Restart',
    },
  },
  error: {
    generic: 'An unexpected error occurred.',
    detailsTitle: 'Error details',
    detailsDescription:
      'These details can help troubleshoot the problem and may include private file locations. Review them before sharing.',
    keychainUnavailable: "Can't access saved sign-in information right now.",
    keychainHint: {
      translocation: 'Move the app to the Applications folder, then open it again.',
      keychainDenied:
        "macOS blocked access to saved sign-in information. Check the app's installation instructions and try again.",
      signNotarize: 'If available, install a version that macOS recognizes as verified.',
    },
    dataMigrationFailed: "Can't read accounts saved by an earlier version.",
    masterKeyUnavailable:
      "Saved accounts were found, but they can't be opened right now. Your account data has not been changed.",
    dataMigrationHint: {
      relogin: 'Please re-login or re-add your accounts.',
      clearData: 'If the issue persists, clear local account data and sign in again.',
    },
    antigravityStorageJsonNotFound:
      'Antigravity setup is incomplete. Open the selected Antigravity app and sign in once, then try switching accounts again.',
    antigravityProjectIdMissing:
      'This account is not ready to use with Antigravity. Sign in to it in Antigravity once, then try switching again.',
    antigravityDatabasePermissionDenied:
      'Antigravity sign-in details could not be saved. Check that its data folder allows changes, or open Antigravity once and restart Manager.',
    cloudAccountLoginExpired:
      'The login information for this cloud account has expired. Please log in again.',
  },
  nav: {
    navigation: 'Navigation',
    'collapse-sidebar': 'Collapse sidebar',
    'expand-sidebar': 'Expand sidebar',
    accounts: 'Accounts',
    proxy: 'API Proxy',
    settings: 'Settings',
    traffic: 'Traffic',
  },
  traffic: {
    'detail-load-failed': 'Could not load this request. Please try again.',
    'detail-not-found': 'This record is no longer available. It may have been cleared.',
    fields: {
      category: 'Category',
      method: 'Request method',
      'requested-model': 'Requested model',
      'mapped-model': 'Selected model route',
      error: 'Error details',
      affected: 'Affected records',
      'request-id': 'Request ID',
      'client-address': 'Client address',
      username: 'User',
      'reasoning-tokens': 'Reasoning tokens',
      'cached-tokens': 'Cached tokens',
      query: 'Additional request options',
    },
    outcomes: {
      in_progress: 'In progress',
      completed: 'Completed',
      client_cancelled: 'Cancelled',
      client_disconnected: 'Connection closed',
      timeout: 'Timed out',
      upstream_error: 'Model service error',
      auth_failed: 'Sign-in failed',
      internal_error: 'App error',
      partial: 'Partial result',
    },
    title: 'Traffic Monitor',
    description: 'Review model requests and app activity to find issues quickly.',
    records: '{{count}} records',
    'on-disk': '{{size}} on disk',
    dropped: '{{count}} dropped',
    model: 'Model requests',
    auxiliary: 'Other requests',
    ipc: 'App actions',
    system: 'System events',
    'advanced-diagnostics': 'Advanced diagnostics',
    'search-metadata': 'Search by model, request ID or address',
    'date-from': 'From',
    'date-to': 'To',
    account: 'Account',
    'all-accounts': 'All accounts',
    'model-family': 'Model family',
    'all-model-families': 'All model families',
    'physical-model': 'Model used',
    'output-type': 'Output',
    'all-output-types': 'All outputs',
    'text-output': 'Text',
    'image-output': 'Image',
    'mixed-output': 'Text + image',
    'no-visible-output': 'No visible output',
    unknown: 'Unknown',
    'tokens-in-out': 'Tokens in / out',
    'input-tokens': 'Input tokens',
    'output-tokens': 'Output tokens',
    'all-statuses': 'All statuses',
    'exact-status': 'Exact code',
    unfinished: 'Unfinished',
    'no-status': 'No status',
    'include-current-credential': 'Include current proxy key in copied cURL',
    'credential-warning':
      'The copied command exposes the current proxy key to your clipboard and any place you paste it. The switch resets when filters change or you leave this page.',
    'current-credential': 'current key',
    'copy-request-curl': 'Copy request as cURL',
    'copy-upstream-curl': 'Copy model-service request as cURL (private values hidden)',
    'curl-copied': 'cURL command copied to clipboard.',
    'curl-copy-failed': 'Unable to copy cURL command.',
    'new-records': '{{count}} new records',
    refresh: 'Refresh',
    'confirm-clear': 'Confirm clear',
    'clear-category': 'Clear category',
    total: '{{count}} total · page {{page}}',
    'loading-records': 'Loading records…',
    'no-records': 'No records in this category.',
    'detail-title': 'Traffic detail',
    'loading-detail': 'Loading traffic detail…',
    'system-operation': 'System operation',
    metadata: 'Request details',
    attempts: 'Retry history ({{count}})',
    payloads: 'Full content ({{count}})',
    'client-request': 'Client request',
    'request-headers': 'Request headers',
    'response-headers': 'Response headers',
    'upstream-attempts': 'Requests sent to the model service',
    'no-attempts': 'No requests were sent to the model service.',
    attempt: 'Attempt {{index}}',
    running: 'running',
    client: 'Client',
    upstream: 'Model service',
    request: 'request',
    response: 'response',
    'select-body': 'Select a request or response body.',
    concise: 'Concise',
    full: 'Full',
    'view-mode-help': 'About view modes',
    'concise-help':
      'Show the main request details. Expanded sections still show their full content.',
    'full-help':
      'Show all loaded details. If the content cannot be organized or is incomplete, both views may look the same.',
    'search-body': 'Search this body',
    'copy-loaded': 'Copy loaded',
    'view-all-body': 'View all',
    'load-more': 'Load more',
    'load-next-window': 'Next section',
    'save-full': 'Save full',
    matches: '{{count}} matches',
    'first-100': 'first 100',
    'parse-error': 'This content could not be read at position {{offset}}.',
    partial: 'Partial',
    'session-key': 'Session ID',
    'select-session': 'Select a session to view saved reasoning.',
    'no-sessions': 'No saved reasoning yet.',
    'delete-session': 'Delete session history',
    turns: '{{count}} turns',
    offset: 'Content position {{offset}}',
    'unknown-model': 'Unknown model',
    'thought-oversized':
      'Reasoning content exceeded 64 MiB and was not saved in full. Reference: {{hash}}',
    time: 'Time',
    operation: 'Operation',
    'operation-url': 'Operation / URL',
    result: 'Result',
    duration: 'Duration',
    status: 'Status',
    endpoint: 'Service address',
    protocol: 'API format',
    'repair-databases': 'Repair saved records',
    'open-monitor': 'Open Traffic Monitor',

    'loading-description': 'Your request records will appear here when they are ready.',
    'empty-description':
      'Requests sent through the proxy appear here. You can also adjust the filters.',
    'empty-category-description':
      'Records for this category appear here. Try another category or adjust the filters.',
    'load-failed': 'Could not read request records',
    'load-failed-description':
      'Please try again. This does not mean your records have been deleted.',
    'refresh-failed': 'Could not refresh records. Previously loaded records are still shown.',
  },
  editionSelection: {
    title: 'Choose Your Antigravity Edition',
    description:
      'Select which version of Antigravity you are using. This helps the Manager connect to the correct application.',
    edition1x: {
      name: 'Antigravity 1.x',
      description:
        'The original Antigravity application. Choose this if you are using the legacy version.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description:
        'The new Antigravity IDE (2.0). Choose this if you are using the latest IDE version.',
    },
    confirm: 'Continue',
  },
  account: {
    current: 'Current',
    lastUsed: 'Last used {{time}}',
    switchToAntigravity: 'Switch to Antigravity',
    switchToIde: 'Switch to Antigravity IDE',
  },
  home: {
    title: 'Accounts',
    description: 'Manage your Antigravity Google Gemini accounts.',
    noBackups: {
      title: 'No backups found',
      description: 'Create a backup of your current Antigravity account to get started.',
      action: 'Backup Current Account',
    },
  },
  settings: {
    'service-unavailable':
      "Settings can't be loaded or saved right now. Try again. If the problem continues, close and reopen Antigravity Manager.",
    'service-retry': 'Retry',
    'service-restart-required':
      'Settings saved. Turn the proxy off and back on to apply the changes.',
    'service-save': 'Save',
    'service-secret-configured': 'Proxy address is set. Enter a new address to replace it.',
    'weekly-warmup': {
      error: 'Warmup settings could not be loaded or saved.',
      retry: 'Retry',
      'cost-notice':
        'Warmup uses real model quota and may use AI credits. HTTP acceptance does not guarantee a new weekly timer.',
      title: 'Weekly quota warmup',
      description:
        'After a selected weekly quota resets, send one minimal request per quota bucket and record successful cycles.',
      enabled: 'Enable weekly quota warmup',
      groups: 'Quota groups to warm up',
      group: { claude: 'Claude quota groups', gemini: 'Gemini quota groups' },
    },
    title: 'Settings',
    description: 'Manage application preferences.',
    general: 'General',
    connection: 'Connection',
    models: 'Models',
    appearance: {
      title: 'Appearance',
      description: 'Customize how Antigravity Manager looks on your device.',
    },
    darkMode: 'Dark Mode',
    darkModeDescription: 'Enable dark mode for better viewing at night.',
    language: {
      title: 'Language',
      description: 'Select your preferred language.',
      english: 'English',
      chinese: 'Chinese (Simplified)',
      russian: 'Russian',
      vietnamese: 'Vietnamese',
      turkish: 'Turkish',
      french: 'French',
    },
    about: {
      title: 'About',
      description: 'Application information.',
    },
    cache: {
      title: 'Antigravity Cache',
      description:
        'Clear known Antigravity and Antigravity IDE cache directories to resolve login or version validation issues.',
      clear: 'Clear Antigravity Cache',
      dialogTitle: 'Clear Antigravity Cache?',
      dialogDescription: 'The following existing cache directories will be removed.',
      pathsLabel: 'Cache directories',
      noPaths: 'No known Antigravity cache directories were found.',
      warning: 'Close Antigravity before clearing its cache to avoid locked or recreated files.',
      cancel: 'Cancel',
      confirm: 'Clear Cache',
      clearing: 'Clearing...',
      clearedTitle: 'Cache cleared',
      clearedDescription: '{{size}} MB was removed from Antigravity cache directories.',
      failedTitle: 'Failed to clear cache',
      notFoundTitle: 'No Antigravity cache found',

      'paths-failed': 'Could not find the cache locations',
      'paths-retry-description': 'Please retry before clearing the cache.',
      'partial-title': 'Some cache could not be cleared',
      'partial-description':
        'Freed {{size}} MB. {{count}} location(s) could not be cleared. Close Antigravity and try again.',
    },
    version: 'Version',
    platform: 'Platform',
    license: 'License',
    openLogDir: 'Open',
    toast: {
      saved: {
        title: 'Settings saved',
        description: 'Your configuration has been updated.',
      },
      saveFailed: {
        title: 'Error saving settings',
      },
    },
    account: {
      'client-setup': 'Client locations and launch options',
      'client-setup-description':
        'Change these only if Manager cannot find your client or you need custom launch options.',
      'choose-file': 'Choose a file',
      'clear-field': 'Clear this field',
      title: 'Account Settings',
      description: 'Configure automatic account refresh and sync.',
      auto_refresh: 'Auto Refresh Quota',
      auto_refresh_desc: 'Periodically refresh quota info for all accounts',
      auto_sync: 'Auto Sync Current Account',
      auto_sync_desc: 'Periodically sync active account information',
      antigravity_executable: 'Antigravity executable',
      antigravity_executable_desc:
        'Optional path used to find portable mode data and launch Antigravity.',
      antigravity_executable_placeholder:
        'Example: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_cli_executable: 'Antigravity CLI executable',
      antigravity_cli_executable_desc:
        'Path to the agy CLI executable. Eligibility patching is restricted to this file.',
      antigravity_cli_executable_placeholder: 'Example: C:\\Program Files\\Antigravity\\agy.exe',
      detect_antigravity_cli: 'Detect',
      agy_cli_detected: 'Antigravity CLI detected',
      agy_cli_detect_failed: 'Antigravity CLI not found',
      agy_patch_desc:
        'Back up the CLI, verify a unique ARM64 or x86_64 eligibility pattern, apply the patch, and re-sign Mach-O files on macOS.',
      agy_patch_action: 'Apply eligibility patch',
      agy_patch_success: 'Antigravity CLI patched',
      agy_patch_already_applied: 'Patch already applied',
      agy_patch_failed: 'Unable to patch Antigravity CLI',
      agy_patch_result:
        'Format: {{format}}; architectures: {{architectures}}; backup: {{backupPath}}',
      agy_patch_no_backup: 'not required',
      antigravity_ide_executable: 'Antigravity IDE executable',
      antigravity_ide_executable_desc:
        'Optional Antigravity IDE executable path. When switching Classic accounts, processes at this path are protected from termination.',
      antigravity_ide_executable_placeholder:
        'Example: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Antigravity launch arguments',
      antigravity_args_desc:
        'Optional arguments passed when launching Antigravity, such as --user-data-dir.',
      antigravity_args_placeholder: 'Example: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Antigravity IDE launch arguments',
      antigravity_ide_args_desc:
        'Optional arguments passed when launching Antigravity IDE, such as --user-data-dir.',
      antigravity_ide_args_placeholder: 'Example: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Detect',
    },
    startup: {
      title: 'Startup',
      description: 'Control application launch behavior at system startup.',
      auto_startup: 'Start with system',
      auto_startup_desc: 'Launch at sign-in and keep the app in the system tray',
      start_in_tray: 'Start in tray',
      start_in_tray_desc: 'Start the application minimized in the system tray',
      macos_hint:
        'macOS requires a signed app for Login Items to work. If auto-start fails, please sign the app or enable it manually in System Settings.',
    },
    privacy: {
      title: 'Privacy',
      description: 'Control how your data is used to improve the application.',
      error_reporting: 'Error Reporting',
      error_reporting_desc:
        'Send anonymous error reports to help us improve the app. No personal data is collected.',
      telemetry: 'Performance Telemetry',
      telemetry_desc:
        'Share anonymous timing metrics and traces to diagnose slow account switching.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Share anonymous interaction diagnostics, heatmaps, and session replay to improve the app.',
      clarity_unavailable: 'Microsoft Clarity is not configured for this build.',
      restart_note: 'Some logging and diagnostics settings take effect after restarting the app.',
    },
    notifications: {
      title: 'Notifications',
      description: 'Configure desktop alerts for account events.',
      quotaAlert: 'Low Quota Alerts',
      quotaAlertDesc: 'Get notified when a model quota drops below the set threshold',
      quotaThreshold: 'Alert Threshold',
      quotaThresholdDesc: 'Percentage below which to trigger an alert',
      saveFailed: 'Failed to save notification settings',
      thresholdSaveFailed: 'Failed to save threshold setting',
      aiCreditsAlert: 'Low AI Credits Alert',
      aiCreditsAlertDesc:
        'Get notified when the AI credits balance falls at or below the set amount',
      aiCreditsThreshold: 'AI Credits Alert Threshold',
      aiCreditsThresholdDesc: 'Credit amount at or below which to trigger an alert',
      aiCreditsThresholdSaveFailed: 'Failed to save AI credits threshold setting',
    },
    proxy: {
      title: 'Upstream Proxy',
      description: 'Configure a proxy for outgoing requests to Google/Gemini APIs.',
      enable: 'Enable Upstream Proxy',
      url: 'Proxy URL',
      timeout: 'Request Timeout (Seconds)',
    },
    modelMapping: {
      title: 'Model Mapping',
      description:
        'Map Claude Code models to Antigravity models. Optimize cost and speed by routing requests intelligently.',
      claudeKeyword: 'Claude Model (Keyword)',
      targetGemini: 'Target Gemini Model',
      addPlaceholderKey: 'e.g. op-3',
      addPlaceholderValue: 'e.g. gemini-3-flash',
      noMappings: 'No custom mappings defined.',
      mapsTo: 'Maps to',
      default: 'Default',
      restoreDefaults: 'Restore Defaults',
    },
    modelVisibility: {
      title: 'Model Visibility',
      description:
        "Control which models are visible in account cards. Hidden models won't appear in the quota display.",
      searchPlaceholder: 'Search models...',
      showAll: 'Show All',
      hideAll: 'Hide All',
      reset: 'Reset to Defaults',
      save: 'Save Changes',
      noModels: 'No models found',
      modelsShown: '{{visible}} of {{total}} models visible',
      quotaManagement: 'Quota Management',
      hidden: 'Hidden',
      noModelsFound: 'No models found',
      totalModels: 'Total',
      visibleModels: 'Visible',
      hiddenModels: 'Hidden',
      saving: 'Saving...',
    },
    autoSwitchModels: {
      title: 'Auto-Switch Models Config',
      description:
        'Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.',
      searchPlaceholder: 'Search models...',
      noModels: 'No models found.',
      noModelsFound: 'No models found.',
      includeLabel: 'Include',
      priorityLabel: 'Priority',
      save: 'Save Config',
      saving: 'Saving...',
      saved: 'Auto-switch model configuration saved successfully.',
      saveFailed: 'Failed to save auto-switch model configuration.',
    },
    providerGroupings: {
      title: 'Provider Groupings',
      description: 'Group models by provider for better organization',
      enabled: 'Enable Provider Groupings',
      models: '{{count}} models',
      avgLabel: 'avg',
      resetLabel: 'reset',
      overall: 'Overall',
      healthy: 'Healthy',
      degraded: 'Degraded',
      limited: 'Limited',
      critical: 'Critical',
    },
    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Copy',
      copied: 'Copied!',
      openai_protocol: 'OpenAI Protocol',
      anthropic_protocol: 'Anthropic Protocol',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Fast',
      pro: 'Pro',
      flash_preview: 'Preview',
      pro_high: 'Best',
      sonnet: 'Thinking',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Service',
      description: 'Control the local API proxy server.',
      status_running: 'Running',
      status_stopped: 'Stopped',
      action_start: 'Start Service',
      action_stop: 'Stop Service',
      accounts_info: '{{count}} accounts available',
      port: 'Listen Port',
      port_hint: 'Default 8045, restart required to apply changes',
      timeout: 'Request Timeout',
      timeout_hint: 'Default 120s, range 30-600s',
      api_key: 'API Key',
      regenerate_key: 'Regenerate',
      regenerateConfirm: {
        title: 'Regenerate API Key?',
        description:
          'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
        cancel: 'Cancel',
        confirm: 'Regenerate',
      },
      key_warning: 'Keep your API key secure. Do not share it.',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
    },
    proxy_tab: 'Proxy',
    save: 'Save Settings',
  },
  toast: {
    backupSuccess: {
      title: 'Success',
      description: 'Account backup created successfully.',
    },
    backupError: {
      title: 'Error',
      description: 'Failed to create backup: {{error}}',
    },
    switchSuccess: {
      title: 'Success',
      description: 'Switched account successfully.',
    },
    switchError: {
      title: 'Error',
      description: 'Failed to switch account: {{error}}',
    },
    deleteSuccess: {
      title: 'Success',
      description: 'Account backup deleted successfully.',
    },
    deleteError: {
      title: 'Error',
      description: 'Failed to delete backup: {{error}}',
    },
  },
  cloud: {
    'total-accounts': 'Total accounts',
    title: 'Accounts',
    description: 'Manage your Google Gemini accounts.',
    security: {
      compatibilityMode: {
        title: 'Security keys are saved on this computer',
        description:
          'Secure system storage is unavailable, so security keys are saved in a local file. Keep this computer and its backups private.',
      },
    },
    autoSwitch: 'Auto-Switch',
    providerGroupings: 'Provider Groupings',
    addAccount: 'Add Account',
    checkQuota: 'Check Quota Now',
    polling: 'Polling triggered',
    globalQuota: 'Global Quota',
    layout: {
      auto: 'Auto',
      twoCol: '2 Columns',
      threeCol: '3 Columns',
      list: 'List',
      compact: 'Compact',
    },
    'auto-switch-client': 'Auto-switch client account',
    'auto-switch-description':
      'Switches accounts in Antigravity, IDE, and CLI. Choose which accounts API requests use on the API Proxy page.',
    'quota-display': {
      title: 'Quota display',
      description:
        'Choose what appears on account cards. This does not change quota or which account is used for requests.',
      'five-hours-gemini': 'Gemini 5-hour quota',
      'five-hours-claude': 'Claude 5-hour quota',
      'weekly-gemini': 'Gemini weekly quota',
      'weekly-claude': 'Claude weekly quota',
    },
    'quota-window': {
      label: 'Quota window',
      'five-hours': '5-hour quota',
      'five-hours-short': '5h',
      weekly: 'Weekly quota',
      'weekly-short': 'Week',
      'compact-weekly-short': 'Wk',
      'both-short': 'Both',
      'no-weekly-quota': 'No weekly quota data',
      'weekly-summary-unavailable': 'The model service did not provide weekly usage information.',
      'weekly-bucket-unavailable': 'Weekly usage could not be found in the information returned.',
    },
    recommendation: {
      badge: 'Recommended Next',
      description: 'Automatically selected from the latest fetched {{context}} quota.',
      context: {
        overall: 'overall',
        claude: 'Claude',
        pro3: 'Gemini Pro',
        flash: 'Gemini Flash',
      },
    },
    authDialog: {
      'manual-sign-in': 'Enter a code manually',
      'waiting-for-browser':
        'Complete sign-in in your browser. This window will update when it finishes.',
      title: 'Add Google Account',
      description:
        'Choose a sign-in method, then sign in to Google in your browser. Your account will be added automatically.',
      oauthClient: 'Sign-in method',
      oauthClientPlaceholder: 'Select a sign-in method',
      openLogin: 'Open Login Page',
      authCode: 'Authorization Code',
      placeholder: 'Paste the code starting with 4/...',
      instruction: 'If automatic sign-in does not finish, paste the code from the browser here.',
      verify: 'Verify & Add',
    },
    localImport: {
      trigger: 'Import from this computer',
      title: 'Import from this computer',
      description:
        'Find accounts already signed in on this computer. Review the results before importing.',
      scanning: 'Scanning and verifying local accounts…',
      importing: 'Importing the confirmed accounts…',
      summary: 'Local account scan summary',
      accounts: 'Accounts',
      validationFailures: 'Verification failures',
      discoveryFailures: 'Source failures',
      merged: 'Merged',
      noAccounts: 'No verified local accounts were found.',
      issues: 'Items that will not be imported',
      project: 'Project',
      emailCollision: '{{email}} has {{count}} different saved sign-ins.',
      rescan: 'Scan Again',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Import {{count}} Accounts',
      resultTitle: 'Local account import complete',
      resultDescription: 'The account list has been updated with the confirmed result.',
      imported: 'Imported {{count}}',
      skipped: 'Skipped {{count}}',
      failed: 'Failed {{count}}',
      sources: {
        'antigravity-keyring': 'System sign-in storage',
        'antigravity-classic-db': 'Antigravity saved accounts',
        'antigravity-ide-db': 'Antigravity IDE saved accounts',
        'legacy-agent': 'Legacy Agent Data',
      },
      validationErrors: {
        'credential-unavailable':
          'These sign-in details are no longer available. Sign in to Antigravity again, then rescan.',
        'authentication-failed':
          'Google did not accept this sign-in. Sign in to Antigravity again, then rescan.',
        'network-failed': 'The account could not be verified because of a network error.',
        'timed-out': 'Account verification timed out.',
        'unverified-email': 'The Google account email is not verified.',
        'invalid-profile': 'Google returned an invalid account profile.',
      },
      discoveryErrors: {
        missing: 'No saved sign-in details were found here.',
        'permission-denied':
          'Access to the saved sign-in details was denied. Check the access permissions and try again.',
        locked:
          'The saved sign-in details are locked or in use. Unlock access or close Antigravity, then rescan.',
        malformed:
          'The saved sign-in details could not be read. Sign in to Antigravity again, then rescan.',
        'timed-out': 'Reading the saved sign-in details took too long. Please rescan.',
        'read-failed': 'The saved sign-in details could not be read. Please rescan.',
      },
      importErrors: {
        'credential-unavailable':
          'These sign-in details are no longer available. Rescan before importing.',
        'identity-required': 'A verified account identity is required.',
        'identity-conflict':
          'These sign-in details do not match the existing account. Please review the accounts before importing.',
        'persistence-failed': 'The account could not be saved.',
      },
      errors: {
        'preview-failed': 'The local account preview could not be prepared.',
        'session-not-found': 'These scan results are no longer available. Please scan again.',
        'session-expired': 'These scan results have expired. Please scan again.',
        'session-consumed':
          'These scan results have already been used. Scan again to import more accounts.',
        'confirmation-failed': 'The local account import could not be completed.',
        'internal-error': 'The local account import request failed.',
      },
    },
    card: {
      active: 'Active',
      use: 'Use',
      rateLimited: 'Rate Limited',
      validationRiskControlled: 'Risk / Rate Limited',
      validationOAuthReauthRequired: 'Sign in to Google again',
      validationRequired: 'Verification Required',
      completeValidation: 'Verify',
      left: 'left',
      used: 'Used',
      unknown: 'Unknown User',
      actions: 'Actions',
      useAccount: 'Use Account',
      identityProfile: 'Identity Profile',
      refresh: 'Refresh Quota',
      delete: 'Delete Account',
      noQuota: 'No quota data',
      rateLimitedQuota: 'Rate Limited',
      liveLimitModelNotSupported: 'Model not supported',
      liveLimitModelForbidden: 'Model forbidden',
      liveLimitQuotaExhausted: 'Quota exhausted',
      liveLimitRateLimited: 'Rate limited',
      liveLimitRemaining: '{{duration}} remaining',
      liveLimitDetectedAgo: 'detected {{duration}} ago',
      liveLimitActiveTitle: 'The model service is temporarily unavailable.',
      liveLimitRecentTitle: 'The model service recently reported an error.',
      liveLimitQuotaSnapshot: 'The last quota check may still show {{percentage}}%.',
      liveLimitMessage: 'Message: {{message}}',
      resetPrefix: 'reset',
      resetTime: 'Reset time',
      resetUnknown: 'Unknown',
      detailedQuota: 'Detailed quota',
      quotaGroupUnknown: 'Quota group',
      gemini3Ready: 'Gemini 3 Ready',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'e.g. http://127.0.0.1:7890',
      proxySaved: 'Proxy saved',
      'network-proxy': 'Network proxy',
      'network-proxy-description':
        'Optional: use a network proxy for this account. Press Enter or leave the address field to save.',
      'proxy-replace-placeholder': 'Enter a new proxy address',
      'proxy-remove': 'Remove proxy',
      'proxy-save-failed': 'Could not save proxy',
      noProxy: 'No proxy',
      aiCredits: 'AI Credits',
      aiCreditsValue: '{{amount}} credits',
      creditsExpiry: 'expires {{date}}',
      modelVisibility: 'Model Visibility',
    },
    identity: {
      'profile-errors': {
        'account-not-found': 'This account is no longer available.',
        'baseline-unavailable': 'There is no original identity profile to restore.',
        'revision-not-found': 'The selected identity profile could not be found.',
        'profile-invalid': 'This identity profile cannot be used. Choose another one.',
        'profile-write-failed': 'Could not save the identity profile. Please retry.',
        'profile-operation-failed': 'Could not complete the identity action. Please retry.',
      },
      title: 'Account device information',
      loading: 'Loading...',
      generateAndBind: 'Create new device information',
      captureAndBind: 'Use current device information',
      restoreOriginal: 'Restore original device information',
      openFolder: 'Open device information folder',
      previewTitle: 'New device information',
      confirm: 'Confirm',
      cancel: 'Cancel',
      close: 'Close',
      currentStorage: 'Current device settings',
      accountBinding: 'Saved for this account',
      history: 'Saved versions',
      noHistory: 'No identity history',
      current: 'Active',
      restore: 'Restore',
      generateSuccess: 'Identity created and bound',
      captureSuccess: 'Current identity captured and bound',
      restoreOriginalSuccess: 'Baseline identity restored',
      restoreVersionSuccess: 'Historical identity restored',
      deleteVersionSuccess: 'Historical identity deleted',
      openFolderSuccess: 'Identity storage opened',
      baseline: 'Original device information',

      description: 'Save device information for this account to use when switching accounts.',
      'load-failed': 'Could not read device information',
      'retry-description': 'Please retry. Your saved device information has not been changed.',
      'refresh-failed': 'Could not refresh. Previously loaded device information is still shown.',
      updating: 'Updating device information…',
      'device-id': 'Device ID',
      'mac-device-id': 'Mac device ID',
      'installation-id': 'Installation ID',
      'diagnostic-id': 'Diagnostics ID',
      'delete-version': 'Delete saved version: {{label}}',
    },
    list: {
      noAccounts: 'No cloud accounts added yet.',
      noFilteredAccounts: 'No accounts match the selected tiers.',
    },
    error: {
      loadFailed: 'Failed to load cloud accounts.',
      'report-issue': 'Report this problem',
      'report-preparing': 'Preparing error information…',
      'report-copied': 'Error information copied',
      'report-paste-guide':
        'Paste it into the GitHub report, describe what you were doing, then submit.',
      'report-copy-failed': 'Could not copy the error information',
      'report-retry': 'Please try again. You can also open Details and copy the error manually.',
      'report-open-failed': 'Could not open GitHub',
      'report-manual-open':
        'Your error information is copied. Open {{url}} and paste it into the report.',
      dataRepair: {
        title: "Saved accounts can't be opened",
        description:
          "The app can't read some saved accounts. This can happen after changing computer accounts or if local files are damaged.",
        stepReLogin:
          'If reopening the app does not help, sign in again or re-add the affected accounts. Keep your existing app data until your accounts are restored.',
        stepMacPrivacy:
          'On macOS, check for permission prompts. Move the app to the Applications folder, then open it again.',
        stepCheckGithub: 'Check the GitHub repository README for the latest troubleshooting steps.',
        stepOpenIssue:
          'Report this problem on GitHub. Click to copy your error information and open the report form.',
        openRepository: 'Open GitHub Repository',
      },
    },
    toast: {
      validationLinkFailed: {
        title: 'Could not open the Google verification page',
        codes: {
          'account-not-found': 'This account is no longer available.',
          'no-trusted-link': 'No Google verification page is available for this account.',
          'validation-link-failed': 'Could not open the Google verification page. Try again.',
        },
      },
      addSuccess: 'Account added successfully!',
      addFailed: {
        title: 'Failed to add account',
        codes: {
          'authorization-denied': 'Google authorization was denied. Try again to add the account.',
          'login-active': 'A Google sign-in is already in progress.',
          'login-cancelled': 'Sign-in was cancelled.',
          'login-timeout': 'Sign-in timed out. Start again when ready.',
          'duplicate-account': 'This Google account is already added.',
          'browser-open-failed':
            'Could not open the browser. Check your default browser and retry.',
          'login-failed': 'Could not add the account. Please retry.',
        },
      },
      quotaRefreshed: 'Quota refreshed',
      refreshFailed: 'Failed to refresh quota',
      pollFailed: 'Failed to poll quota for all accounts',
      switched: {
        title: 'Account switched!',
        description: 'Restarting Antigravity...',
      },
      switchFailed: 'Failed to switch account',
      switchFailureCodes: {
        'account-not-found': 'This account is no longer available.',
        'reauth-required': 'Sign in to this account again before switching.',
        'identity-profile-required': 'Set up an identity profile before switching.',
        'process-control-failed': 'Could not close or restart Antigravity. Please retry.',
        'target-write-failed': 'Could not use the selected account in Antigravity. Try again.',
        'switch-failed': 'Could not switch accounts. Please retry.',
      },
      deleted: 'Account deleted',
      deleteFailed: 'Failed to delete account',
      deleteConfirm: 'Are you sure you want to delete this account?',
      autoSwitchOn: 'Auto-Switch Enabled',
      autoSwitchOff: 'Auto-Switch Disabled',
      updateSettingsFailed: 'Failed to update settings',
      actionFailed: 'Action failed',
      startAuthFailed: 'Failed to start sign-in flow',
      refreshCreditsAvailable: 'AI credits: {{amount}}',
      refreshCreditsUnavailable: 'AI credits not available for this refresh.',
      batchRefreshSuccess: 'Successfully refreshed {{count}} accounts.',
      batchRefreshPartial: {
        title: 'Refresh completed with issues',
        description: 'Refreshed {{successful}} accounts, {{failed}} failed.',
      },
      batchDeleteSuccess: 'Successfully deleted {{count}} accounts.',
      batchDeletePartial: {
        title: 'Deletion completed with issues',
        description: 'Deleted {{successful}} accounts, {{failed}} failed.',
      },
    },
    batch: {
      actions: 'Selected account actions',
      'delete-title': 'Delete {{count}} accounts?',
      cancel: 'Cancel',
      selected: 'Selected {{count}}',
      delete: 'Delete Selected',
      refresh: 'Refresh Selected',
      selectAll: 'Select All',
      clear: 'Clear Selection',
      confirmDelete: 'Are you sure you want to delete {{count}} accounts?',
    },
    tierFilter: {
      all: 'All tiers',
      reset: 'Reset to all',
      selectedCount: '{{count}} tiers',
      unknown: 'Unknown',
    },
    sort: {
      recentlyUsed: 'Recently Used',
      quotaOverall: 'Overall Quota',
      quotaClaude: 'Claude Quota',
      quotaPro3: 'Pro3 Quota',
      quotaFlash: 'Flash Quota',
    },
    exportImport: {
      'file-errors': {
        'file-too-large': 'The selected file is too large. Choose a smaller account backup.',
        'invalid-export':
          'This account backup could not be recognized. Choose a valid backup file.',
        'read-failed': 'Could not open the selected file. Check that it is still in place.',
        'write-failed': 'Could not save the account backup. Check the save location and try again.',
        'import-failed': 'Could not import the accounts. Please try again.',
        'tokens-missing':
          'This account backup is missing sign-in details. Export a backup that includes them.',
        'account-write-failed': 'Unable to save this account.',
      },
      export: 'Export',
      import: 'Import',
      exportTitle: 'Export Accounts',
      exportDesc:
        'Choose whether to include account sign-in details. Keep backups with sign-in details private.',
      includeTokens: 'Include sign-in details (restores accounts)',
      stripTokens: 'Exclude sign-in details (safer to share)',
      exportSuccess: 'Accounts exported successfully',
      importTitle: 'Import Accounts',
      importDesc: 'Select a previously exported JSON file.',
      importStrategy: 'Import Strategy',
      strategyMerge: 'Merge - Update existing, add new',
      strategyOverwrite: 'Overwrite - Replace all existing data',
      strategySkip: 'Skip - Only add new accounts',
      importSuccess: 'Imported {{imported}}, updated {{updated}}, skipped {{skipped}}',
      importErrors: 'Import completed with {{count}} error(s)',
      selectFile: 'Select File',
      importing: 'Importing...',
      fileTooLarge: 'File size exceeds 5MB limit',
      invalidJson: 'Invalid JSON file format',
      readFileFailed: 'Failed to read file',
    },

    feedback: {
      'loading-title': 'Reading your accounts',
      'loading-description': 'Your account details will appear here when they are ready.',
      'empty-description': 'Choose Add Account to sign in, or import an existing account file.',
      'filtered-description': 'Try another plan or clear the filter to see more accounts.',
    },
  },
  proxy: {
    'advanced-options': 'More service settings',
    'advanced-description': 'Account selection, shared instructions and tool compatibility.',
    tabs: { tools: 'Tools', models: 'Models', records: 'Records', examples: 'Examples' },
    'account-strategy': {
      'save-failed': 'Could not save your choice. Please select it again to retry.',
      title: 'Accounts used for API requests',
      balanced: 'Rotate between available accounts',
      'account-first': 'Prefer the same account',
      'balanced-description':
        'Distributes new conversations across available accounts. An existing conversation keeps its account while it remains available.',
      'account-first-description':
        'For each model, keep using the same account. Switch when its quota is exhausted, it is temporarily limited, or it cannot serve the request. Existing conversations keep their available account.',
      'client-description':
        'This setting does not change the account signed in to Antigravity, IDE, or CLI. Client auto-switching is controlled on the Accounts page.',
    },
    title: 'API Proxy',
    description: 'Manage the local API proxy service.',
    save: 'Save Settings',
    copy: 'Copy',
    copied: 'Copied!',
    regenerate: 'Regenerate',
    regenerateConfirm: {
      title: 'Regenerate API Key?',
      description:
        'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
      cancel: 'Cancel',
      confirm: 'Regenerate',
    },
    'risk-confirmation': {
      title: 'Confirm the risks before starting the proxy',
      description:
        'Since February, Google has intensified enforcement. Simply switching accounts with this software will not affect your Google account.\n\nHowever, using it as a reverse proxy or for similar purposes violates Google’s Terms of Service and may result in account suspension.',
      'account-advice': 'Only use accounts you can afford to lose.',
      cancel: 'Cancel',
      confirm: 'I understand the risks. Start the proxy',
    },
    service: {
      title: 'Service Status',
      description: 'Control the local API proxy server.',
      running: 'Running',
      stopped: 'Stopped',
      start: 'Start Service',
      stop: 'Stop Service',
      start_failed: 'Failed to start service',
      port_in_use_title: 'Port is already in use',
      port_in_use_description:
        'Port {{port}} is already in use by another process. Close that process, or change the API proxy listen port in Settings and try again.',
    },
    config: {
      port: 'Listen Port',
      timeout: 'Request Timeout',
      api_key: 'API Key',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
      cloud_code_meta: 'Cloud Code compatibility',
      cloud_code_meta_desc:
        'Add the extra response information needed by older Cloud Code clients. Leave off unless your client needs it, as other clients may not accept it.',
      'allow-local-video-paths': 'Allow local video paths',
      'allow-local-video-paths-desc':
        'Let connected tools read video files on this computer that your user account can access. Enable only for tools you trust.',
      'global-system-prompt-title': 'Instructions for all AI requests',
      'global-system-prompt-description':
        'Automatically add these instructions before the instructions from each connected tool, for every request sent through Manager.',
      'global-system-prompt-placeholder':
        'Enter a global system prompt...\nFor example: Reply in Simplified Chinese and explain code changes concisely.',
      'global-system-prompt-character-count': '{{count}} characters',
      'global-system-prompt-long-warning':
        'More than 2,000 characters leaves less room for conversation history. Consider shortening these instructions.',
      local_access: 'Local network access:',
      select_ip: 'Select IP',
      no_token_warning: '⚠️ API key is not set. Access is open to everyone!',
      show_key: 'Show',
      hide_key: 'Hide',
    },
    mapping: {
      title: 'Model Mapping',
      description: 'Choose which Gemini model handles each Claude model request.',
      maps_to: 'Maps to',
      restore: 'Restore Defaults',
      'only-raw-quota-models': 'Only list models found in your accounts',
      'only-raw-quota-models-desc':
        'Connected tools see only model names from the latest account quota checks. Additional model aliases are not listed.',
    },
    'open-code': {
      title: 'OpenCode sync',
      description:
        'Connect OpenCode to Manager while keeping your other settings, comments and formatting.',
      synced: 'Synced',
      'synced-custom-url': 'Synced with custom URL',
      'not-synced': 'Not synced',
      'config-path': 'Configuration',
      'configured-models': 'Configured models',
      runtime: 'OpenCode installation',
      installed: 'Installed',
      'not-installed': 'Not detected',
      credential: 'OpenCode connection key',
      'key-stored': 'Saved in secure system storage',
      'key-missing': 'Created on the next sync',
      'backup-notice':
        'Backups keep comments and formatting. The Manager connection key is replaced with a value that cannot be used; restoring uses the current key.',
      sync: 'Configure and sync OpenCode',
      restore: 'Restore backup',
      clear: 'Clear managed configuration',
      revoke: 'Revoke dedicated key',
      'model-dialog-title': 'Choose OpenCode models',
      'model-dialog-description':
        'Selected models are added or updated. Unselected existing models are not deleted.',
      'custom-base-url': 'Manager address',
      'reset-base-url': 'Reset',
      'invalid-base-url': 'Enter a valid HTTP or HTTPS URL.',
      'sync-accounts': 'Use accounts in the OpenCode sign-in plugin',
      'sync-accounts-description':
        'When enabled, OpenCode saves information that keeps these accounts signed in to a file on this computer. This is off by default. Only enable it on a computer you trust.',
      'select-models': 'Models to add or update',
      'selected-count': '{{selected}} of {{total}} selected',
      'select-all': 'Select all',
      'deselect-all': 'Deselect all',
      'confirm-sync': 'Confirm sync',
      'auth-plugin-warning-title': 'Another sign-in plugin was found',
      'auth-plugin-warning-description':
        'opencode-antigravity-auth may use a different connection. Check that Manager is selected in OpenCode before using these settings.',
      'view-config': 'View configuration',
      'restore-confirm-title': 'Restore OpenCode backup?',
      'restore-confirm-description':
        'This replaces the whole settings file with the original backup, including later edits. The backup is used once.',
      'confirm-restore': 'Confirm restore',
      'clear-confirm-title': 'Remove the Manager connection?',
      'clear-confirm-description':
        'Remove this connection and its dedicated key. Other providers, settings and the backup are kept.',
      'confirm-clear': 'Confirm clear',
      'config-viewer-title': 'OpenCode configuration',
      'config-viewer-description': 'Read-only configuration preview',
      'config-redacted-notice': 'Private values are hidden in this preview.',
      'config-copied': 'Configuration copied with private values hidden',
      'config-copy-failed': 'Failed to copy configuration',
      'config-load-failed': 'Failed to load configuration',
      'copy-config': 'Copy configuration (private values hidden)',
      'success-title': 'OpenCode configuration updated',
      'error-title': 'OpenCode update failed',
      'unknown-error': 'Unknown OpenCode configuration error',

      'choose-model-hint': 'Choose at least one model to continue.',
      'config-retry-description': 'Please retry. Your saved configuration has not been changed.',
    },
    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
    },
    persistence: {
      title: 'Request history and reasoning',
      description: 'Keep requests and conversation history on this device to help diagnose issues.',
      'audit-title': 'Request history',
      'audit-description':
        'Save requests, replies and attempts to reach the model service on this computer, with sensitive details hidden.',
      rows: '{{count}} requests',
      queue: '{{count}} records waiting to be saved',
      dropped:
        '{{count}} records could not be saved ({{reason}}). Model requests continued normally.',
      'disk-gib': 'Disk limit (GiB)',
      'body-hours': 'Full content retention (hours)',
      'summary-days': 'Summary retention (days)',
      'max-rows': 'Maximum rows',
      'no-audit': 'No traffic records yet.',
      'audit-metadata': 'Request details and model-service attempts',
      'audit-body-missing': 'The full request or reply content is no longer saved.',
      'audit-body-expired':
        'The full content has expired, but the request details are still available.',
      partial: 'Partial',
      'logical-size': 'Content size',
      'parse-error-offset': 'Position that could not be read',
      loading: 'Loading…',
      'copy-progress': 'Preparing full copy: {{value}}%',
      'previous-page': 'Previous page',
      'next-page': 'Next page',
      'copy-full': 'Copy complete body',
      'confirm-copy-full': 'Confirm copying {{size}}',
      'clear-audit': 'Clear request history',
      'repair-audit': 'Repair request history',
      'thought-title': 'Conversation reasoning history',
      'thought-description': 'Save reasoning so later turns can continue the conversation.',
      sessions: '{{count}} sessions',
      'hard-limit': 'Each conversation can save up to 200 turns and 64 MiB of content.',
      'retention-days': 'Retention (days)',
      'max-sessions': 'Maximum sessions',
      oversized: 'Content exceeded 64 MiB and was not saved in full.',
      'no-thought-body': 'No saved reasoning content.',
      signature: 'Signature',
      'copy-signature': 'Copy signature',
      'no-thought': 'No reasoning history yet.',
      'clear-thought': 'Clear reasoning history',
      'repair-thought': 'Repair reasoning history',
      'confirm-clear': 'Confirm clear',
      'confirm-repair': 'Confirm repair',
    },
  },
};
export default en;
