const ru = {
  'agent-tools': {
    title: 'Подключение инструментов программирования',
    description: 'Выберите инструмент для использования моделей через Antigravity Manager.',
    loading: 'Чтение настроек…',
    installed: 'Установлен',
    'not-installed': 'Установка не обнаружена',
    'read-error': 'Не удалось прочитать настройки. Повторите попытку перед изменением.',
    retry: 'Повторить',
    configured: 'Настройки сохранены',
    'custom-address': 'Используется другой адрес',
    'not-configured': 'Не настроен',
    'not-verified': 'Запросы не проверены',
    address: 'Адрес Manager',
    model: 'Модель',
    'not-set': 'Не задан',
    'choose-model': 'Выберите при настройке',
    update: 'Обновить настройки',
    configure: 'Настроить',
    view: 'Посмотреть настройки',
    restore: 'Восстановить копию',
    remove: 'Удалить подключение',
    'install-notice':
      'Можно сохранить настройки до установки инструмента. Затем откройте его заново.',
    'action-error': 'Не удалось обновить настройки',
    saved: 'Настройки обновлены',
    reopen: 'Откройте {{name}} заново, чтобы применить настройки.',
    'configure-title': 'Подключить {{name}}',
    'configure-description':
      'Запросы будут проходить через Manager. Перед первым изменением сохраняется резервная копия.',
    'restore-title': 'Восстановить настройки {{name}}?',
    'restore-description':
      'Весь файл будет заменён исходной копией, включая последующие правки. Если файл создан Manager, он будет удалён. Копия используется один раз.',
    'remove-title': 'Удалить подключение к Manager?',
    'remove-description':
      'Восстанавливает прежние параметры подключения, сохраняя остальные настройки и копию.',
    'preview-title': 'Настройки {{name}}',
    'preview-description':
      'Показаны только настройки подключения к Manager. Ключи подключения скрыты.',
    confirm: 'Подтвердить',
    advanced: 'Адрес и файл настроек',
    'reset-address': 'Использовать текущий адрес Manager',
    'backend-files':
      'Эти настройки сохраняются на компьютере, где запущена служба Manager, для запустившего её пользователя.',
    'backup-notice':
      'Первая копия сохраняется при обновлениях. Откройте инструмент заново после сохранения.',
    'toml-notice':
      'Оформление и комментарии в настройках Codex могут измениться. Для восстановления сохраняется полная копия. Данные входа и разрешения сохраняются.',
    'codex-review':
      'Настраиваются запросы задач и автоматической проверки. Существующие активные маршруты проверки и настройки подтверждения сохраняются.',
    'model-count': 'Моделей: {{count}}',
    'plugin-notice': 'Установлен плагин прямого входа. Убедитесь, что в OpenCode выбран Manager.',
    'revoke-key': 'Отключить ключ подключения OpenCode',
    errors: {
      unavailable: 'Настройки недоступны. Повторите попытку.',
      'invalid-config': 'Файл некорректен или слишком большой. Исправьте его перед настройкой.',
      'read-failed': 'Не удалось прочитать файл. Проверьте права доступа.',
      'write-failed': 'Не удалось сохранить. Резервная копия сохранена.',
      'backup-failed': 'Не удалось создать копию. Настройки инструмента не изменены.',
      'backup-missing': 'Резервная копия отсутствует.',
      'configuration-changed': 'Настройки изменились во время операции. Прочитайте их заново.',
      'key-missing': 'Сначала создайте ключ на странице прокси.',
      'review-route-disabled':
        'Маршрут проверки Codex отключён. Включите его в настройках маршрутизации моделей.',
    },

    'address-help': 'Оставьте текущий адрес Manager, если сервис не работает на другом компьютере.',
    'invalid-address':
      'Укажите адрес Manager с http:// или https://, без данных входа и дополнительных параметров.',
    'model-required': 'Выберите модель перед сохранением.',
  },
  appName: 'Antigravity Manager',
  'process-runtime': {
    'update-in-progress': 'Antigravity обновляется. Завершите обновление и попробуйте снова.',
    'close-failed':
      'Не удалось закрыть Antigravity. Сохраните чаты и файлы, закройте приложение вручную и повторите попытку.',
    'exit-unconfirmed':
      'Antigravity ещё не закрыт. Сохраните чаты и файлы, закройте приложение вручную и повторите попытку.',
    working: 'Обработка...',
    busy: 'Antigravity занят. Дождитесь завершения операции.',
    'missing-executable':
      'Antigravity не найден или не открывается. Проверьте расположение приложения в настройках.',
    'target-conflict':
      'Запущенный Antigravity не соответствует установке, выбранной в настройках. Закройте его или выберите нужную установку перед сменой аккаунта.',
    'directory-conflict':
      'Antigravity использует другую папку данных. Закройте его или проверьте выбранную папку перед сменой аккаунта.',
    'probe-failed':
      'Не удалось вовремя проверить состояние Antigravity. Проверьте, открыто ли приложение, и повторите попытку.',
    'launch-failed':
      'Не удалось открыть Antigravity. Проверьте расположение приложения и разрешения доступа.',
    'startup-unconfirmed':
      'Пока не удалось подтвердить открытие Antigravity. Повторный запуск не выполнялся. Проверьте приложение перед новой попыткой.',
    'switched-hot-unconfirmed':
      'Новый аккаунт сохранён, но смена в Antigravity IDE не подтверждена. Проверьте аккаунт в IDE перед новой попыткой.',
    'switched-startup-unconfirmed':
      'Новый аккаунт сохранён, но открытие Antigravity не подтверждено. Повторный запуск не выполнялся. Проверьте приложение перед новой попыткой.',
  },
  common: {
    close: 'Закрыть',
    cancel: 'Отмена',
    'core-unavailable-title': 'Не удалось подключиться к Antigravity Manager',
    'core-unavailable-body':
      'Аккаунты и прокси сейчас недоступны. Закройте и снова откройте Antigravity Manager. Если проблема останется, установите последнюю версию.',
    'account-data-unavailable-title': 'Не удаётся открыть сохранённые аккаунты',
    'account-data-unavailable-body':
      'Сейчас не удаётся прочитать сохранённые аккаунты. Убедитесь, что вы вошли в свой обычный аккаунт на этом компьютере, затем снова откройте Antigravity Manager. Данные аккаунтов не изменены.',
    'already-running-title': 'Antigravity Manager уже запущен',
    'already-running-body':
      'Закройте другое окно Antigravity Manager и повторите попытку. Если не можете его найти, перезагрузите компьютер.',
    loading: 'Загрузка...',
    error: 'Ошибка',
    unknown: 'Неизвестно',
    notAvailable: 'Н/Д',
    openMenu: 'Открыть меню',

    'dismiss-notification': 'Закрыть уведомление',
    'reading-settings': 'Читаем ваши настройки…',
  },
  status: {
    services: 'Приложения',
    dashboard_title: 'Состояние приложений',
    open_dashboard: 'Показать состояние приложений',
    checking_short: 'Проверка…',
    running_short: 'Работает',
    stopped_short: 'Не запущено',
    all_running: 'Все приложения работают',
    all_stopped: 'Приложения не запущены',
    partial_running: 'Работают {{running}}/{{total}} приложений',
    checking: 'Проверка статуса...',
    running: 'Antigravity работает в фоне',
    stopped: 'Служба Antigravity остановлена',
  },
  action: {
    stop: 'Стоп',
    start: 'Старт',
    switch: 'Переключить',
    deleteBackup: 'Удалить резервную копию',
    backupCurrent: 'Создать бэкап текущего',
    retry: 'Повторить',
    details: 'Подробности',
    openLogs: 'Открыть папку логов',
  },
  update: {
    title: 'Обновления',
    checking: 'Проверка...',
    checkNow: 'Проверить обновления',
    checkFailed: 'Не удалось проверить обновления',
    upToDate: 'У вас последняя версия.',
    unsupported: 'Проверка обновлений недоступна на этой платформе.',
    available: {
      title: 'Доступно обновление',
      description: 'Версия {{version}} доступна на GitHub.',
      download: 'Скачать',
      downloading: 'Скачивание...',
      dismiss: 'Закрыть',
      macosUnsignedNote:
        'Эта сборка macOS официально не подписана. Если macOS блокирует приложение, следуйте шагам ручной подписи в GitHub README или связанных issues.',
    },
    downloaded: {
      title: 'Обновление готово',
      description: 'Версия {{version}} загружена.',
      restart: 'Перезапустить',
    },
  },
  error: {
    generic: 'Произошла непредвиденная ошибка.',
    detailsTitle: 'Детали ошибки',
    detailsDescription:
      'Эти сведения помогут разобраться в проблеме и могут содержать расположение личных файлов. Проверьте их перед отправкой.',
    keychainUnavailable: 'Сейчас не удаётся прочитать сохранённые данные для входа.',
    keychainHint: {
      translocation: 'Переместите приложение в папку «Программы» и откройте его снова.',
      keychainDenied:
        'macOS заблокировала доступ к сохранённым данным для входа. Проверьте инструкцию по установке приложения и повторите попытку.',
      signNotarize: 'По возможности установите версию, проверенную macOS.',
    },
    dataMigrationFailed: 'Не удаётся прочитать аккаунты, сохранённые в предыдущей версии.',
    masterKeyUnavailable:
      'Сохранённые аккаунты найдены, но сейчас их не удаётся открыть. Данные аккаунтов не изменены.',
    dataMigrationHint: {
      relogin: 'Пожалуйста, перезайдите в аккаунт или добавьте его заново.',
      clearData: 'Если ошибка сохраняется, очистите локальные данные и войдите снова.',
    },
    antigravityStorageJsonNotFound:
      'Первоначальная настройка Antigravity не завершена. Откройте выбранное приложение и войдите один раз, затем повторите смену аккаунта.',
    antigravityProjectIdMissing:
      'Этот аккаунт ещё не готов к работе с Antigravity. Войдите с ним в Antigravity один раз, затем повторите попытку.',
    antigravityDatabasePermissionDenied:
      'Не удалось сохранить данные входа Antigravity. Проверьте доступ на запись в папку данных или откройте Antigravity и перезапустите Manager.',
    cloudAccountLoginExpired:
      'Данные входа для этого облачного аккаунта устарели. Пожалуйста, войдите снова.',
  },
  nav: {
    navigation: 'Навигация',
    'collapse-sidebar': 'Свернуть боковую панель',
    'expand-sidebar': 'Развернуть боковую панель',
    accounts: 'Аккаунты',
    proxy: 'API Прокси',
    settings: 'Настройки',
  },
  editionSelection: {
    title: 'Выберите версию Antigravity',
    description:
      'Выберите, какую версию Antigravity вы используете. Это поможет менеджеру подключиться к правильному приложению.',
    edition1x: {
      name: 'Antigravity 1.x',
      description:
        'Оригинальное приложение Antigravity. Выберите это, если вы используете устаревшую версию.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description:
        'Новый Antigravity IDE (2.0). Выберите это, если вы используете последнюю версию IDE.',
    },
    confirm: 'Продолжить',
  },
  account: {
    current: 'Текущий',
    lastUsed: 'Последнее использование {{time}}',
    switchToAntigravity: 'Переключиться на Antigravity',
    switchToIde: 'Переключиться на Antigravity IDE',
  },
  home: {
    title: 'Аккаунты',
    description: 'Управление вашими аккаунтами Antigravity Google Gemini.',
    noBackups: {
      title: 'Бэкапы не найдены',
      description: 'Создайте резервную копию вашего текущего аккаунта Antigravity, чтобы начать.',
      action: 'Создать бэкап текущего аккаунта',
    },
  },
  settings: {
    'service-unavailable':
      'Сейчас не удаётся открыть или сохранить настройки. Повторите попытку. Если проблема останется, закройте и снова откройте Antigravity Manager.',
    'service-retry': 'Повторить',
    'service-restart-required':
      'Настройки сохранены. Выключите и снова включите прокси, чтобы изменения вступили в силу.',
    'service-save': 'Сохранить',
    'service-secret-configured': 'Адрес прокси уже задан. Введите новый адрес, чтобы заменить его.',
    'weekly-warmup': {
      error: 'Не удалось загрузить или сохранить настройки прогрева.',
      retry: 'Повторить',
      'cost-notice':
        'Прогрев расходует квоту модели и может использовать AI credits. Принятие HTTP-запроса не гарантирует запуск недельного таймера.',
      title: 'Прогрев недельной квоты',
      description:
        'После сброса выбранной недельной квоты отправляет один минимальный запрос на каждый сегмент и сохраняет успешный цикл.',
      enabled: 'Включить прогрев недельной квоты',
      groups: 'Группы квот для прогрева',
      group: { claude: 'Группы квот Claude', gemini: 'Группы квот Gemini' },
    },
    title: 'Настройки',
    description: 'Управление настройками приложения.',
    general: 'Общие',
    connection: 'Подключение',
    models: 'Модели',
    appearance: {
      title: 'Внешний вид',
      description: 'Настройте внешний вид Antigravity Manager.',
    },
    darkMode: 'Темная тема',
    darkModeDescription: 'Включить темную тему для комфортной работы ночью.',
    language: {
      title: 'Язык',
      description: 'Выберите язык интерфейса.',
      english: 'English',
      chinese: '中文 (简体)',
      russian: 'Русский',
      vietnamese: 'Вьетнамский',
      turkish: 'Турецкий',
      french: 'Французский',
    },
    about: {
      title: 'О программе',
      description: 'Информация о приложении.',
    },
    cache: {
      title: 'Кэш Antigravity',
      description:
        'Очистите известные каталоги кэша Antigravity и Antigravity IDE, чтобы устранить ошибки входа или проверки версии.',
      clear: 'Очистить кэш Antigravity',
      dialogTitle: 'Очистить кэш Antigravity?',
      dialogDescription: 'Следующие существующие каталоги кэша будут удалены.',
      pathsLabel: 'Каталоги кэша',
      noPaths: 'Известные каталоги кэша Antigravity не найдены.',
      warning: 'Закройте Antigravity перед очисткой, чтобы избежать заблокированных файлов.',
      cancel: 'Отмена',
      confirm: 'Очистить кэш',
      clearing: 'Очистка...',
      clearedTitle: 'Кэш очищен',
      clearedDescription: 'Из каталогов кэша Antigravity удалено {{size}} МБ.',
      failedTitle: 'Не удалось очистить кэш',
      notFoundTitle: 'Кэш Antigravity не найден',

      'paths-failed': 'Не удалось найти папки кэша',
      'paths-retry-description': 'Попробуйте ещё раз перед очисткой кэша.',
      'partial-title': 'Часть кэша не удалось очистить',
      'partial-description':
        'Освобождено {{size}} МБ. Не удалось очистить {{count}} папок. Закройте Antigravity и попробуйте ещё раз.',
    },
    version: 'Версия',
    platform: 'Платформа',
    license: 'Лицензия',
    openLogDir: 'Открыть',
    toast: {
      saved: {
        title: 'Настройки сохранены',
        description: 'Конфигурация обновлена.',
      },
      saveFailed: {
        title: 'Ошибка сохранения настроек',
      },
    },
    account: {
      'client-setup': 'Расположение и запуск клиентов',
      'client-setup-description':
        'Измените, если Manager не находит клиент или нужны особые параметры запуска.',
      'choose-file': 'Выбрать файл',
      'clear-field': 'Очистить поле',
      title: 'Настройки аккаунта',
      description: 'Настройка автоматического обновления и синхронизации.',
      auto_refresh: 'Автообновление квот',
      auto_refresh_desc: 'Периодически обновлять информацию о квотах для всех аккаунтов',
      auto_sync: 'Автосинхронизация текущего',
      auto_sync_desc: 'Периодически синхронизировать активный аккаунт',
      antigravity_executable: 'Файл запуска Antigravity',
      antigravity_executable_desc:
        'Необязательный путь для поиска данных portable mode и запуска Antigravity.',
      antigravity_executable_placeholder:
        'Например: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_cli_executable: 'Исполняемый файл Antigravity CLI',
      antigravity_cli_executable_desc:
        'Путь к CLI agy. Патч проверки доступа применяется только к этому файлу.',
      antigravity_cli_executable_placeholder: 'Пример: C:\\Program Files\\Antigravity\\agy.exe',
      detect_antigravity_cli: 'Найти',
      agy_cli_detected: 'Antigravity CLI найден',
      agy_cli_detect_failed: 'Antigravity CLI не найден',
      agy_patch_desc:
        'Создаёт резервную копию CLI, проверяет единственное совпадение ARM64 или x86_64, применяет патч и повторно подписывает Mach-O в macOS.',
      agy_patch_action: 'Применить патч доступа',
      agy_patch_success: 'Antigravity CLI исправлен',
      agy_patch_already_applied: 'Патч уже применён',
      agy_patch_failed: 'Не удалось исправить Antigravity CLI',
      agy_patch_result:
        'Формат: {{format}}; архитектуры: {{architectures}}; резервная копия: {{backupPath}}',
      agy_patch_no_backup: 'не требуется',
      antigravity_ide_executable: 'Файл запуска Antigravity IDE',
      antigravity_ide_executable_desc:
        'Необязательный путь к Antigravity IDE. При переключении аккаунтов Classic процессы по этому пути защищаются от завершения.',
      antigravity_ide_executable_placeholder:
        'Например: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Аргументы запуска Antigravity',
      antigravity_args_desc: 'Необязательные аргументы запуска, например --user-data-dir.',
      antigravity_args_placeholder: 'Например: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Аргументы запуска Antigravity IDE',
      antigravity_ide_args_desc:
        'Необязательные аргументы запуска Antigravity IDE, например --user-data-dir.',
      antigravity_ide_args_placeholder: 'Например: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Найти',
    },
    startup: {
      title: 'Автозагрузка',
      description: 'Управление запуском приложения при старте системы.',
      auto_startup: 'Запускать вместе с системой',
      auto_startup_desc: 'Запускать при входе и сворачивать в трей',
      start_in_tray: 'Запускать в трее',
      start_in_tray_desc: 'Запускать приложение свернутым в системный трей',
      macos_hint:
        'macOS требует подписанное приложение для работы элементов входа. Если автозапуск не работает, подпишите приложение или включите его вручную в системных настройках.',
    },
    privacy: {
      title: 'Конфиденциальность',
      description: 'Управление использованием данных для улучшения приложения.',
      error_reporting: 'Отчеты об ошибках',
      error_reporting_desc:
        'Отправляйте анонимные отчеты об ошибках, чтобы помочь нам улучшить приложение. Личные данные не собираются.',
      telemetry: 'Телеметрия производительности',
      telemetry_desc:
        'Отправлять анонимные метрики времени и трассировки для диагностики медленного переключения аккаунтов.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Отправлять анонимную диагностику взаимодействия, тепловые карты и записи сеансов для улучшения приложения.',
      clarity_unavailable: 'Microsoft Clarity не настроен для этой сборки.',
      restart_note:
        'Некоторые настройки журналов и диагностики вступят в силу после перезапуска приложения.',
    },
    notifications: {
      title: 'Уведомления',
      description: 'Настройте уведомления о событиях аккаунтов.',
      quotaAlert: 'Уведомления о низкой квоте',
      quotaAlertDesc: 'Получайте уведомления, когда квота модели падает ниже установленного порога',
      quotaThreshold: 'Порог уведомления',
      quotaThresholdDesc: 'Процент, ниже которого срабатывает уведомление',
      saveFailed: 'Не удалось сохранить настройки уведомлений',
      thresholdSaveFailed: 'Не удалось сохранить порог уведомления',
      aiCreditsAlert: 'Уведомление о низком балансе AI-кредитов',
      aiCreditsAlertDesc:
        'Получайте уведомления, когда баланс AI-кредитов достигает или опускается ниже установленного значения',
      aiCreditsThreshold: 'Порог уведомления об AI-кредитах',
      aiCreditsThresholdDesc:
        'Количество кредитов, при достижении которого срабатывает уведомление',
      aiCreditsThresholdSaveFailed: 'Не удалось сохранить порог AI-кредитов',
    },
    proxy: {
      title: 'Верхнеуровневый прокси',
      description: 'Настроить прокси для исходящих запросов к Google/Gemini API.',
      enable: 'Включить прокси',
      url: 'URL прокси',
      'configure-before-enabling':
        'Сохраните корректный HTTP(S) URL прокси перед включением. Очистка URL также отключает прокси.',
      'configuration-invalid':
        'Прокси включён, но URL некорректен. Сохраните корректный адрес или отключите прокси.',
      'url-invalid': 'Введите корректный HTTP или HTTPS URL прокси.',
      timeout: 'Тайм-аут запроса (сек)',
    },
    modelMapping: {
      title: 'Маппинг моделей',
      description:
        'Сопоставьте модели Claude Code с моделями Antigravity. Оптимизируйте затраты и скорость, разумно маршрутизируя запросы.',
      claudeKeyword: 'Модель Claude (Ключевое слово)',
      targetGemini: 'Целевая модель Gemini',
      addPlaceholderKey: 'например, op-3',
      addPlaceholderValue: 'например, gemini-3-flash',
      noMappings: 'Нет пользовательских сопоставлений.',
      mapsTo: 'Мапится в',
      default: 'По умолчанию',
      restoreDefaults: 'Сбросить по умолчанию',
    },
    modelVisibility: {
      title: 'Видимость моделей',
      description:
        'Управляйте тем, какие модели отображаются в карточках аккаунтов. Скрытые модели не будут показаны в отображении квот.',
      searchPlaceholder: 'Поиск моделей...',
      showAll: 'Показать все',
      hideAll: 'Скрыть все',
      reset: 'Сбросить по умолчанию',
      save: 'Сохранить изменения',
      noModels: 'Модели не найдены',
      modelsShown: '{{visible}} из {{total}} моделей видно',
      quotaManagement: 'Управление квотами',
      hidden: 'Скрыто',
      noModelsFound: 'Модели не найдены',
      totalModels: 'Всего',
      visibleModels: 'Видно',
      hiddenModels: 'Скрыто',
      saving: 'Сохранение...',
    },
    autoSwitchModels: {
      title: 'Настройка автосвапа моделей',
      description:
        'Настройте, какие модели вызывают автосвап при исчерпании лимитов, и какие модели приоритетны при выборе следующего аккаунта.',
      searchPlaceholder: 'Поиск моделей...',
      noModels: 'Модели не найдены.',
      noModelsFound: 'Модели не найдены.',
      includeLabel: 'Включить',
      priorityLabel: 'Приоритет',
      save: 'Сохранить настройки',
      saving: 'Сохранение...',
      saved: 'Настройки автосвапа успешно сохранены.',
      saveFailed: 'Не удалось сохранить настройки автосвапа.',
    },
    providerGroupings: {
      title: 'Группировка провайдеров',
      description: 'Группировка моделей по провайдерам для лучшей организации',
      enabled: 'Включить группировку провайдеров',
      models: '{{count}} моделей',
      avgLabel: 'сред.',
      resetLabel: 'сброс',
      overall: 'Общее',
      healthy: 'Исправно',
      degraded: 'Снижено',
      limited: 'Ограничено',
      critical: 'Критично',
    },
    examples: {
      title: 'Примеры использования',
      description: 'Примеры команд для вызова локального API прокси.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Копировать',
      copied: 'Скопировано!',
      openai_protocol: 'Протокол OpenAI',
      anthropic_protocol: 'Протокол Anthropic',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Быстрый (Flash)',
      pro: 'Про (Pro)',
      flash_preview: 'Превью (Flash Preview)',
      pro_high: 'Лучший (Pro High)',
      sonnet: 'Мыслящий (Sonnet)',
      opus: 'Opus',
    },
    gateway: {
      title: 'Служба API Прокси',
      description: 'Управление локальным прокси-сервером API.',
      status_running: 'Запущено',
      status_stopped: 'Остановлено',
      action_start: 'Запустить службу',
      action_stop: 'Остановить службу',
      accounts_info: '{{count}} аккаунтов доступно',
      port: 'Порт прослушивания',
      port_hint: 'По умолчанию 8045, требуется перезапуск для применения',
      timeout: 'Тайм-аут запроса',
      timeout_hint: 'По умолчанию 120с, диапазон 30-600с',
      api_key: 'API Ключ',
      regenerate_key: 'Перегенерировать',
      regenerateConfirm: {
        title: 'Перегенерировать API ключ?',
        description:
          'Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.',
        cancel: 'Отмена',
        confirm: 'Перегенерировать',
      },
      key_warning: 'Держите ваш API ключ в секрете. Не передавайте его никому.',
      auto_start: 'Автозапуск с приложением',
      auto_start_desc: 'Запускать прокси-службу при старте приложения',
    },
    proxy_tab: 'Прокси',
    save: 'Сохранить настройки',
  },
  toast: {
    backupSuccess: {
      title: 'Успешно',
      description: 'Бэкап аккаунта создан.',
    },
    backupError: {
      title: 'Ошибка',
      description: 'Не удалось создать бэкап: {{error}}',
    },
    switchSuccess: {
      title: 'Успешно',
      description: 'Аккаунт переключен.',
    },
    switchError: {
      title: 'Ошибка',
      description: 'Не удалось переключить аккаунт: {{error}}',
    },
    deleteSuccess: {
      title: 'Успешно',
      description: 'Бэкап удален.',
    },
    deleteError: {
      title: 'Ошибка',
      description: 'Не удалось удалить бэкап: {{error}}',
    },
  },
  cloud: {
    'total-accounts': 'Всего аккаунтов',
    title: 'Аккаунты',
    description: 'Управляйте своими аккаунтами Google Gemini.',
    security: {
      compatibilityMode: {
        title: 'Ключи безопасности сохранены на этом компьютере',
        description:
          'Защищённое системное хранилище недоступно, поэтому ключи сохранены в локальном файле. Защитите компьютер и его резервные копии.',
      },
    },
    autoSwitch: 'Авто-переключение',
    providerGroupings: 'Группировка по провайдерам',
    addAccount: 'Добавить аккаунт',
    checkQuota: 'Проверить квоту',
    polling: 'Опрос запущен',
    globalQuota: 'Глобальная квота',
    layout: {
      auto: 'Авто',
      twoCol: '2 колонки',
      threeCol: '3 колонки',
      list: 'Список',
      compact: 'Компактный',
    },
    'auto-switch-client': 'Автосмена аккаунта в клиентах',
    'auto-switch-description':
      'Переключает аккаунты в Antigravity, IDE и CLI. Аккаунты для API-запросов настраиваются на странице API-прокси.',
    'quota-display': {
      title: 'Отображение квот',
      description:
        'Выберите квоты для карточек аккаунтов. Это не меняет квоты или аккаунт, используемый для запросов.',
      'five-hours-gemini': 'Квота Gemini на 5 часов',
      'five-hours-claude': 'Квота Claude на 5 часов',
      'weekly-gemini': 'Недельная квота Gemini',
      'weekly-claude': 'Недельная квота Claude',
    },
    'quota-window': {
      label: 'Период квоты',
      'five-hours': 'Квота на 5 часов',
      'five-hours-short': '5 ч',
      weekly: 'Недельная квота',
      'weekly-short': 'Неделя',
      'compact-weekly-short': 'Нед.',
      'both-short': 'Оба',
      'no-weekly-quota': 'Нет данных о недельной квоте',
      'weekly-summary-unavailable':
        'Сервис моделей не предоставил сведения о недельном использовании.',
      'weekly-bucket-unavailable': 'В полученных данных не найдено недельное использование.',
    },
    authDialog: {
      'manual-sign-in': 'Ввести код вручную',
      'waiting-for-browser': 'Завершите вход в браузере. Это окно обновится автоматически.',
      title: 'Добавить Google Аккаунт',
      description:
        'Выберите способ входа и войдите в Google через браузер. Аккаунт будет добавлен автоматически.',
      oauthClient: 'Способ входа',
      oauthClientPlaceholder: 'Выберите способ входа',
      openLogin: 'Открыть страницу входа',
      authCode: 'Код авторизации',
      placeholder: 'Вставьте код, начинающийся с 4/...',
      instruction: 'Если вход не завершился автоматически, вставьте сюда код из браузера.',
      verify: 'Проверить и добавить',
    },
    card: {
      active: 'Активен',
      use: 'Использовать',
      rateLimited: 'Лимит исчерпан',
      validationRiskControlled: 'Риск / Ограничение',
      validationOAuthReauthRequired: 'Войдите в Google снова',
      validationRequired: 'Требуется проверка',
      completeValidation: 'Пройти проверку',
      left: 'ост.',
      used: 'Исп.',
      unknown: 'Неизвестный',
      actions: 'Действия',
      useAccount: 'Использовать этот аккаунт',
      identityProfile: 'Профиль идентичности',
      refresh: 'Обновить квоту',
      delete: 'Удалить аккаунт',
      noQuota: 'Нет данных',
      rateLimitedQuota: 'Лимит исчерпан',
      liveLimitModelNotSupported: 'Модель не поддерживается',
      liveLimitModelForbidden: 'Доступ к модели запрещён',
      liveLimitQuotaExhausted: 'Квота исчерпана',
      liveLimitRateLimited: 'Ограничение частоты',
      liveLimitRemaining: 'осталось {{duration}}',
      liveLimitDetectedAgo: 'обнаружено {{duration}} назад',
      liveLimitActiveTitle: 'Сервис моделей временно недоступен.',
      liveLimitRecentTitle: 'Сервис моделей недавно сообщил об ошибке.',
      liveLimitQuotaSnapshot:
        'Последняя проверка остатка может всё ещё показывать {{percentage}}%.',
      liveLimitMessage: 'Сообщение: {{message}}',
      resetPrefix: 'Сброс',
      resetTime: 'Время сброса',
      resetUnknown: 'Неизвестно',
      detailedQuota: 'Подробная квота',
      quotaGroupUnknown: 'Группа квот',
      gemini3Ready: 'Gemini 3 готов',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Прокси',
      proxyPlaceholder: 'напр. http://127.0.0.1:7890',
      proxySaved: 'Прокси сохранён',
      'network-proxy': 'Сетевой прокси',
      'network-proxy-description':
        'Необязательно: используйте сетевой прокси для этого аккаунта. Нажмите Enter или покиньте поле адреса для сохранения.',
      'proxy-replace-placeholder': 'Введите новый адрес прокси',
      'proxy-remove': 'Удалить прокси',
      'proxy-save-failed': 'Не удалось сохранить прокси',
      noProxy: 'Без прокси',
      aiCredits: 'AI Кредиты',
      aiCreditsValue: '{{amount}} кредитов',
      creditsExpiry: 'истекает {{date}}',
      modelVisibility: 'Видимость моделей',
    },
    identity: {
      'profile-errors': {
        'account-not-found': 'Эта учётная запись больше недоступна.',
        'baseline-unavailable': 'Нет исходного профиля идентичности для восстановления.',
        'revision-not-found': 'Выбранный профиль идентичности не найден.',
        'profile-invalid': 'Этот профиль идентичности нельзя использовать. Выберите другой.',
        'profile-write-failed': 'Не удалось сохранить профиль идентичности. Повторите попытку.',
        'profile-operation-failed':
          'Не удалось выполнить действие с профилем идентичности. Повторите попытку.',
      },
      title: 'Устройство аккаунта',
      loading: 'Загрузка...',
      generateAndBind: 'Создать новые данные устройства',
      captureAndBind: 'Использовать текущее устройство',
      restoreOriginal: 'Восстановить исходные данные',
      openFolder: 'Открыть папку данных устройства',
      previewTitle: 'Новые данные устройства',
      confirm: 'Подтвердить',
      cancel: 'Отмена',
      close: 'Закрыть',
      currentStorage: 'Текущие настройки устройства',
      accountBinding: 'Сохранено для этого аккаунта',
      history: 'Сохранённые версии',
      noHistory: 'История профилей пуста',
      current: 'Активный',
      restore: 'Восстановить',
      generateSuccess: 'Профиль создан и привязан',
      captureSuccess: 'Текущий профиль считан и привязан',
      restoreOriginalSuccess: 'Базовый профиль восстановлен',
      restoreVersionSuccess: 'Исторический профиль восстановлен',
      deleteVersionSuccess: 'Исторический профиль удален',
      openFolderSuccess: 'Хранилище профилей открыто',
      baseline: 'Исходные данные устройства',

      description:
        'Сохраните данные устройства для этого аккаунта, чтобы использовать их при переключении.',
      'load-failed': 'Не удалось прочитать данные устройства',
      'retry-description': 'Попробуйте ещё раз. Сохранённые данные устройства не изменены.',
      'refresh-failed': 'Не удалось обновить. На экране остаются ранее загруженные данные.',
      updating: 'Обновляем данные устройства…',
      'device-id': 'Номер устройства',
      'mac-device-id': 'Номер устройства Mac',
      'installation-id': 'Номер установки',
      'diagnostic-id': 'Номер диагностики',
      'delete-version': 'Удалить сохранённую версию: {{label}}',
    },
    list: {
      noAccounts: 'Нет добавленных облачных аккаунтов.',
      noFilteredAccounts: 'Нет аккаунтов для выбранных уровней.',
    },
    error: {
      loadFailed: 'Не удалось загрузить аккаунты.',
      'report-issue': 'Сообщить о проблеме',
      'report-preparing': 'Подготовка сведений об ошибке…',
      'report-copied': 'Сведения об ошибке скопированы',
      'report-paste-guide':
        'Вставьте их в форму GitHub, опишите свои действия и отправьте сообщение.',
      'report-copy-failed': 'Не удалось скопировать сведения',
      'report-retry': 'Попробуйте ещё раз. Можно открыть подробности и скопировать ошибку вручную.',
      'report-open-failed': 'Не удалось открыть GitHub',
      'report-manual-open': 'Сведения скопированы. Откройте {{url}} и вставьте их в сообщение.',
      dataRepair: {
        title: 'Не удаётся открыть сохранённые аккаунты',
        description:
          'Приложение не может прочитать некоторые сохранённые аккаунты. Это может произойти после смены учётной записи компьютера или повреждения локальных файлов.',
        stepReLogin:
          'Если повторный запуск не помог, войдите снова или добавьте затронутые аккаунты заново. Сохраните существующие данные приложения до восстановления аккаунтов.',
        stepMacPrivacy:
          'На macOS проверьте запросы на разрешения. Переместите приложение в папку «Программы» и откройте его снова.',
        stepCheckGithub:
          'Проверьте README в репозитории GitHub на наличие актуальных шагов диагностики.',
        stepOpenIssue:
          'Сообщите об этой проблеме на GitHub. Нажмите, чтобы скопировать сведения об ошибке и открыть форму.',
        openRepository: 'Открыть репозиторий GitHub',
      },
    },
    toast: {
      validationLinkFailed: {
        title: 'Не удалось открыть страницу проверки Google',
        codes: {
          'account-not-found': 'Этот аккаунт больше недоступен.',
          'no-trusted-link': 'Для этого аккаунта нет доступной страницы проверки Google.',
          'validation-link-failed':
            'Не удалось открыть страницу проверки Google. Повторите попытку.',
        },
      },
      addSuccess: 'Аккаунт успешно добавлен!',
      addFailed: {
        title: 'Не удалось добавить аккаунт',
        codes: {
          'authorization-denied': 'Доступ через Google не предоставлен. Повторите попытку.',
          'login-active': 'Вход через Google уже выполняется.',
          'login-cancelled': 'Вход отменён.',
          'login-timeout': 'Время входа истекло. Начните заново.',
          'duplicate-account': 'Этот аккаунт Google уже добавлен.',
          'browser-open-failed': 'Не удалось открыть браузер. Проверьте браузер по умолчанию.',
          'login-failed': 'Не удалось добавить аккаунт. Повторите попытку.',
          'proxy-configuration-invalid':
            'Сохраните корректный адрес прокси или отключите прокси в настройках, затем повторите вход.',
        },
      },
      quotaRefreshed: 'Квота обновлена',
      refreshFailed: 'Не удалось обновить квоту',
      pollFailed: 'Не удалось опросить квоты всех аккаунтов',
      switched: {
        title: 'Аккаунт переключен!',
        description: 'Перезапуск Antigravity...',
      },
      switchFailed: 'Не удалось переключить аккаунт',
      switchFailureCodes: {
        'account-not-found': 'Этот аккаунт больше недоступен.',
        'reauth-required': 'Войдите в этот аккаунт снова перед переключением.',
        'identity-profile-required': 'Настройте профиль устройства перед переключением.',
        'process-control-failed':
          'Не удалось закрыть или перезапустить Antigravity. Повторите попытку.',
        'target-write-failed':
          'Не удалось использовать выбранный аккаунт в Antigravity. Повторите попытку.',
        'switch-failed': 'Не удалось переключить аккаунт. Повторите попытку.',
      },
      deleted: 'Аккаунт удален',
      deleteFailed: 'Не удалось удалить аккаунт',
      deleteConfirm: 'Вы уверены, что хотите удалить этот аккаунт?',
      autoSwitchOn: 'Авто-переключение включено',
      autoSwitchOff: 'Авто-переключение выключено',
      updateSettingsFailed: 'Не удалось обновить настройки',
      actionFailed: 'Не удалось выполнить действие',
      startAuthFailed: 'Не удалось запустить процесс входа',
      refreshCreditsAvailable: 'AI кредиты: {{amount}}',
      refreshCreditsUnavailable: 'AI кредиты недоступны для этого обновления.',
      batchRefreshSuccess: 'Успешно обновлено {{count}} аккаунтов.',
      batchRefreshPartial: {
        title: 'Обновление завершено с проблемами',
        description: 'Обновлено {{successful}} аккаунтов, {{failed}} с ошибкой.',
      },
      batchDeleteSuccess: 'Успешно удалено {{count}} аккаунтов.',
      batchDeletePartial: {
        title: 'Удаление завершено с проблемами',
        description: 'Удалено {{successful}} аккаунтов, {{failed}} с ошибкой.',
      },
    },
    batch: {
      actions: 'Действия с выбранными аккаунтами',
      'delete-title': 'Удалить {{count}} аккаунтов?',
      cancel: 'Отмена',
      selected: 'Выбрано {{count}}',
      delete: 'Удалить выбранные',
      refresh: 'Обновить выбранные',
      selectAll: 'Выбрать все',
      clear: 'Снять выделение',
      confirmDelete: 'Вы уверены, что хотите удалить {{count}} аккаунтов?',
    },
    tierFilter: {
      all: 'Все уровни',
      reset: 'Сбросить',
      selectedCount: '{{count}} уровня',
      unknown: 'Неизвестно',
    },
    sort: {
      recentlyUsed: 'Недавние',
      quotaOverall: 'Общая квота',
      quotaClaude: 'Квота Claude',
      quotaPro3: 'Квота Pro3',
      quotaFlash: 'Квота Flash',
    },
    exportImport: {
      'file-errors': {
        'file-too-large': 'Выбранный файл слишком большой. Выберите меньшую резервную копию.',
        'invalid-export': 'Не удалось распознать резервную копию аккаунтов. Выберите другой файл.',
        'read-failed': 'Не удалось открыть выбранный файл. Проверьте, что он всё ещё доступен.',
        'write-failed': 'Не удалось сохранить резервную копию. Проверьте место сохранения.',
        'import-failed': 'Не удалось импортировать аккаунты. Повторите попытку.',
        'tokens-missing':
          'В резервной копии нет данных для входа в этот аккаунт. Экспортируйте копию с данными для входа.',
        'account-write-failed': 'Не удалось сохранить аккаунт.',
      },
      export: 'Экспорт',
      import: 'Импорт',
      exportTitle: 'Экспорт аккаунтов',
      exportDesc:
        'Выберите, включать ли данные для входа в резервную копию. Храните такие копии в безопасном месте.',
      includeTokens: 'Включить данные для входа (восстановление аккаунтов)',
      stripTokens: 'Без данных для входа (безопаснее для обмена)',
      exportSuccess: 'Аккаунты успешно экспортированы',
      importTitle: 'Импорт аккаунтов',
      importDesc: 'Выберите ранее экспортированный JSON файл.',
      importStrategy: 'Стратегия импорта',
      strategyMerge: 'Объединить - Обновить существующие, добавить новые',
      strategyOverwrite: 'Перезаписать - Заменить все существующие данные',
      strategySkip: 'Пропустить - Добавить только новые аккаунты',
      importSuccess: 'Импортировано {{imported}}, обновлено {{updated}}, пропущено {{skipped}}',
      importErrors: 'Импорт завершён с {{count}} ошибкой(ами)',
      selectFile: 'Выбрать файл',
      importing: 'Импорт...',
      fileTooLarge: 'Размер файла превышает лимит в 5 МБ',
      invalidJson: 'Некорректный формат JSON-файла',
      readFileFailed: 'Не удалось прочитать файл',
    },
    localImport: {
      description:
        'Найдите аккаунты, в которые уже выполнен вход на этом компьютере. Проверьте результаты перед импортом.',
      emailCollision: 'Для {{email}} найдено {{count}} разных сохранённых входов.',
      sources: {
        'antigravity-keyring': 'Данные входа в системе',
        'antigravity-classic-db': 'Сохранённые аккаунты Antigravity',
        'antigravity-ide-db': 'Сохранённые аккаунты Antigravity IDE',
      },
      validationErrors: {
        'credential-unavailable':
          'Эти данные входа больше недоступны. Войдите в Antigravity снова и повторите поиск.',
        'authentication-failed':
          'Google не принял этот вход. Войдите в Antigravity снова и повторите поиск.',
      },
      discoveryErrors: {
        missing: 'Здесь не найдены сохранённые данные входа.',
        'permission-denied':
          'Нет доступа к сохранённым данным входа. Проверьте разрешения и повторите попытку.',
        locked:
          'Данные входа заблокированы или используются. Разблокируйте доступ или закройте Antigravity и повторите поиск.',
        malformed:
          'Не удалось прочитать данные входа. Войдите в Antigravity снова и повторите поиск.',
        'timed-out': 'Чтение данных входа заняло слишком много времени. Повторите поиск.',
        'read-failed': 'Не удалось прочитать данные входа. Повторите поиск.',
      },
      importErrors: {
        'credential-unavailable':
          'Эти данные входа больше недоступны. Повторите поиск перед импортом.',
        'identity-conflict':
          'Данные входа не совпадают с существующим аккаунтом. Проверьте аккаунты перед импортом.',
      },
      errors: {
        'session-not-found': 'Результаты поиска больше недоступны. Повторите поиск.',
        'session-expired': 'Результаты поиска устарели. Повторите поиск.',
        'session-consumed':
          'Эти результаты уже использованы. Повторите поиск для импорта других аккаунтов.',
      },

      title: 'Импорт с этого компьютера',

      trigger: 'Импорт с этого компьютера',
    },

    feedback: {
      'loading-title': 'Читаем ваши аккаунты',
      'loading-description': 'Сведения об аккаунтах появятся здесь, когда будут готовы.',
      'empty-description':
        'Нажмите «Добавить аккаунт», чтобы войти, или импортируйте файл аккаунтов.',
      'filtered-description':
        'Выберите другой тариф или сбросьте фильтр, чтобы увидеть больше аккаунтов.',
    },
  },
  proxy: {
    'advanced-options': 'Другие настройки сервиса',
    'advanced-description': 'Выбор аккаунтов, общие инструкции и совместимость инструментов.',
    tabs: { tools: 'Инструменты', models: 'Модели', records: 'История', examples: 'Примеры' },
    'account-strategy': {
      'save-failed':
        'Не удалось сохранить настройку. Выберите её ещё раз, чтобы повторить попытку.',
      title: 'Аккаунты для API-запросов',
      balanced: 'Чередовать доступные аккаунты',
      'account-first': 'Предпочитать тот же аккаунт',
      'balanced-description':
        'Распределяет новые диалоги между доступными аккаунтами. Текущий диалог сохраняет свой аккаунт, пока он доступен.',
      'account-first-description':
        'Для каждой модели продолжает использовать тот же аккаунт. Переключается, если квота исчерпана, аккаунт временно ограничен или не может обработать запрос. Текущие диалоги сохраняют доступный аккаунт.',
      'client-description':
        'Эта настройка не меняет аккаунт в Antigravity, IDE или CLI. Автосмена в клиентах настраивается на странице аккаунтов.',
    },
    title: 'API Прокси',
    description: 'Управление локальным прокси-сервером API.',
    save: 'Сохранить',
    copy: 'Копировать',
    copied: 'Скопировано!',
    regenerate: 'Перегенерировать',
    regenerateConfirm: {
      title: 'Перегенерировать API ключ?',
      description:
        'Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.',
      cancel: 'Отмена',
      confirm: 'Перегенерировать',
    },
    'risk-confirmation': {
      title: 'Подтвердите риски перед запуском прокси',
      description:
        'С февраля Google усилил меры контроля. Простое переключение аккаунтов с помощью этой программы не влияет на ваш аккаунт Google.\n\nОднако её использование в качестве обратного прокси или для подобных целей нарушает условия использования Google и может привести к приостановке действия аккаунта.',
      'account-advice': 'Используйте только аккаунты, потерю которых вы можете себе позволить.',
      cancel: 'Отмена',
      confirm: 'Я понимаю риски. Запустить прокси',
    },
    service: {
      title: 'Статус сервиса',
      description: 'Управление локальным сервером.',
      running: 'Работает',
      stopped: 'Остановлен',
      start: 'Запустить',
      stop: 'Остановить',
      start_failed: 'Не удалось запустить сервис',
      port_in_use_title: 'Порт уже используется',
      port_in_use_description:
        'Порт {{port}} уже используется другим процессом. Закройте этот процесс или измените порт API прокси в настройках и повторите попытку.',
    },
    config: {
      port: 'Порт',
      timeout: 'Тайм-аут',
      api_key: 'API Ключ',
      auto_start: 'Автозапуск',
      auto_start_desc: 'Запускать прокси при старте приложения',
      'allow-local-video-paths': 'Разрешить локальные пути к видео',
      'allow-local-video-paths-desc':
        'Разрешает подключённым инструментам читать видео на этом компьютере, доступные вашему пользователю. Включайте только для доверенных инструментов.',
      'global-system-prompt-title': 'Инструкции для всех запросов к ИИ',
      'global-system-prompt-description':
        'Эти инструкции автоматически добавляются перед инструкциями подключённого инструмента в каждом запросе через Manager.',
      'global-system-prompt-placeholder':
        'Введите глобальную системную инструкцию...\nНапример: отвечайте на упрощённом китайском и кратко объясняйте изменения кода.',
      'global-system-prompt-character-count': '{{count}} символов',
      'global-system-prompt-long-warning':
        'Более 2 000 символов оставляют меньше места для истории диалога. Попробуйте сократить инструкции.',
      local_access: 'Доступ из локальной сети:',
      select_ip: 'Выбрать IP',
      no_token_warning: '⚠️ API ключ не установлен. Доступ открыт всем!',
      show_key: 'Показать',
      hide_key: 'Скрыть',
      cloud_code_meta: 'Совместимость с Cloud Code',
      cloud_code_meta_desc:
        'Добавляет сведения, нужные старым клиентам Cloud Code. Включайте только при необходимости: другие клиенты могут их не принять.',
    },
    mapping: {
      title: 'Маппинг моделей',
      description: 'Выберите модель Gemini для обработки запросов к каждой модели Claude.',
      maps_to: '->',
      restore: 'Сброс',
      'only-raw-quota-models': 'Показывать только модели, найденные в ваших аккаунтах',
      'only-raw-quota-models-desc':
        'Подключённые инструменты видят только модели из последних проверок квоты аккаунтов, без дополнительных названий.',
    },
    'open-code': {
      title: 'Синхронизация OpenCode',
      description:
        'Подключите OpenCode к Manager, сохранив остальные настройки, комментарии и оформление.',
      synced: 'Синхронизировано',
      'synced-custom-url': 'Синхронизировано с пользовательским URL',
      'not-synced': 'Не синхронизировано',
      'config-path': 'Конфигурация',
      'configured-models': 'Настроенные модели',
      runtime: 'Установка OpenCode',
      installed: 'Установлено',
      'not-installed': 'Не обнаружено',
      credential: 'Ключ подключения OpenCode',
      'key-stored': 'Сохранён в защищённом хранилище системы',
      'key-missing': 'Будет создан при следующей синхронизации',
      'backup-notice':
        'В копиях сохраняются комментарии и оформление. Ключ Manager заменяется непригодным значением; при восстановлении используется текущий ключ.',
      sync: 'Настроить и синхронизировать OpenCode',
      restore: 'Восстановить резервную копию',
      clear: 'Очистить управляемую конфигурацию',
      revoke: 'Отозвать отдельный ключ',
      'model-dialog-title': 'Выберите модели OpenCode',
      'model-dialog-description':
        'Выбранные модели будут добавлены или обновлены. Существующие невыбранные модели не удаляются.',
      'custom-base-url': 'Адрес Manager',
      'reset-base-url': 'Сбросить',
      'invalid-base-url': 'Введите корректный URL HTTP или HTTPS.',
      'sync-accounts': 'Использовать аккаунты в плагине входа OpenCode',
      'sync-accounts-description':
        'Если включить эту функцию, OpenCode сохранит в файле на этом компьютере данные, которые позволяют оставаться в этих аккаунтах. По умолчанию функция выключена. Включайте её только на компьютере, которому доверяете.',
      'select-models': 'Модели для добавления или обновления',
      'selected-count': 'Выбрано {{selected}} из {{total}}',
      'select-all': 'Выбрать все',
      'deselect-all': 'Снять выделение',
      'confirm-sync': 'Подтвердить синхронизацию',
      'auth-plugin-warning-title': 'Найден другой плагин входа',
      'auth-plugin-warning-description':
        'opencode-antigravity-auth может использовать другое подключение. Убедитесь, что в OpenCode выбран Manager.',
      'view-config': 'Просмотреть конфигурацию',
      'restore-confirm-title': 'Восстановить резервную копию OpenCode?',
      'restore-confirm-description':
        'Весь файл будет заменён первоначальной копией, включая последующие изменения. После восстановления копия удаляется.',
      'confirm-restore': 'Подтвердить восстановление',
      'clear-confirm-title': 'Удалить подключение к Manager?',
      'clear-confirm-description':
        'Подключение и его ключ будут удалены. Другие сервисы, настройки и резервная копия сохранятся.',
      'confirm-clear': 'Подтвердить очистку',
      'config-viewer-title': 'Конфигурация OpenCode',
      'config-viewer-description': 'Предпросмотр конфигурации только для чтения',
      'config-redacted-notice': 'Личные данные скрыты в этом просмотре.',
      'config-copied': 'Настройки скопированы, личные данные скрыты',
      'config-copy-failed': 'Не удалось скопировать конфигурацию',
      'config-load-failed': 'Не удалось загрузить конфигурацию',
      'copy-config': 'Скопировать настройки (личные данные скрыты)',
      'success-title': 'Конфигурация OpenCode обновлена',
      'error-title': 'Не удалось обновить OpenCode',
      'unknown-error': 'Неизвестная ошибка конфигурации OpenCode',

      'choose-model-hint': 'Выберите хотя бы одну модель, чтобы продолжить.',
      'config-retry-description': 'Попробуйте ещё раз. Сохранённые настройки не изменены.',
    },
    examples: {
      title: 'Примеры',
      description: 'Примеры использования локального прокси.',
    },
    persistence: {
      title: 'Request history and reasoning',
      description: 'Inspect bounded local records without slowing model traffic.',
      'audit-title': 'История запросов',
      'audit-description':
        'Сохраняет запросы, ответы и попытки обращения к сервису моделей на этом компьютере, скрывая конфиденциальные данные.',
      rows: '{{count}} requests',
      queue: '{{count}} записей ожидают сохранения',
      dropped:
        'Не удалось сохранить {{count}} записей ({{reason}}). Обработка запросов к модели продолжилась.',
      'disk-gib': 'Disk limit (GiB)',
      'body-hours': 'Хранение полного содержимого (часы)',
      'summary-days': 'Summary retention (days)',
      'max-rows': 'Maximum rows',
      'no-audit': 'No traffic records yet.',
      'audit-metadata': 'Сведения о запросах и обращениях к сервису моделей',
      'audit-body-missing': 'Полное содержимое запроса или ответа больше не хранится.',
      'audit-body-expired':
        'Срок хранения полного содержимого истёк, но сведения о запросе доступны.',
      partial: 'Partial',
      'logical-size': 'Размер содержимого',
      'parse-error-offset': 'Позиция, которую не удалось прочитать',
      loading: 'Loading…',
      'copy-progress': 'Preparing full copy: {{value}}%',
      'previous-page': 'Previous page',
      'next-page': 'Next page',
      'copy-full': 'Copy complete body',
      'confirm-copy-full': 'Confirm copying {{size}}',
      'clear-audit': 'Очистить историю запросов',
      'repair-audit': 'Восстановить историю запросов',
      'thought-title': 'Reasoning history',
      'thought-description': 'Save reasoning so later turns can continue the conversation.',
      sessions: '{{count}} sessions',
      'hard-limit': 'Каждый диалог сохраняет не более 200 ходов и 64 MiB содержимого.',
      'retention-days': 'Retention (days)',
      'max-sessions': 'Maximum sessions',
      oversized: 'Содержимое превысило 64 MiB и сохранено не полностью.',
      'no-thought-body': 'No stored thought body.',
      signature: 'Signature',
      'copy-signature': 'Copy signature',
      'no-thought': 'No reasoning history yet.',
      'clear-thought': 'Clear reasoning history',
      'repair-thought': 'Repair reasoning history',
      'confirm-clear': 'Confirm clear',
      'confirm-repair': 'Confirm repair',
    },
  },
  traffic: {
    'detail-load-failed': 'Не удалось загрузить запрос. Повторите попытку.',
    'detail-not-found': 'Запись недоступна. Возможно, она была удалена.',
    fields: {
      category: 'Категория',
      method: 'Метод запроса',
      'requested-model': 'Запрошенная модель',
      'mapped-model': 'Выбранный маршрут модели',
      error: 'Описание ошибки',
      affected: 'Затронутые записи',
      'request-id': 'Номер запроса',
      'client-address': 'Адрес клиента',
      username: 'Пользователь',
      'reasoning-tokens': 'Токены рассуждения',
      'cached-tokens': 'Кэшированные токены',
      query: 'Дополнительные параметры',
    },
    outcomes: {
      in_progress: 'Выполняется',
      completed: 'Завершено',
      client_cancelled: 'Отменено',
      client_disconnected: 'Соединение закрыто',
      timeout: 'Время ожидания истекло',
      upstream_error: 'Ошибка сервиса модели',
      auth_failed: 'Не удалось войти',
      internal_error: 'Ошибка приложения',
      partial: 'Частичный результат',
    },
    'search-metadata': 'Поиск по модели, номеру запроса или адресу',
    'copy-upstream-curl': 'Скопировать запрос к сервису моделей в cURL (личные данные скрыты)',
    'upstream-attempts': 'Запросы к сервису моделей',
    'no-attempts': 'Запросы к сервису моделей не отправлялись.',
    upstream: 'Сервис моделей',
    endpoint: 'Адрес сервиса',
    protocol: 'Формат API',
    'repair-databases': 'Восстановить сохранённые записи',
    'concise-help':
      'Показывает основные сведения о запросе. Развёрнутые разделы отображаются полностью.',
    'full-help':
      'Показывает все загруженные сведения. Если содержимое нельзя упорядочить или оно неполное, оба вида могут выглядеть одинаково.',
    'load-next-window': 'Следующий фрагмент',
    offset: 'Позиция в содержимом: {{offset}}',
    'parse-error': 'Не удалось прочитать содержимое в позиции {{offset}}.',
    'thought-oversized':
      'Рассуждения превысили 64 MiB и сохранены не полностью. Номер для проверки: {{hash}}',

    'loading-description': 'Записи запросов появятся здесь, когда будут готовы.',
    'empty-description':
      'Здесь появляются запросы, отправленные через прокси. Можно также изменить фильтры.',
    'empty-category-description':
      'Здесь появляются записи этой категории. Выберите другую категорию или измените фильтры.',
    'load-failed': 'Не удалось прочитать записи запросов',
    'load-failed-description': 'Попробуйте ещё раз. Это не означает, что записи удалены.',
    'refresh-failed': 'Не удалось обновить записи. Ранее загруженные данные остаются на экране.',
  },
};
export default ru;
