const tr = {
  'agent-tools': {
    title: 'Kodlama araçlarınızı bağlayın',
    description: 'Modellerinizi Antigravity Manager üzerinden kullanmak için bir araç seçin.',
    loading: 'Ayarlar okunuyor…',
    installed: 'Yüklü',
    'not-installed': 'Kurulum bulunamadı',
    'read-error': 'Mevcut ayarlar okunamadı. Değişiklik yapmadan önce yeniden deneyin.',
    retry: 'Yeniden dene',
    configured: 'Yapılandırma kaydedildi',
    'custom-address': 'Başka bir adres kullanılıyor',
    'not-configured': 'Yapılandırılmadı',
    'not-verified': 'İstekler doğrulanmadı',
    address: 'Manager adresi',
    model: 'Model',
    'not-set': 'Ayarlanmadı',
    'choose-model': 'Kurulum sırasında seçin',
    update: 'Yapılandırmayı güncelle',
    configure: 'Yapılandır',
    view: 'Yapılandırmayı görüntüle',
    restore: 'Yedeği geri yükle',
    remove: 'Bağlantıyı kaldır',
    'install-notice': 'Aracı yüklemeden önce ayarları kaydedebilirsiniz. Sonra aracı yeniden açın.',
    'action-error': 'Ayarlar güncellenemedi',
    saved: 'Ayarlar güncellendi',
    reopen: 'Ayarları yüklemek için {{name}} aracını yeniden açın.',
    'configure-title': '{{name}} aracını bağla',
    'configure-description':
      'İstekler Manager üzerinden gönderilecek. İlk değişiklikten önce mevcut ayarlar yedeklenir.',
    'restore-title': '{{name}} ayarları geri yüklensin mi?',
    'restore-description':
      'Tüm dosya ilk yedekle değiştirilir; sonraki düzenlemeler de kaybolur. Dosyayı Manager oluşturduysa dosya kaldırılır. Yedek bir kez kullanılır.',
    'remove-title': 'Manager bağlantısı kaldırılsın mı?',
    'remove-description':
      'Diğer ayarları ve yedeği koruyarak önceki bağlantı ayarlarını geri getirir.',
    'preview-title': '{{name}} ayarları',
    'preview-description':
      'Yalnızca Manager bağlantısı için gereken ayarlar gösterilir. Bağlantı anahtarları gizlidir.',
    confirm: 'Onayla',
    advanced: 'Adres ve yapılandırma dosyası',
    'reset-address': 'Geçerli Manager adresini kullan',
    'backend-files':
      'Bu ayarlar, Manager hizmetinin çalıştığı bilgisayarda hizmeti çalıştıran kullanıcı için kaydedilir.',
    'backup-notice': 'İlk yedek güncellemelerde korunur. Kaydettikten sonra aracı yeniden açın.',
    'toml-notice':
      'Codex ayar dosyasının biçimi ve yorumları değişebilir. Geri yüklemek için tam yedek alınır. Mevcut giriş ve izin ayarları korunur.',
    'codex-review':
      'Görev ve otomatik inceleme istekleri yapılandırılır. Etkin inceleme yolları ve onay ayarları korunur.',
    'model-count': '{{count}} model',
    'plugin-notice':
      'Doğrudan giriş eklentisi yüklü. OpenCode içinde Manager seçili olduğundan emin olun.',
    'revoke-key': 'OpenCode bağlantı anahtarını devre dışı bırak',
    errors: {
      unavailable: 'Ayarlar kullanılamıyor. Yeniden deneyin.',
      'invalid-config': 'Dosya geçersiz veya çok büyük. Önce dosyayı düzeltin.',
      'read-failed': 'Dosya okunamadı. Erişim izinlerini kontrol edin.',
      'write-failed': 'Kaydedilemedi. Kurtarma yedeği korunuyor.',
      'backup-failed': 'Yedek oluşturulamadı. Araç ayarları değiştirilmedi.',
      'backup-missing': 'Kurtarma yedeği yok.',
      'configuration-changed': 'İşlem sırasında ayarlar değişti. Tekrar okuyup deneyin.',
      'key-missing': 'Önce proxy sayfasında bağlantı anahtarı oluşturun.',
      'review-route-disabled': 'Codex inceleme yolu kapalı. Model yönlendirmesinde etkinleştirin.',
    },

    'address-help': 'Hizmet başka bir bilgisayarda çalışmıyorsa mevcut Manager adresini kullanın.',
    'invalid-address':
      'http:// veya https:// ile başlayan, oturum bilgisi ve ek parametre içermeyen bir Manager adresi kullanın.',
    'model-required': 'Kaydetmeden önce bir model seçin.',
  },
  appName: 'Antigravity Manager',
  'process-runtime': {
    'update-in-progress': 'Antigravity güncelleniyor. Güncellemeyi tamamlayıp tekrar deneyin.',
    'close-failed':
      'Antigravity kapatılamadı. Sohbetlerinizi ve dosyalarınızı kaydedin, uygulamayı elle kapatıp tekrar deneyin.',
    'exit-unconfirmed':
      'Antigravity henüz kapanmadı. Sohbetlerinizi ve dosyalarınızı kaydedin, uygulamayı elle kapatıp tekrar deneyin.',
    working: 'İşleniyor...',
    busy: 'Antigravity meşgul. İşlemin tamamlanmasını bekleyin.',
    'missing-executable':
      'Antigravity bulunamadı veya açılamadı. Ayarlardan uygulama konumunu kontrol edin.',
    'target-conflict':
      'Çalışan Antigravity, ayarlarda seçilen kurulumla aynı değil. Hesap değiştirmeden önce uygulamayı kapatın veya doğru kurulumu seçin.',
    'directory-conflict':
      'Antigravity, ayarlarda seçilenden farklı bir veri klasörü kullanıyor. Hesap değiştirmeden önce uygulamayı kapatın veya klasör ayarını kontrol edin.',
    'probe-failed':
      'Antigravity durumu zamanında kontrol edilemedi. Uygulamanın açık olup olmadığını kontrol edip yeniden deneyin.',
    'launch-failed': 'Antigravity açılamadı. Uygulama konumunu ve erişim izinlerini kontrol edin.',
    'startup-unconfirmed':
      'Antigravity uygulamasının açıldığı henüz doğrulanamadı. İki kez açılmaması için yeniden başlatılmadı. Tekrar denemeden önce uygulamayı kontrol edin.',
    'switched-hot-unconfirmed':
      'Yeni hesap kaydedildi ancak Antigravity IDE içinde değişiklik doğrulanamadı. Yeniden denemeden önce IDE içindeki hesabı kontrol edin.',
    'switched-startup-unconfirmed':
      'Yeni hesap kaydedildi ancak Antigravity uygulamasının açıldığı doğrulanamadı. Yeniden başlatılmadı. Tekrar denemeden önce uygulamayı kontrol edin.',
  },
  common: {
    close: 'Kapat',
    cancel: 'İptal',
    'core-unavailable-title': "Antigravity Manager'a bağlanılamıyor",
    'core-unavailable-body':
      "Hesaplar ve proxy şu anda kullanılamıyor. Antigravity Manager'ı kapatıp yeniden açın. Sorun sürerse en son sürümü yükleyin.",
    'account-data-unavailable-title': 'Kayıtlı hesaplar açılamıyor',
    'account-data-unavailable-body':
      "Kayıtlı hesaplar şu anda okunamıyor. Bu bilgisayarda her zamanki kullanıcı hesabınızla oturum açtığınızdan emin olun, ardından Antigravity Manager'ı yeniden açın. Hesap verileriniz değiştirilmedi.",
    'already-running-title': 'Antigravity Manager zaten açık',
    'already-running-body':
      'Diğer Antigravity Manager penceresini kapatıp tekrar deneyin. Bulamıyorsanız bilgisayarınızı yeniden başlatın.',
    loading: 'Yükleniyor...',
    error: 'Hata',
    unknown: 'Bilinmeyen',
    notAvailable: 'Yok',
    openMenu: 'Menüyü aç',

    'dismiss-notification': 'Bildirimi kapat',
    'reading-settings': 'Ayarlarınız okunuyor…',
  },
  status: {
    checking: 'Durum kontrol ediliyor...',
    running: 'Antigravity arka planda çalışıyor',
    stopped: 'Antigravity hizmeti durduruldu',
    services: 'Hizmetler',
    dashboard_title: 'Hizmet durumu',
    open_dashboard: 'Hizmet durumunu aç',
    checking_short: 'Kontrol ediliyor...',
    running_short: 'Çalışıyor',
    stopped_short: 'Durduruldu',
    all_running: 'Tüm hizmetler çalışıyor',
    all_stopped: 'Tüm hizmetler durduruldu',
    partial_running: '{{running}}/{{total}} hizmet çalışıyor',
  },
  action: {
    stop: 'Durdur',
    start: 'Başlat',
    switch: 'Değiştir',
    deleteBackup: 'Yedeği Sil',
    backupCurrent: 'Mevcut Hesabı Yedekle',
    retry: 'Yeniden Dene',
    details: 'Ayrıntılar',
    openLogs: 'Log Klasörünü Aç',
  },
  update: {
    title: 'Güncellemeler',
    checking: 'Kontrol ediliyor...',
    checkNow: 'Güncellemeleri Kontrol Et',
    checkFailed: 'Güncellemeler kontrol edilemedi',
    upToDate: 'En güncel sürümü kullanıyorsunuz.',
    unsupported: 'Bu platformda otomatik güncelleme kontrolü kullanılamaz.',
    available: {
      title: 'Güncelleme var',
      description: '{{version}} sürümü GitHub üzerinde mevcut.',
      download: 'İndir',
      downloading: 'İndiriliyor...',
      dismiss: 'Kapat',
      macosUnsignedNote:
        'Bu macOS derlemesi resmi olarak imzalanmamıştır. macOS uygulamayı engellerse GitHub README veya ilgili issue kayıtlarındaki elle imzalama adımlarını izleyin.',
    },
    downloaded: {
      title: 'Güncelleme hazır',
      description: '{{version}} sürümü indirildi.',
      restart: 'Yeniden başlat',
    },
  },
  error: {
    generic: 'Beklenmeyen bir hata oluştu.',
    detailsTitle: 'Hata ayrıntıları',
    detailsDescription:
      'Bu ayrıntılar sorunu çözmeye yardımcı olabilir ve kişisel dosya konumlarını içerebilir. Paylaşmadan önce kontrol edin.',
    keychainUnavailable: 'Kayıtlı oturum açma bilgileri şu anda okunamıyor.',
    keychainHint: {
      translocation: 'Uygulamayı Uygulamalar klasörüne taşıyın, ardından yeniden açın.',
      keychainDenied:
        'macOS, kayıtlı oturum açma bilgilerine erişimi engelledi. Uygulamanın kurulum yönergelerini kontrol edip tekrar deneyin.',
      signNotarize: 'Mümkünse macOS tarafından doğrulanmış bir sürüm yükleyin.',
    },
    dataMigrationFailed: 'Önceki bir sürümde kaydedilen hesaplar okunamıyor.',
    masterKeyUnavailable:
      'Kayıtlı hesaplar bulundu ancak şu anda açılamıyor. Hesap verileriniz değiştirilmedi.',
    dataMigrationHint: {
      relogin: 'Lütfen yeniden giriş yapın veya hesaplarınızı tekrar ekleyin.',
      clearData: 'Sorun devam ederse yerel hesap verilerini temizleyip tekrar giriş yapın.',
    },
    antigravityStorageJsonNotFound:
      'Antigravity ilk kurulumu tamamlanmamış. Seçilen uygulamayı açıp bir kez giriş yapın, ardından hesap değiştirmeyi yeniden deneyin.',
    antigravityProjectIdMissing:
      'Bu hesap henüz Antigravity için hazır değil. Antigravity içinde bu hesapla bir kez giriş yapıp yeniden deneyin.',
    antigravityDatabasePermissionDenied:
      'Antigravity giriş bilgileri kaydedilemedi. Veri klasörünün yazılabilir olduğunu kontrol edin veya Antigravity uygulamasını açıp Manager uygulamasını yeniden başlatın.',
    cloudAccountLoginExpired:
      'Bu bulut hesabının giriş bilgileri süresi dolmuş. Lütfen tekrar giriş yapın.',
  },
  nav: {
    navigation: 'Gezinme',
    'collapse-sidebar': 'Kenar çubuğunu daralt',
    'expand-sidebar': 'Kenar çubuğunu genişlet',
    accounts: 'Hesaplar',
    proxy: 'API Proxy',
    settings: 'Ayarlar',
  },
  editionSelection: {
    title: 'Antigravity Sürümünüzü Seçin',
    description:
      "Kullandığınız Antigravity sürümünü seçin. Bu, Manager'ın doğru uygulamaya bağlanmasını sağlar.",
    edition1x: {
      name: 'Antigravity 1.x',
      description: 'Orijinal Antigravity uygulaması. Eski sürümü kullanıyorsanız bunu seçin.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description: 'Yeni Antigravity IDE (2.0). En son IDE sürümünü kullanıyorsanız bunu seçin.',
    },
    confirm: 'Devam Et',
  },
  account: {
    current: 'Mevcut',
    lastUsed: 'Son kullanım: {{time}}',
    switchToAntigravity: "Antigravity'ye Geç",
    switchToIde: "Antigravity IDE'ye Geç",
  },
  home: {
    title: 'Hesaplar',
    description: 'Antigravity Google Gemini hesaplarınızı yönetin.',
    noBackups: {
      title: 'Yedek bulunamadı',
      description: 'Başlamak için mevcut Antigravity hesabınızın bir yedeğini oluşturun.',
      action: 'Mevcut Hesabı Yedekle',
    },
  },
  settings: {
    'service-unavailable':
      "Ayarlar şu anda açılamıyor veya kaydedilemiyor. Tekrar deneyin. Sorun sürerse Antigravity Manager'ı kapatıp yeniden açın.",
    'service-retry': 'Tekrar dene',
    'service-restart-required':
      "Ayarlar kaydedildi. Değişiklikleri uygulamak için proxy'yi kapatıp yeniden açın.",
    'service-save': 'Kaydet',
    'service-secret-configured': 'Proxy adresi ayarlı. Değiştirmek için yeni bir adres girin.',
    'weekly-warmup': {
      error: 'Isınma ayarları yüklenemedi veya kaydedilemedi.',
      retry: 'Yeniden dene',
      'cost-notice':
        'Isınma model kotası ve AI kredileri kullanabilir. HTTP isteğinin kabul edilmesi haftalık sayacın yeniden başladığını garanti etmez.',
      title: 'Haftalık kota ısıtma',
      description:
        'Seçili haftalık kota sıfırlandıktan sonra her kota bölümü için bir küçük istek gönderir ve başarılı döngüyü kaydeder.',
      enabled: 'Haftalık kota ısıtmayı etkinleştir',
      groups: 'Isıtılacak kota grupları',
      group: { claude: 'Claude kota grupları', gemini: 'Gemini kota grupları' },
    },
    title: 'Ayarlar',
    description: 'Uygulama tercihlerini yönetin.',
    general: 'Genel',
    connection: 'Bağlantı',
    models: 'Modeller',
    appearance: {
      title: 'Görünüm',
      description: "Antigravity Manager'ın cihazınızda nasıl görüneceğini özelleştirin.",
    },
    darkMode: 'Karanlık Mod',
    darkModeDescription: 'Gece daha iyi bir görünüm için karanlık modu etkinleştirin.',
    language: {
      title: 'Dil',
      description: 'Tercih ettiğiniz dili seçin.',
      english: 'İngilizce (English)',
      chinese: 'Çince (Basitleştirilmiş)',
      russian: 'Rusça',
      vietnamese: 'Vietnamca',
      turkish: 'Türkçe',
      french: 'Fransızca',
    },
    about: {
      title: 'Hakkında',
      description: 'Uygulama bilgileri.',
    },
    cache: {
      title: 'Antigravity Önbelleği',
      description:
        'Oturum açma veya sürüm doğrulama sorunlarını gidermek için bilinen Antigravity ve Antigravity IDE önbellek klasörlerini temizleyin.',
      clear: 'Antigravity Önbelleğini Temizle',
      dialogTitle: 'Antigravity önbelleği temizlensin mi?',
      dialogDescription: 'Aşağıdaki mevcut önbellek klasörleri silinecek.',
      pathsLabel: 'Önbellek klasörleri',
      noPaths: 'Bilinen bir Antigravity önbellek klasörü bulunamadı.',
      warning: 'Kilitli dosyaları önlemek için temizlemeden önce Antigravity uygulamasını kapatın.',
      cancel: 'İptal',
      confirm: 'Önbelleği Temizle',
      clearing: 'Temizleniyor...',
      clearedTitle: 'Önbellek temizlendi',
      clearedDescription: 'Antigravity önbellek klasörlerinden {{size}} MB silindi.',
      failedTitle: 'Önbellek temizlenemedi',
      notFoundTitle: 'Antigravity önbelleği bulunamadı',

      'paths-failed': 'Önbellek konumları bulunamadı',
      'paths-retry-description': 'Önbelleği temizlemeden önce tekrar deneyin.',
      'partial-title': 'Önbelleğin bir kısmı temizlenemedi',
      'partial-description':
        '{{size}} MB boşaltıldı. {{count}} konum temizlenemedi. Antigravity’yi kapatıp tekrar deneyin.',
    },
    version: 'Sürüm',
    platform: 'Platform',
    license: 'Lisans',
    openLogDir: 'Aç',
    toast: {
      saved: {
        title: 'Ayarlar kaydedildi',
        description: 'Yapılandırmanız güncellendi.',
      },
      saveFailed: {
        title: 'Ayarlar kaydedilirken hata oluştu',
      },
    },
    account: {
      'client-setup': 'İstemci konumu ve başlatma ayarları',
      'client-setup-description':
        'Manager istemcinizi bulamıyorsa veya özel başlatma seçenekleri gerekiyorsa değiştirin.',
      'choose-file': 'Dosya seç',
      'clear-field': 'Bu alanı temizle',
      title: 'Hesap Ayarları',
      description: 'Otomatik hesap yenileme ve eşitleme ayarlarını yapılandırın.',
      auto_refresh: 'Kotayı Otomatik Yenile',
      auto_refresh_desc: 'Tüm hesaplar için kota bilgilerini periyodik olarak yenile',
      auto_sync: 'Mevcut Hesabı Otomatik Eşitle',
      auto_sync_desc: 'Aktif hesap bilgilerini periyodik olarak eşitle',
      antigravity_executable: 'Antigravity çalıştırılabilir dosyası',
      antigravity_executable_desc:
        'Portable mode verilerini bulmak ve Antigravity uygulamasını başlatmak için isteğe bağlı yol.',
      antigravity_executable_placeholder: 'Örnek: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_cli_executable: 'Antigravity CLI çalıştırılabilir dosyası',
      antigravity_cli_executable_desc:
        'agy CLI yolu. Uygunluk yaması yalnızca bu dosyaya uygulanır.',
      antigravity_cli_executable_placeholder: 'Örnek: C:\\Program Files\\Antigravity\\agy.exe',
      detect_antigravity_cli: 'Algıla',
      agy_cli_detected: 'Antigravity CLI algılandı',
      agy_cli_detect_failed: 'Antigravity CLI bulunamadı',
      agy_patch_desc:
        'CLI dosyasını yedekler, tek bir ARM64 veya x86_64 kalıbını doğrular, yamayı uygular ve macOS’ta Mach-O dosyasını yeniden imzalar.',
      agy_patch_action: 'Uygunluk yamasını uygula',
      agy_patch_success: 'Antigravity CLI yamalandı',
      agy_patch_already_applied: 'Yama zaten uygulanmış',
      agy_patch_failed: 'Antigravity CLI yamalanamadı',
      agy_patch_result: 'Biçim: {{format}}; mimariler: {{architectures}}; yedek: {{backupPath}}',
      agy_patch_no_backup: 'gerekli değil',
      antigravity_ide_executable: 'Antigravity IDE çalıştırılabilir dosyası',
      antigravity_ide_executable_desc:
        'İsteğe bağlı Antigravity IDE yolu. Ayarlandıktan sonra Classic hesap geçişlerinde bu yoldaki süreçler sonlandırılmaya karşı korunur.',
      antigravity_ide_executable_placeholder:
        'Örnek: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Antigravity başlatma argümanları',
      antigravity_args_desc:
        'Antigravity başlatılırken iletilecek isteğe bağlı argümanlar, örneğin --user-data-dir.',
      antigravity_args_placeholder: 'Örnek: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Antigravity IDE başlatma argümanları',
      antigravity_ide_args_desc:
        'Antigravity IDE başlatılırken iletilecek isteğe bağlı argümanlar, örneğin --user-data-dir.',
      antigravity_ide_args_placeholder: 'Örnek: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Algıla',
    },
    startup: {
      title: 'Başlangıç',
      description: 'Sistem başlangıcında uygulamanın nasıl davranacağını kontrol edin.',
      auto_startup: 'Sistemle birlikte başlat',
      auto_startup_desc: 'Oturum açıldığında başlat ve sistem tepsisinde tut',
      start_in_tray: 'Sistem tepsisinde başlat',
      start_in_tray_desc: 'Uygulamayı sistem tepsisinde simge durumuna küçültülmüş olarak başlat',
      macos_hint:
        'macOS, Oturum Açma Öğelerinin çalışması için imzalanmış bir uygulama gerektirir. Otomatik başlatma başarısız olursa, lütfen uygulamayı imzalayın veya Sistem Ayarlarından manuel olarak etkinleştirin.',
    },
    privacy: {
      title: 'Gizlilik',
      description: 'Verilerinizin uygulamayı geliştirmek için nasıl kullanılacağını kontrol edin.',
      error_reporting: 'Hata Raporlama',
      error_reporting_desc:
        'Uygulamayı geliştirmemize yardımcı olmak için anonim hata raporları gönderin. Hiçbir kişisel veri toplanmaz.',
      telemetry: 'Performans Telemetrisi',
      telemetry_desc:
        'Yavaş hesap geçişlerini teşhis etmek için anonim zamanlama metrikleri ve izler paylaşın.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Uygulamayı iyileştirmek için anonim etkileşim tanıları, ısı haritaları ve oturum tekrarları paylaşın.',
      clarity_unavailable: 'Microsoft Clarity bu derleme için yapılandırılmamış.',
      restart_note:
        'Bazı günlük ve sorun giderme ayarları uygulama yeniden başlatıldığında etkinleşir.',
    },
    notifications: {
      title: 'Bildirimler',
      description: 'Hesap olayları için masaüstü uyarılarını yapılandırın.',
      quotaAlert: 'Düşük Kota Uyarıları',
      quotaAlertDesc: 'Bir model kotası belirlenen eşiğin altına düştüğünde bildirim alın',
      quotaThreshold: 'Uyarı Eşiği',
      quotaThresholdDesc: 'Uyarının tetikleneceği yüzde değeri',
      saveFailed: 'Bildirim ayarları kaydedilemedi',
      thresholdSaveFailed: 'Eşik ayarı kaydedilemedi',
      aiCreditsAlert: 'Düşük AI Kredisi Uyarısı',
      aiCreditsAlertDesc:
        'AI kredi bakiyesi belirlenen miktara ulaştığında veya altına düştüğünde bildirim alın',
      aiCreditsThreshold: 'AI Kredisi Uyarı Eşiği',
      aiCreditsThresholdDesc: 'Uyarının tetikleneceği kredi miktarı',
      aiCreditsThresholdSaveFailed: 'AI kredisi eşiği kaydedilemedi',
    },
    proxy: {
      title: 'Üst Akış (Upstream) Proxy',
      description: "Google/Gemini API'lerine giden istekler için bir proxy yapılandırın.",
      enable: "Üst Akış Proxy'sini Etkinleştir",
      url: "Proxy URL'si",
      timeout: 'İstek Zaman Aşımı (Saniye)',
    },
    modelMapping: {
      title: 'Model Eşleme',
      description:
        'Claude Code modellerini Antigravity modelleriyle eşleyin. İstekleri akıllıca yönlendirerek maliyeti ve hızı optimize edin.',
      claudeKeyword: 'Claude Modeli (Anahtar Kelime)',
      targetGemini: 'Hedef Gemini Modeli',
      addPlaceholderKey: 'örn. op-3',
      addPlaceholderValue: 'örn. gemini-3-flash',
      noMappings: 'Özel eşleme tanımlanmadı.',
      mapsTo: 'Şu modele eşlenir:',
      default: 'Varsayılan',
      restoreDefaults: 'Varsayılanlara Sıfırla',
    },
    modelVisibility: {
      title: 'Model Görünürlüğü',
      description:
        'Hesap kartlarında hangi modellerin görüneceğini kontrol edin. Gizli modeller kota ekranında görünmez.',
      searchPlaceholder: 'Modelleri ara...',
      showAll: 'Tümünü Göster',
      hideAll: 'Tümünü Gizle',
      reset: 'Varsayılanlara Sıfırla',
      save: 'Değişiklikleri Kaydet',
      noModels: 'Model bulunamadı',
      modelsShown: '{{total}} modelden {{visible}} tanesi görünüyor',
      quotaManagement: 'Kota Yönetimi',
      hidden: 'Gizli',
      noModelsFound: 'Model bulunamadı',
      totalModels: 'Toplam',
      visibleModels: 'Görünen',
      hiddenModels: 'Gizli',
      saving: 'Kaydediliyor...',
    },
    autoSwitchModels: {
      title: 'Auto-Switch Models Config',
      description:
        'Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.',
      searchPlaceholder: 'Search models...',
      noModels: 'No models found.',
      noModelsFound: 'No models found.',
      includeLabel: 'Include',
      priorityLabel: 'Priority',
      save: 'Save Config',
      saving: 'Saving...',
      saved: 'Auto-switch model configuration saved successfully.',
      saveFailed: 'Failed to save auto-switch model configuration.',
    },
    providerGroupings: {
      title: 'Sağlayıcı Grupları',
      description: 'Daha iyi organizasyon için modelleri sağlayıcıya göre gruplayın',
      enabled: 'Sağlayıcı Gruplamasını Etkinleştir',
      models: '{{count}} model',
      avgLabel: 'ort',
      resetLabel: 'sıfırla',
      overall: 'Genel',
      healthy: 'Sağlıklı',
      degraded: 'Düşük Performans',
      limited: 'Sınırlı',
      critical: 'Kritik',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: "Yerel API proxy'sini çağırmak için örnek komutlar.",
      curl: 'cURL',
      python: 'Python',
      copy: 'Kopyala',
      copied: 'Kopyalandı!',
      openai_protocol: 'OpenAI Protokolü',
      anthropic_protocol: 'Anthropic Protokolü',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Hızlı',
      pro: 'Pro',
      flash_preview: 'Önizleme',
      pro_high: 'En İyi',
      sonnet: 'Düşünme (Thinking)',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Hizmeti',
      description: 'Yerel API proxy sunucusunu kontrol edin.',
      status_running: 'Çalışıyor',
      status_stopped: 'Durduruldu',
      action_start: 'Hizmeti Başlat',
      action_stop: 'Hizmeti Durdur',
      accounts_info: '{{count}} hesap kullanılabilir',
      port: 'Dinleme Portu',
      port_hint: 'Varsayılan 8045, değişikliklerin uygulanması için yeniden başlatma gerekir',
      timeout: 'İstek Zaman Aşımı',
      timeout_hint: 'Varsayılan 120s, aralık 30-600s',
      api_key: 'API Anahtarı',
      regenerate_key: 'Yeniden Oluştur',
      regenerateConfirm: {
        title: 'API Anahtarı Yeniden Oluşturulsun mu?',
        description:
          'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan tüm uygulamalar çalışmayı durduracaktır.',
        cancel: 'İptal',
        confirm: 'Yeniden Oluştur',
      },
      key_warning: 'API anahtarınızı güvende tutun. Kimseyle paylaşmayın.',
      auto_start: 'Uygulama ile Otomatik Başlat',
      auto_start_desc: 'Uygulama başlatıldığında proxy hizmetini de başlat',
    },
    proxy_tab: 'Proxy',
    save: 'Ayarları Kaydet',
  },
  toast: {
    backupSuccess: {
      title: 'Başarılı',
      description: 'Hesap yedeği başarıyla oluşturuldu.',
    },
    backupError: {
      title: 'Hata',
      description: 'Yedek oluşturulamadı: {{error}}',
    },
    switchSuccess: {
      title: 'Başarılı',
      description: 'Hesap başarıyla değiştirildi.',
    },
    switchError: {
      title: 'Hata',
      description: 'Hesap değiştirilemedi: {{error}}',
    },
    deleteSuccess: {
      title: 'Başarılı',
      description: 'Hesap yedeği başarıyla silindi.',
    },
    deleteError: {
      title: 'Hata',
      description: 'Yedek silinemedi: {{error}}',
    },
  },
  cloud: {
    'total-accounts': 'Toplam hesap',
    title: 'Hesaplar',
    description: 'Google Gemini hesaplarınızı yönetin.',
    security: {
      compatibilityMode: {
        title: 'Güvenlik anahtarları bu bilgisayarda saklanıyor',
        description:
          'Sistemin güvenli depolaması kullanılamadığından anahtarlar yerel bir dosyada saklanır. Bilgisayarı ve yedeklerini koruyun.',
      },
    },
    autoSwitch: 'Otomatik Değiştir',
    providerGroupings: 'Sağlayıcı Grupları',
    addAccount: 'Hesap Ekle',
    checkQuota: 'Kotayı Şimdi Kontrol Et',
    polling: 'Sorgulama tetiklendi',
    globalQuota: 'Genel Kota',
    layout: {
      auto: 'Otomatik',
      twoCol: '2 Sütun',
      threeCol: '3 Sütun',
      list: 'Liste',
      compact: 'Sıkışık',
    },
    'auto-switch-client': 'İstemci hesabını otomatik değiştir',
    'auto-switch-description':
      'Antigravity, IDE ve CLI hesaplarını değiştirir. API isteklerinde kullanılan hesapları API Proxy sayfasında seçebilirsiniz.',
    'quota-display': {
      title: 'Kota görünümü',
      description:
        'Hesap kartlarında gösterilecek kotaları seçin. Bu ayar kotayı veya isteklerde kullanılan hesabı değiştirmez.',
      'five-hours-gemini': 'Gemini 5 saatlik kota',
      'five-hours-claude': 'Claude 5 saatlik kota',
      'weekly-gemini': 'Gemini haftalık kota',
      'weekly-claude': 'Claude haftalık kota',
    },
    'quota-window': {
      label: 'Kota dönemi',
      'five-hours': '5 saatlik kota',
      'five-hours-short': '5 sa',
      weekly: 'Haftalık kota',
      'weekly-short': 'Hafta',
      'compact-weekly-short': 'Hf',
      'both-short': 'İkisi',
      'no-weekly-quota': 'Haftalık kota verisi yok',
      'weekly-summary-unavailable': 'Model hizmeti haftalık kullanım bilgilerini sağlamadı.',
      'weekly-bucket-unavailable': 'Dönen bilgilerde haftalık kullanım bulunamadı.',
    },
    authDialog: {
      'manual-sign-in': 'Kodu elle gir',
      'waiting-for-browser':
        'Tarayıcınızda oturum açmayı tamamlayın. Bu pencere otomatik olarak güncellenecek.',
      title: 'Google Hesabı Ekle',
      description:
        'Giriş yöntemini seçip tarayıcıda Google hesabınıza giriş yapın. Hesap otomatik olarak eklenecektir.',
      oauthClient: 'Oturum açma yöntemi',
      oauthClientPlaceholder: 'Giriş yöntemi seçin',
      openLogin: 'Giriş Sayfasını Aç',
      authCode: 'Yetkilendirme Kodu',
      placeholder: '4/ ile başlayan kodu yapıştırın...',
      instruction: 'Giriş otomatik tamamlanmazsa tarayıcıdaki kodu buraya yapıştırın.',
      verify: 'Doğrula ve Ekle',
    },
    card: {
      active: 'Aktif',
      use: 'Kullan',
      rateLimited: 'Hız Sınırına Takıldı',
      validationRiskControlled: 'Risk / Hız Sınırı',
      validationOAuthReauthRequired: 'Google hesabına yeniden giriş yapın',
      validationRequired: 'Doğrulama Gerekiyor',
      completeValidation: 'Doğrulamayı tamamla',
      left: 'kaldı',
      used: 'Kullanılan',
      unknown: 'Bilinmeyen Kullanıcı',
      actions: 'İşlemler',
      useAccount: 'Hesabı Kullan',
      identityProfile: 'Kimlik Profili',
      refresh: 'Kotayı Yenile',
      delete: 'Hesabı Sil',
      noQuota: 'Kota verisi yok',
      rateLimitedQuota: 'Hız Sınırına Takıldı',
      liveLimitModelNotSupported: 'Model desteklenmiyor',
      liveLimitModelForbidden: 'Model erişimi yasak',
      liveLimitQuotaExhausted: 'Kota tükendi',
      liveLimitRateLimited: 'Hız sınırı',
      liveLimitRemaining: '{{duration}} kaldı',
      liveLimitDetectedAgo: '{{duration}} önce algılandı',
      liveLimitActiveTitle: 'Model hizmeti geçici olarak kullanılamıyor.',
      liveLimitRecentTitle: 'Model hizmeti yakın zamanda bir hata bildirdi.',
      liveLimitQuotaSnapshot: 'Son kota kontrolü hâlâ %{{percentage}} gösterebilir.',
      liveLimitMessage: 'Mesaj: {{message}}',
      resetPrefix: 'sıfırlama',
      resetTime: 'Sıfırlanma zamanı',
      resetUnknown: 'Bilinmeyen',
      detailedQuota: 'Ayrıntılı kota',
      quotaGroupUnknown: 'Kota grubu',
      gemini3Ready: 'Gemini 3 Hazır',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'örn. http://127.0.0.1:7890',
      proxySaved: 'Proxy kaydedildi',
      'network-proxy': 'Ağ proxy’si',
      'network-proxy-description':
        'İsteğe bağlı: bu hesap için bir ağ proxy’si kullanın. Kaydetmek için Enter tuşuna basın veya adres alanından çıkın.',
      'proxy-replace-placeholder': 'Yeni proxy adresi girin',
      'proxy-remove': "Proxy'yi kaldır",
      'proxy-save-failed': 'Proxy kaydedilemedi',
      noProxy: 'Proxy yok',
      aiCredits: 'Yapay Zeka Kredileri',
      aiCreditsValue: '{{amount}} kredi',
      creditsExpiry: 'son kullanma tarihi {{date}}',
      modelVisibility: 'Model Görünürlüğü',
    },
    identity: {
      'profile-errors': {
        'account-not-found': 'Bu hesap artık kullanılamıyor.',
        'baseline-unavailable': 'Geri yüklenecek ilk kimlik profili bulunamadı.',
        'revision-not-found': 'Seçilen kimlik profili bulunamadı.',
        'profile-invalid': 'Bu kimlik profili kullanılamıyor. Başka bir profil seçin.',
        'profile-write-failed': 'Kimlik profili kaydedilemedi. Yeniden deneyin.',
        'profile-operation-failed': 'Kimlik profili işlemi tamamlanamadı. Yeniden deneyin.',
      },
      title: 'Hesabın cihaz bilgileri',
      loading: 'Yükleniyor...',
      generateAndBind: 'Yeni cihaz bilgileri oluştur',
      captureAndBind: 'Mevcut cihaz bilgilerini kullan',
      restoreOriginal: 'İlk cihaz bilgilerini geri yükle',
      openFolder: 'Cihaz bilgileri klasörünü aç',
      previewTitle: 'Yeni cihaz bilgileri',
      confirm: 'Onayla',
      cancel: 'İptal',
      close: 'Kapat',
      currentStorage: 'Mevcut cihaz ayarları',
      accountBinding: 'Bu hesap için kaydedilen',
      history: 'Kaydedilmiş sürümler',
      noHistory: 'Kimlik geçmişi yok',
      current: 'Aktif',
      restore: 'Geri Yükle',
      generateSuccess: 'Kimlik oluşturuldu ve bağlandı',
      captureSuccess: 'Mevcut kimlik yakalandı ve bağlandı',
      restoreOriginalSuccess: 'Temel kimlik geri yüklendi',
      restoreVersionSuccess: 'Geçmiş kimlik geri yüklendi',
      deleteVersionSuccess: 'Geçmiş kimlik silindi',
      openFolderSuccess: 'Kimlik depolama klasörü açıldı',
      baseline: 'İlk cihaz bilgileri',

      description: 'Hesap değiştirirken kullanmak için bu hesabın cihaz bilgilerini kaydedin.',
      'load-failed': 'Cihaz bilgileri okunamadı',
      'retry-description': 'Tekrar deneyin. Kaydedilmiş cihaz bilgileri değiştirilmedi.',
      'refresh-failed': 'Yenilenemedi. Önceden okunan cihaz bilgileri gösteriliyor.',
      updating: 'Cihaz bilgileri güncelleniyor…',
      'device-id': 'Cihaz numarası',
      'mac-device-id': 'Mac cihaz numarası',
      'installation-id': 'Kurulum numarası',
      'diagnostic-id': 'Tanılama numarası',
      'delete-version': 'Kaydedilmiş sürümü sil: {{label}}',
    },
    list: {
      noAccounts: 'Henüz bulut hesabı eklenmedi.',
      noFilteredAccounts: 'Seçilen katmanlarla eşleşen hesap yok.',
    },
    error: {
      loadFailed: 'Bulut hesapları yüklenemedi.',
      'report-issue': 'Bu sorunu bildirin',
      'report-preparing': 'Hata bilgileri hazırlanıyor…',
      'report-copied': 'Hata bilgileri kopyalandı',
      'report-paste-guide':
        'GitHub formuna yapıştırın, yaptığınız işlemleri açıklayın ve bildirimi gönderin.',
      'report-copy-failed': 'Hata bilgileri kopyalanamadı',
      'report-retry': 'Tekrar deneyin. Ayrıntıları açıp hatayı elle de kopyalayabilirsiniz.',
      'report-open-failed': 'GitHub açılamadı',
      'report-manual-open': 'Bilgiler kopyalandı. {{url}} adresini açıp bildirime yapıştırın.',
      dataRepair: {
        stepOpenIssue:
          'Bu sorunu GitHub’da bildirin. Bilgileri kopyalayıp formu açmak için tıklayın.',
      },
    },
    toast: {
      validationLinkFailed: {
        title: 'Google doğrulama sayfası açılamadı',
        codes: {
          'account-not-found': 'Bu hesap artık kullanılamıyor.',
          'no-trusted-link': 'Bu hesap için açılabilecek bir Google doğrulama sayfası yok.',
          'validation-link-failed': 'Google doğrulama sayfası açılamadı. Tekrar deneyin.',
        },
      },
      addSuccess: 'Hesap başarıyla eklendi!',
      addFailed: {
        title: 'Hesap eklenemedi',
        codes: {
          'authorization-denied': 'Google erişimine izin verilmedi. Tekrar deneyin.',
          'login-active': 'Google girişi zaten devam ediyor.',
          'login-cancelled': 'Giriş iptal edildi.',
          'login-timeout': 'Giriş süresi doldu. Yeniden başlayın.',
          'duplicate-account': 'Bu Google hesabı zaten ekli.',
          'browser-open-failed': 'Tarayıcı açılamadı. Varsayılan tarayıcınızı kontrol edin.',
          'login-failed': 'Hesap eklenemedi. Tekrar deneyin.',
        },
      },
      quotaRefreshed: 'Kota yenilendi',
      refreshFailed: 'Kota yenilenemedi',
      pollFailed: 'Tüm hesaplar için kota sorgulanamadı',
      switched: {
        title: 'Hesap değiştirildi!',
        description: 'Antigravity yeniden başlatılıyor...',
      },
      switchFailed: 'Hesap değiştirilemedi',
      switchFailureCodes: {
        'account-not-found': 'Bu hesap artık kullanılamıyor.',
        'reauth-required': 'Hesap değiştirmeden önce yeniden giriş yapın.',
        'identity-profile-required': 'Hesap değiştirmeden önce kimlik profili oluşturun.',
        'process-control-failed':
          'Antigravity kapatılamadı veya yeniden başlatılamadı. Tekrar deneyin.',
        'target-write-failed': "Seçilen hesap Antigravity'de kullanılamadı. Tekrar deneyin.",
        'switch-failed': 'Hesap değiştirilemedi. Tekrar deneyin.',
      },
      deleted: 'Hesap silindi',
      deleteFailed: 'Hesap silinemedi',
      deleteConfirm: 'Bu hesabı silmek istediğinizden emin misiniz?',
      autoSwitchOn: 'Otomatik Değiştirme Etkin',
      autoSwitchOff: 'Otomatik Değiştirme Devre Dışı',
      updateSettingsFailed: 'Ayarlar güncellenemedi',
      actionFailed: 'İşlem başarısız oldu',
      startAuthFailed: 'Oturum açma akışı başlatılamadı',
      refreshCreditsAvailable: 'Yapay Zeka kredileri: {{amount}}',
      refreshCreditsUnavailable: 'Bu yenileme için Yapay Zeka kredileri mevcut değil.',
      batchRefreshSuccess: '{{count}} hesap başarıyla yenilendi.',
      batchRefreshPartial: {
        title: 'Yenileme sorunlarla tamamlandı',
        description: '{{successful}} hesap yenilendi, {{failed}} başarısız oldu.',
      },
      batchDeleteSuccess: '{{count}} hesap başarıyla silindi.',
      batchDeletePartial: {
        title: 'Silme işlemi sorunlarla tamamlandı',
        description: '{{successful}} hesap silindi, {{failed}} başarısız oldu.',
      },
    },
    batch: {
      actions: 'Seçili hesap işlemleri',
      'delete-title': '{{count}} hesap silinsin mi?',
      cancel: 'İptal',
      selected: '{{count}} adet seçildi',
      delete: 'Seçilenleri Sil',
      refresh: 'Seçilenleri Yenile',
      selectAll: 'Tümünü Seç',
      clear: 'Seçimi Temizle',
      confirmDelete: '{{count}} hesabı silmek istediğinizden emin misiniz?',
    },
    tierFilter: {
      all: 'Tüm katmanlar',
      reset: 'Tümüne sıfırla',
      selectedCount: '{{count}} katman',
      unknown: 'Bilinmiyor',
    },
    sort: {
      recentlyUsed: 'Son Kullanılanlar',
      quotaOverall: 'Genel Kota',
      quotaClaude: 'Claude Kotası',
      quotaPro3: 'Pro3 Kotası',
      quotaFlash: 'Flash Kotası',
    },
    exportImport: {
      'file-errors': {
        'file-too-large': 'Seçilen dosya çok büyük. Daha küçük bir hesap yedeği seçin.',
        'invalid-export': 'Bu hesap yedeği tanınamadı. Geçerli bir yedek dosyası seçin.',
        'read-failed': 'Seçilen dosya açılamadı. Dosyanın yerinde olduğunu kontrol edin.',
        'write-failed': 'Hesap yedeği kaydedilemedi. Kaydetme konumunu kontrol edin.',
        'import-failed': 'Hesaplar içe aktarılamadı. Tekrar deneyin.',
        'tokens-missing':
          'Bu hesap yedeğinde giriş bilgileri yok. Giriş bilgilerini içeren bir yedek dışa aktarın.',
        'account-write-failed': 'Hesap kaydedilemedi.',
      },
      export: 'Dışa Aktar',
      import: 'İçe Aktar',
      exportTitle: 'Hesapları Dışa Aktar',
      exportDesc:
        'Yedeğe hesap giriş bilgilerinin eklenip eklenmeyeceğini seçin. Bu bilgileri içeren yedekleri gizli tutun.',
      includeTokens: 'Giriş bilgilerini ekle (hesapları geri yükler)',
      stripTokens: 'Giriş bilgilerini çıkar (paylaşmak için daha güvenli)',
      exportSuccess: 'Hesaplar başarıyla dışa aktarıldı',
      importTitle: 'Hesapları İçe Aktar',
      importDesc: 'Daha önce dışa aktarılmış bir JSON dosyası seçin.',
      importStrategy: 'İçe Aktarma Stratejisi',
      strategyMerge: 'Birleştir - Mevcut olanları güncelle, yenileri ekle',
      strategyOverwrite: 'Üzerine Yaz - Tüm mevcut verileri değiştir',
      strategySkip: 'Atla - Sadece yeni hesapları ekle',
      importSuccess: '{{imported}} içe aktarıldı, {{updated}} güncellendi, {{skipped}} atlandı',
      importErrors: 'İçe aktarma işlemi {{count}} hata ile tamamlandı',
      selectFile: 'Dosya Seç',
      importing: 'İçe aktarılıyor...',
      fileTooLarge: 'Dosya boyutu 5MB sınırını aşıyor',
      invalidJson: 'Geçersiz JSON dosya biçimi',
      readFileFailed: 'Dosya okunamadı',
    },
    localImport: {
      description:
        'Bu bilgisayarda oturum açılmış hesapları bulun. Aktarmadan önce sonuçları kontrol edin.',
      emailCollision: '{{email}} için {{count}} farklı kayıtlı giriş bulundu.',
      sources: {
        'antigravity-keyring': 'Sistemde kayıtlı giriş bilgileri',
        'antigravity-classic-db': 'Antigravity kayıtlı hesapları',
        'antigravity-ide-db': 'Antigravity IDE kayıtlı hesapları',
      },
      validationErrors: {
        'credential-unavailable':
          'Bu giriş bilgileri artık kullanılamıyor. Antigravity hesabına yeniden giriş yapıp tekrar tarayın.',
        'authentication-failed':
          'Google bu girişi kabul etmedi. Antigravity hesabına yeniden giriş yapıp tekrar tarayın.',
      },
      discoveryErrors: {
        missing: 'Burada kayıtlı giriş bilgisi bulunamadı.',
        'permission-denied':
          'Kayıtlı giriş bilgilerine erişim reddedildi. Erişim izinlerini kontrol edip yeniden deneyin.',
        locked:
          'Giriş bilgileri kilitli veya kullanımda. Erişim kilidini açın ya da Antigravity uygulamasını kapatıp tekrar tarayın.',
        malformed:
          'Kayıtlı giriş bilgileri okunamadı. Antigravity hesabına yeniden giriş yapıp tekrar tarayın.',
        'timed-out': 'Giriş bilgilerinin okunması çok uzun sürdü. Lütfen tekrar tarayın.',
        'read-failed': 'Kayıtlı giriş bilgileri okunamadı. Lütfen tekrar tarayın.',
      },
      importErrors: {
        'credential-unavailable':
          'Bu giriş bilgileri artık kullanılamıyor. İçeri aktarmadan önce tekrar tarayın.',
        'identity-conflict':
          'Bu giriş bilgileri mevcut hesapla eşleşmiyor. İçeri aktarmadan önce hesapları kontrol edin.',
      },
      errors: {
        'session-not-found': 'Bu tarama sonuçları artık kullanılamıyor. Lütfen tekrar tarayın.',
        'session-expired': 'Bu tarama sonuçlarının süresi doldu. Lütfen tekrar tarayın.',
        'session-consumed':
          'Bu tarama sonuçları zaten kullanıldı. Daha fazla hesap aktarmak için tekrar tarayın.',
      },

      title: 'Bu bilgisayardan hesap aktar',

      trigger: 'Bu bilgisayardan hesap aktar',
    },

    feedback: {
      'loading-title': 'Hesaplarınız okunuyor',
      'loading-description': 'Hesap bilgileriniz hazır olduğunda burada görünecek.',
      'empty-description':
        'Oturum açmak için Hesap Ekle’yi seçin veya mevcut bir hesap dosyasını içe aktarın.',
      'filtered-description':
        'Daha fazla hesap görmek için başka bir plan deneyin veya filtreyi temizleyin.',
    },
  },
  proxy: {
    'advanced-options': 'Diğer hizmet ayarları',
    'advanced-description': 'Hesap seçimi, ortak talimatlar ve araç uyumluluğu.',
    tabs: { tools: 'Araçlar', models: 'Modeller', records: 'Kayıtlar', examples: 'Örnekler' },
    'account-strategy': {
      'save-failed': 'Seçiminiz kaydedilemedi. Yeniden denemek için tekrar seçin.',
      title: 'API isteklerinde kullanılan hesaplar',
      balanced: 'Kullanılabilir hesapları sırayla kullan',
      'account-first': 'Aynı hesabı tercih et',
      'balanced-description':
        'Yeni sohbetleri kullanılabilir hesaplara dağıtır. Mevcut sohbet, hesabı kullanılabilir olduğu sürece aynı hesabı kullanır.',
      'account-first-description':
        'Her model için aynı hesabı kullanmaya devam eder. Kota bittiğinde, hesap geçici olarak sınırlandığında veya isteği karşılayamadığında başka hesaba geçer. Mevcut sohbetler kullanılabilir hesaplarını korur.',
      'client-description':
        'Bu ayar Antigravity, IDE veya CLI oturum hesabını değiştirmez. İstemci hesabının otomatik değiştirilmesi Hesaplar sayfasından yönetilir.',
    },
    title: 'API Proxy',
    description: 'Yerel API proxy hizmetini yönetin.',
    save: 'Ayarları Kaydet',
    copy: 'Kopyala',
    copied: 'Kopyalandı!',
    regenerate: 'Yeniden Oluştur',
    regenerateConfirm: {
      title: 'API Anahtarı Yeniden Oluşturulsun mu?',
      description:
        'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan tüm uygulamalar çalışmayı durduracaktır.',
      cancel: 'İptal',
      confirm: 'Yeniden Oluştur',
    },
    'risk-confirmation': {
      title: 'Proxy başlatılmadan önce riskleri onaylayın',
      description:
        'Google, şubat ayından bu yana denetimlerini artırmıştır. Bu yazılımla yalnızca hesap değiştirmek Google hesabınızı etkilemez.\n\nAncak yazılımı ters proxy veya benzer amaçlarla kullanmak Google Hizmet Şartları’nı ihlal eder ve hesabınızın askıya alınmasına yol açabilir.',
      'account-advice': 'Yalnızca kaybetmeyi göze alabileceğiniz hesapları kullanın.',
      cancel: 'İptal',
      confirm: 'Riskleri anlıyorum. Proxy başlat',
    },
    service: {
      title: 'Hizmet Durumu',
      description: 'Yerel API proxy sunucusunu kontrol edin.',
      running: 'Çalışıyor',
      stopped: 'Durduruldu',
      start: 'Hizmeti Başlat',
      stop: 'Hizmeti Durdur',
      start_failed: 'Hizmet başlatılamadı',
      port_in_use_title: 'Port zaten kullanılıyor',
      port_in_use_description:
        '{{port}} portu başka bir işlem tarafından kullanılıyor. Bu işlemi kapatın veya Ayarlar bölümünden API proxy dinleme portunu değiştirip tekrar deneyin.',
    },
    config: {
      port: 'Dinleme Portu',
      timeout: 'İstek Zaman Aşımı',
      api_key: 'API Anahtarı',
      auto_start: 'Uygulama ile Otomatik Başlat',
      auto_start_desc: 'Uygulama başlatıldığında proxy hizmetini de başlat',
      'allow-local-video-paths': 'Yerel video yollarına izin ver',
      'allow-local-video-paths-desc':
        'Bağlı araçların bu bilgisayarda hesabınızın erişebildiği video dosyalarını okumasına izin verir. Yalnızca güvendiğiniz araçlar için etkinleştirin.',
      'global-system-prompt-title': 'Tüm yapay zekâ istekleri için talimatlar',
      'global-system-prompt-description':
        'Manager üzerinden gönderilen her istekte bu talimatlar, bağlı aracın talimatlarından önce otomatik olarak eklenir.',
      'global-system-prompt-placeholder':
        'Genel bir sistem istemi girin...\nÖrneğin: Basitleştirilmiş Çince yanıt verin ve kod değişikliklerini kısa açıklayın.',
      'global-system-prompt-character-count': '{{count}} karakter',
      'global-system-prompt-long-warning':
        '2.000 karakterden uzun talimatlar sohbet geçmişi için daha az yer bırakır. Talimatları kısaltmayı düşünün.',
      local_access: 'Yerel ağ erişimi:',
      select_ip: 'IP Seç',
      no_token_warning: '⚠️ API anahtarı ayarlanmadı. Erişim herkese açık!',
      show_key: 'Göster',
      hide_key: 'Gizle',
      cloud_code_meta: 'Cloud Code uyumluluğu',
      cloud_code_meta_desc:
        'Eski Cloud Code araçlarının ihtiyaç duyduğu ek yanıt bilgilerini ekler. Diğer araçlar bu bilgileri kabul etmeyebilir; yalnızca gerektiğinde açın.',
    },
    mapping: {
      title: 'Model Eşleme',
      description: 'Her Claude model isteğini hangi Gemini modelinin karşılayacağını seçin.',
      maps_to: 'Şu modele eşlenir:',
      restore: 'Varsayılanlara Sıfırla',
      'only-raw-quota-models': 'Yalnızca hesaplarınızda bulunan modelleri listele',
      'only-raw-quota-models-desc':
        'Bağlı araçlar yalnızca son hesap kota kontrollerindeki model adlarını görür. Ek model takma adları listelenmez.',
    },
    'open-code': {
      title: 'OpenCode eşitleme',
      description:
        'Diğer ayarlarınızı, yorumları ve biçimi koruyarak OpenCode uygulamasını Manager uygulamasına bağlayın.',
      synced: 'Eşitlendi',
      'synced-custom-url': 'Özel URL ile eşitlendi',
      'not-synced': 'Eşitlenmedi',
      'config-path': 'Yapılandırma',
      'configured-models': 'Yapılandırılmış modeller',
      runtime: 'OpenCode kurulumu',
      installed: 'Yüklü',
      'not-installed': 'Algılanmadı',
      credential: 'OpenCode bağlantı anahtarı',
      'key-stored': 'Sistemin güvenli depolamasında kayıtlı',
      'key-missing': 'Bir sonraki eşitlemede oluşturulacak',
      'backup-notice':
        'Yedekler yorumları ve biçimi korur. Manager bağlantı anahtarı kullanılamayan bir değerle değiştirilir; geri yüklemede geçerli anahtar kullanılır.',
      sync: "OpenCode'u yapılandır ve eşitle",
      restore: 'Yedeği geri yükle',
      clear: 'Yönetilen yapılandırmayı temizle',
      revoke: 'Özel anahtarı iptal et',
      'model-dialog-title': 'OpenCode modellerini seçin',
      'model-dialog-description':
        'Seçilen modeller eklenir veya güncellenir. Seçilmeyen mevcut modeller silinmez.',
      'custom-base-url': 'Manager adresi',
      'reset-base-url': 'Sıfırla',
      'invalid-base-url': 'Geçerli bir HTTP veya HTTPS URL girin.',
      'sync-accounts': 'Hesapları OpenCode giriş eklentisinde kullan',
      'sync-accounts-description':
        'Etkinleştirildiğinde OpenCode, bu hesaplarda oturumun açık kalmasını sağlayan bilgileri bu bilgisayardaki bir dosyaya kaydeder. Varsayılan olarak kapalıdır. Yalnızca güvendiğiniz bir bilgisayarda etkinleştirin.',
      'select-models': 'Eklenecek veya güncellenecek modeller',
      'selected-count': '{{total}} modelden {{selected}} tanesi seçili',
      'select-all': 'Tümünü seç',
      'deselect-all': 'Tümünün seçimini kaldır',
      'confirm-sync': 'Eşitlemeyi onayla',
      'auth-plugin-warning-title': 'Başka bir giriş eklentisi bulundu',
      'auth-plugin-warning-description':
        'opencode-antigravity-auth farklı bir bağlantı kullanabilir. Bu ayarları kullanmadan önce OpenCode içinde Manager seçildiğini kontrol edin.',
      'view-config': 'Yapılandırmayı görüntüle',
      'restore-confirm-title': 'OpenCode yedeği geri yüklensin mi?',
      'restore-confirm-description':
        'Dosyanın tamamı ilk yedekle değiştirilir; sonraki değişiklikler de üzerine yazılır. Başarılı geri yüklemeden sonra yedek kaldırılır.',
      'confirm-restore': 'Geri yüklemeyi onayla',
      'clear-confirm-title': 'Manager bağlantısı kaldırılsın mı?',
      'clear-confirm-description':
        'Bu bağlantı ve özel anahtarı kaldırılır. Diğer hizmetler, ayarlar ve yedek korunur.',
      'confirm-clear': 'Temizlemeyi onayla',
      'config-viewer-title': 'OpenCode yapılandırması',
      'config-viewer-description': 'Salt okunur yapılandırma önizlemesi',
      'config-redacted-notice': 'Bu önizlemede özel bilgiler gizlenir.',
      'config-copied': 'Yapılandırma özel bilgiler gizlenerek kopyalandı',
      'config-copy-failed': 'Yapılandırma kopyalanamadı',
      'config-load-failed': 'Yapılandırma yüklenemedi',
      'copy-config': 'Yapılandırmayı kopyala (özel bilgiler gizli)',
      'success-title': 'OpenCode yapılandırması güncellendi',
      'error-title': 'OpenCode güncellemesi başarısız',
      'unknown-error': 'Bilinmeyen OpenCode yapılandırma hatası',

      'choose-model-hint': 'Devam etmek için en az bir model seçin.',
      'config-retry-description': 'Tekrar deneyin. Kaydedilmiş ayarlarınız değiştirilmedi.',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: "Yerel API proxy'sini çağırmak için örnek komutlar.",
    },
    persistence: {
      title: 'Request history and reasoning',
      description: 'Inspect bounded local records without slowing model traffic.',
      'audit-title': 'İstek geçmişi',
      'audit-description':
        'İstekleri, yanıtları ve model hizmetine erişim denemelerini bu bilgisayarda hassas bilgileri gizleyerek kaydeder.',
      rows: '{{count}} requests',
      queue: '{{count}} kayıt kaydedilmeyi bekliyor',
      dropped:
        '{{count}} kayıt kaydedilemedi ({{reason}}). Model istekleri normal şekilde devam etti.',
      'disk-gib': 'Disk limit (GiB)',
      'body-hours': 'Tam içeriğin saklanma süresi (saat)',
      'summary-days': 'Summary retention (days)',
      'max-rows': 'Maximum rows',
      'no-audit': 'No traffic records yet.',
      'audit-metadata': 'İstek ayrıntıları ve model hizmeti denemeleri',
      'audit-body-missing': 'İsteğin veya yanıtın tam içeriği artık saklanmıyor.',
      'audit-body-expired':
        'Tam içeriğin saklanma süresi doldu ancak istek ayrıntıları hâlâ görülebilir.',
      partial: 'Partial',
      'logical-size': 'İçerik boyutu',
      'parse-error-offset': 'Okunamayan içerik konumu',
      loading: 'Loading…',
      'copy-progress': 'Preparing full copy: {{value}}%',
      'previous-page': 'Previous page',
      'next-page': 'Next page',
      'copy-full': 'Copy complete body',
      'confirm-copy-full': 'Confirm copying {{size}}',
      'clear-audit': 'İstek geçmişini temizle',
      'repair-audit': 'İstek geçmişini onar',
      'thought-title': 'Reasoning history',
      'thought-description': 'Save reasoning so later turns can continue the conversation.',
      sessions: '{{count}} sessions',
      'hard-limit': 'Her sohbet en fazla 200 tur ve 64 MiB içerik kaydedebilir.',
      'retention-days': 'Retention (days)',
      'max-sessions': 'Maximum sessions',
      oversized: 'İçerik 64 MiB sınırını aştığı için tam kaydedilmedi.',
      'no-thought-body': 'No stored thought body.',
      signature: 'Signature',
      'copy-signature': 'Copy signature',
      'no-thought': 'No reasoning history yet.',
      'clear-thought': 'Clear reasoning history',
      'repair-thought': 'Repair reasoning history',
      'confirm-clear': 'Confirm clear',
      'confirm-repair': 'Confirm repair',
    },
  },
  traffic: {
    'detail-load-failed': 'Bu istek yüklenemedi. Tekrar deneyin.',
    'detail-not-found': 'Bu kayıt artık mevcut değil. Temizlenmiş olabilir.',
    fields: {
      category: 'Kategori',
      method: 'İstek yöntemi',
      'requested-model': 'İstenen model',
      'mapped-model': 'Seçilen model yolu',
      error: 'Hata ayrıntıları',
      affected: 'Etkilenen kayıtlar',
      'request-id': 'İstek numarası',
      'client-address': 'İstemci adresi',
      username: 'Kullanıcı',
      'reasoning-tokens': 'Düşünme tokenları',
      'cached-tokens': 'Önbellek tokenları',
      query: 'Ek istek seçenekleri',
    },
    outcomes: {
      in_progress: 'İşleniyor',
      completed: 'Tamamlandı',
      client_cancelled: 'İptal edildi',
      client_disconnected: 'Bağlantı kapandı',
      timeout: 'Zaman aşımı',
      upstream_error: 'Model hizmeti hatası',
      auth_failed: 'Oturum açma başarısız',
      internal_error: 'Uygulama hatası',
      partial: 'Kısmi sonuç',
    },
    'search-metadata': 'Model, istek numarası veya adres ara',
    'copy-upstream-curl': 'Model hizmeti isteğini cURL olarak kopyala (özel bilgiler gizli)',
    'upstream-attempts': 'Model hizmetine gönderilen istekler',
    'no-attempts': 'Model hizmetine istek gönderilmedi.',
    upstream: 'Model hizmeti',
    endpoint: 'Hizmet adresi',
    protocol: 'API biçimi',
    'repair-databases': 'Kaydedilen kayıtları onar',
    'concise-help':
      'Ana istek bilgilerini gösterir. Açılan bölümler tüm içeriği göstermeye devam eder.',
    'full-help':
      'Yüklenen tüm bilgileri gösterir. İçerik düzenlenemiyorsa veya eksikse iki görünüm aynı görünebilir.',
    'load-next-window': 'Sonraki bölüm',
    offset: 'İçerik konumu {{offset}}',
    'parse-error': 'İçerik {{offset}} konumunda okunamadı.',
    'thought-oversized':
      'Düşünme içeriği 64 MiB sınırını aştığı için tam kaydedilmedi. Referans: {{hash}}',

    'loading-description': 'İstek kayıtlarınız hazır olduğunda burada görünecek.',
    'empty-description':
      'Proxy üzerinden gönderilen istekler burada görünür. Filtreleri de değiştirebilirsiniz.',
    'empty-category-description':
      'Bu kategorinin kayıtları burada görünür. Başka bir kategori deneyin veya filtreleri değiştirin.',
    'load-failed': 'İstek kayıtları okunamadı',
    'load-failed-description':
      'Lütfen tekrar deneyin. Bu, kayıtlarınızın silindiği anlamına gelmez.',
    'refresh-failed': 'Kayıtlar yenilenemedi. Önceden yüklenen kayıtlar gösterilmeye devam ediyor.',
  },
};
export default tr;
