const vi = {
  'agent-tools': {
    title: 'Kết nối công cụ lập trình',
    description: 'Chọn công cụ để dùng mô hình qua Antigravity Manager.',
    loading: 'Đang đọc cài đặt…',
    installed: 'Đã cài đặt',
    'not-installed': 'Chưa tìm thấy bản cài đặt',
    'read-error': 'Không thể đọc cài đặt. Hãy thử lại trước khi thay đổi.',
    retry: 'Thử lại',
    configured: 'Đã lưu cấu hình',
    'custom-address': 'Đang dùng địa chỉ khác',
    'not-configured': 'Chưa cấu hình',
    'not-verified': 'Chưa xác minh yêu cầu',
    address: 'Địa chỉ Manager',
    model: 'Mô hình',
    'not-set': 'Chưa đặt',
    'choose-model': 'Chọn khi cấu hình',
    update: 'Cập nhật cấu hình',
    configure: 'Cấu hình',
    view: 'Xem cấu hình',
    restore: 'Khôi phục bản sao lưu',
    remove: 'Gỡ kết nối',
    'install-notice': 'Bạn có thể lưu cài đặt trước khi cài công cụ. Sau đó hãy mở lại công cụ.',
    'action-error': 'Không thể cập nhật cài đặt',
    saved: 'Đã cập nhật cài đặt',
    reopen: 'Mở lại {{name}} để áp dụng cài đặt.',
    'configure-title': 'Kết nối {{name}}',
    'configure-description':
      'Yêu cầu sẽ đi qua Manager. Cài đặt hiện tại được sao lưu trước thay đổi đầu tiên.',
    'restore-title': 'Khôi phục cài đặt {{name}}?',
    'restore-description':
      'Toàn bộ tệp sẽ được thay bằng bản sao lưu ban đầu, kể cả các chỉnh sửa sau đó. Nếu Manager tạo tệp, tệp sẽ bị xóa. Bản sao lưu chỉ dùng một lần.',
    'remove-title': 'Gỡ kết nối với Manager?',
    'remove-description': 'Khôi phục cài đặt kết nối trước đó, giữ cài đặt khác và bản sao lưu.',
    'preview-title': 'Cài đặt {{name}}',
    'preview-description':
      'Chỉ hiển thị cài đặt cần thiết để kết nối với Manager. Khóa kết nối được ẩn.',
    confirm: 'Xác nhận',
    advanced: 'Địa chỉ và tệp cấu hình',
    'reset-address': 'Dùng địa chỉ Manager hiện tại',
    'backend-files':
      'Các cài đặt này được lưu trên máy tính chạy dịch vụ Manager, cho người dùng chạy dịch vụ đó.',
    'backup-notice': 'Giữ bản sao lưu đầu tiên khi cập nhật. Mở lại công cụ sau khi lưu.',
    'toml-notice':
      'Định dạng và chú thích trong cài đặt Codex có thể thay đổi. Bản sao đầy đủ được lưu để khôi phục. Thông tin đăng nhập và quyền hiện có được giữ lại.',
    'codex-review':
      'Cấu hình yêu cầu tác vụ và kiểm tra tự động. Giữ tuyến kiểm tra đang bật và cài đặt phê duyệt.',
    'model-count': '{{count}} mô hình',
    'plugin-notice':
      'Đã cài plugin đăng nhập trực tiếp. Hãy kiểm tra Manager được chọn trong OpenCode.',
    'revoke-key': 'Vô hiệu hóa khóa kết nối OpenCode',
    errors: {
      unavailable: 'Không thể truy cập cài đặt. Hãy thử lại.',
      'invalid-config': 'Tệp không hợp lệ hoặc quá lớn. Hãy sửa trước khi cấu hình.',
      'read-failed': 'Không thể đọc tệp. Hãy kiểm tra quyền truy cập.',
      'write-failed': 'Không thể lưu. Bản sao lưu vẫn được giữ.',
      'backup-failed': 'Không thể tạo bản sao lưu. Cài đặt công cụ chưa thay đổi.',
      'backup-missing': 'Không có bản sao lưu để khôi phục.',
      'configuration-changed': 'Cài đặt thay đổi trong lúc xử lý. Hãy đọc lại và thử lại.',
      'key-missing': 'Hãy tạo khóa kết nối ở trang proxy trước.',
      'review-route-disabled': 'Tuyến kiểm tra Codex bị tắt. Hãy bật trong ánh xạ mô hình.',
    },

    'address-help': 'Giữ địa chỉ Manager hiện tại, trừ khi dịch vụ chạy trên máy tính khác.',
    'invalid-address':
      'Dùng địa chỉ Manager bắt đầu bằng http:// hoặc https://, không chứa thông tin đăng nhập hay tham số bổ sung.',
    'model-required': 'Chọn một mô hình trước khi lưu.',
  },
  appName: 'Antigravity Manager',
  'process-runtime': {
    'update-in-progress': 'Antigravity đang cập nhật. Hãy hoàn tất cập nhật rồi thử lại.',
    'close-failed':
      'Không thể đóng Antigravity. Hãy lưu cuộc trò chuyện và tệp, đóng ứng dụng thủ công rồi thử lại.',
    'exit-unconfirmed':
      'Antigravity chưa đóng xong. Hãy lưu cuộc trò chuyện và tệp, đóng ứng dụng thủ công rồi thử lại.',
    working: 'Đang xử lý...',
    busy: 'Antigravity đang bận. Vui lòng đợi thao tác hoàn tất.',
    'missing-executable':
      'Không tìm thấy hoặc không thể mở Antigravity. Hãy kiểm tra vị trí ứng dụng trong Cài đặt.',
    'target-conflict':
      'Antigravity đang chạy không phải bản cài đặt được chọn trong Cài đặt. Hãy đóng ứng dụng hoặc chọn đúng bản cài đặt trước khi đổi tài khoản.',
    'directory-conflict':
      'Antigravity đang dùng thư mục dữ liệu khác với thư mục đã chọn. Hãy đóng ứng dụng hoặc kiểm tra cài đặt thư mục trước khi đổi tài khoản.',
    'probe-failed':
      'Không thể kiểm tra trạng thái Antigravity kịp thời. Hãy kiểm tra ứng dụng có đang mở rồi thử lại.',
    'launch-failed': 'Không thể mở Antigravity. Hãy kiểm tra vị trí ứng dụng và quyền truy cập.',
    'startup-unconfirmed':
      'Chưa xác nhận được Antigravity đã mở. Không khởi chạy lần nữa để tránh mở hai lần. Hãy kiểm tra ứng dụng trước khi thử lại.',
    'switched-hot-unconfirmed':
      'Tài khoản mới đã được lưu nhưng chưa xác nhận đổi tài khoản trong Antigravity IDE. Hãy kiểm tra tài khoản hiển thị trong IDE trước khi thử lại.',
    'switched-startup-unconfirmed':
      'Tài khoản mới đã được lưu nhưng chưa xác nhận Antigravity đã mở. Không khởi chạy lần nữa. Hãy kiểm tra ứng dụng trước khi thử lại.',
  },
  common: {
    close: 'Đóng',
    cancel: 'Hủy',
    'core-unavailable-title': 'Không thể kết nối với Antigravity Manager',
    'core-unavailable-body':
      'Tài khoản và proxy hiện không dùng được. Hãy đóng rồi mở lại Antigravity Manager. Nếu vẫn gặp lỗi, hãy cài đặt phiên bản mới nhất.',
    'account-data-unavailable-title': 'Không thể mở các tài khoản đã lưu',
    'account-data-unavailable-body':
      'Hiện không thể đọc các tài khoản đã lưu. Hãy kiểm tra bạn đang đăng nhập bằng tài khoản thường dùng trên máy tính này, rồi mở lại Antigravity Manager. Dữ liệu tài khoản của bạn không thay đổi.',
    'already-running-title': 'Antigravity Manager đang chạy',
    'already-running-body':
      'Hãy đóng cửa sổ Antigravity Manager khác rồi thử lại. Nếu không tìm thấy, hãy khởi động lại máy tính.',
    loading: 'Đang tải...',
    error: 'Lỗi',
    unknown: 'Không rõ',
    notAvailable: 'Không có',
    openMenu: 'Mở menu',

    'dismiss-notification': 'Đóng thông báo',
    'reading-settings': 'Đang đọc cài đặt của bạn…',
  },
  status: {
    checking: 'Đang kiểm tra trạng thái...',
    running: 'Antigravity đang chạy nền',
    stopped: 'Dịch vụ Antigravity đã dừng',
    services: 'Dịch vụ',
    dashboard_title: 'Trạng thái dịch vụ',
    open_dashboard: 'Mở trạng thái dịch vụ',
    checking_short: 'Đang kiểm tra...',
    running_short: 'Đang chạy',
    stopped_short: 'Đã dừng',
    all_running: 'Tất cả dịch vụ đang chạy',
    all_stopped: 'Tất cả dịch vụ đã dừng',
    partial_running: '{{running}}/{{total}} dịch vụ đang chạy',
  },
  action: {
    stop: 'Dừng',
    start: 'Bắt đầu',
    switch: 'Chuyển',
    deleteBackup: 'Xóa bản sao lưu',
    backupCurrent: 'Sao lưu tài khoản hiện tại',
    retry: 'Thử lại',
    details: 'Chi tiết',
    openLogs: 'Mở thư mục log',
  },
  update: {
    title: 'Cập nhật',
    checking: 'Đang kiểm tra...',
    checkNow: 'Kiểm tra cập nhật',
    checkFailed: 'Không thể kiểm tra cập nhật',
    upToDate: 'Bạn đang dùng phiên bản mới nhất.',
    unsupported: 'Nền tảng này không hỗ trợ kiểm tra cập nhật tự động.',
    available: {
      title: 'Có bản cập nhật',
      description: 'Phiên bản {{version}} đã có trên GitHub.',
      download: 'Tải xuống',
      downloading: 'Đang tải...',
      dismiss: 'Đóng',
      macosUnsignedNote:
        'Bản macOS này chưa được ký chính thức. Nếu macOS chặn ứng dụng, hãy làm theo các bước ký thủ công trong GitHub README hoặc các issue liên quan.',
    },
    downloaded: {
      title: 'Bản cập nhật đã sẵn sàng',
      description: 'Phiên bản {{version}} đã được tải xuống.',
      restart: 'Khởi động lại',
    },
  },
  error: {
    generic: 'Đã xảy ra lỗi không mong đợi.',
    detailsTitle: 'Chi tiết lỗi',
    detailsDescription:
      'Những thông tin này có thể giúp tìm nguyên nhân sự cố và có thể chứa vị trí tệp cá nhân. Hãy kiểm tra trước khi chia sẻ.',
    keychainUnavailable: 'Hiện không thể đọc thông tin đăng nhập đã lưu.',
    keychainHint: {
      translocation: 'Hãy chuyển ứng dụng vào thư mục Ứng dụng, rồi mở lại.',
      keychainDenied:
        'macOS đã chặn quyền truy cập thông tin đăng nhập đã lưu. Hãy xem hướng dẫn cài đặt ứng dụng rồi thử lại.',
      signNotarize: 'Nếu có, hãy cài đặt phiên bản được macOS xác minh.',
    },
    dataMigrationFailed: 'Không thể đọc các tài khoản được lưu bằng phiên bản trước.',
    masterKeyUnavailable:
      'Đã tìm thấy các tài khoản đã lưu nhưng hiện chưa thể mở. Dữ liệu tài khoản của bạn không bị thay đổi.',
    dataMigrationHint: {
      relogin: 'Hãy đăng nhập lại hoặc thêm lại tài khoản của bạn.',
      clearData: 'Nếu lỗi vẫn tiếp diễn, hãy xóa dữ liệu tài khoản cục bộ rồi đăng nhập lại.',
    },
    antigravityStorageJsonNotFound:
      'Antigravity chưa hoàn tất thiết lập ban đầu. Hãy mở ứng dụng đã chọn và đăng nhập một lần, rồi thử đổi tài khoản lại.',
    antigravityProjectIdMissing:
      'Tài khoản này chưa sẵn sàng dùng với Antigravity. Hãy đăng nhập tài khoản trong Antigravity một lần, rồi thử lại.',
    antigravityDatabasePermissionDenied:
      'Không thể lưu thông tin đăng nhập Antigravity. Hãy kiểm tra quyền ghi vào thư mục dữ liệu, hoặc mở Antigravity một lần rồi khởi động lại Manager.',
    cloudAccountLoginExpired:
      'Thông tin đăng nhập cho tài khoản cloud này đã hết hạn. Hãy đăng nhập lại.',
  },
  nav: {
    navigation: 'Điều hướng',
    'collapse-sidebar': 'Thu gọn thanh bên',
    'expand-sidebar': 'Mở rộng thanh bên',
    accounts: 'Tài khoản',
    proxy: 'API Proxy',
    settings: 'Cài đặt',
  },
  editionSelection: {
    title: 'Chọn phiên bản Antigravity',
    description:
      'Chọn phiên bản Antigravity bạn đang sử dụng. Điều này giúp Manager kết nối đúng ứng dụng.',
    edition1x: {
      name: 'Antigravity 1.x',
      description: 'Ứng dụng Antigravity gốc. Chọn nếu bạn đang dùng phiên bản cũ.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description: 'Antigravity IDE mới (2.0). Chọn nếu bạn đang dùng phiên bản IDE mới nhất.',
    },
    confirm: 'Tiếp tục',
  },
  account: {
    current: 'Hiện tại',
    lastUsed: 'Đã dùng {{time}}',
    switchToAntigravity: 'Chuyển sang Antigravity',
    switchToIde: 'Chuyển sang Antigravity IDE',
  },
  home: {
    title: 'Tài khoản',
    description: 'Quản lý các tài khoản Antigravity Google Gemini.',
    noBackups: {
      title: 'Chưa tìm thấy bản sao lưu',
      description: 'Hãy tạo bản sao lưu cho tài khoản Antigravity hiện tại để bắt đầu.',
      action: 'Sao lưu tài khoản hiện tại',
    },
  },
  settings: {
    'service-unavailable':
      'Hiện không thể mở hoặc lưu cài đặt. Hãy thử lại. Nếu vẫn gặp lỗi, hãy đóng rồi mở lại Antigravity Manager.',
    'service-retry': 'Thử lại',
    'service-restart-required': 'Đã lưu cài đặt. Hãy tắt rồi bật lại proxy để áp dụng thay đổi.',
    'service-save': 'Lưu',
    'service-secret-configured': 'Đã đặt địa chỉ proxy. Nhập địa chỉ mới để thay thế.',
    'weekly-warmup': {
      error: 'Không thể tải hoặc lưu cài đặt làm nóng.',
      retry: 'Thử lại',
      'cost-notice':
        'Làm nóng tiêu thụ hạn mức mô hình và có thể dùng tín dụng AI. Yêu cầu HTTP được chấp nhận không đảm bảo bộ đếm tuần đã khởi động lại.',
      title: 'Làm nóng hạn mức hàng tuần',
      description:
        'Sau khi hạn mức hàng tuần đã chọn được đặt lại, gửi một yêu cầu tối thiểu cho mỗi nhóm và lưu chu kỳ thành công.',
      enabled: 'Bật làm nóng hạn mức hàng tuần',
      groups: 'Nhóm hạn mức cần làm nóng',
      group: { claude: 'Nhóm hạn mức Claude', gemini: 'Nhóm hạn mức Gemini' },
    },
    title: 'Cài đặt',
    description: 'Quản lý tùy chọn ứng dụng.',
    general: 'Chung',
    connection: 'Kết nối',
    models: 'Mô hình',
    appearance: {
      title: 'Giao diện',
      description: 'Tùy chỉnh giao diện Antigravity Manager trên thiết bị của bạn.',
    },
    darkMode: 'Chế độ tối',
    darkModeDescription: 'Bật chế độ tối để dễ nhìn hơn vào ban đêm.',
    language: {
      title: 'Ngôn ngữ',
      description: 'Chọn ngôn ngữ bạn muốn sử dụng.',
      english: 'Tiếng Anh',
      chinese: 'Tiếng Trung Giản thể',
      russian: 'Tiếng Nga',
      vietnamese: 'Tiếng Việt',
      turkish: 'Tiếng Thổ Nhĩ Kỳ',
      french: 'Tiếng Pháp',
    },
    about: {
      title: 'Thông tin',
      description: 'Thông tin ứng dụng.',
    },
    cache: {
      title: 'Bộ nhớ đệm Antigravity',
      description:
        'Xóa các thư mục bộ nhớ đệm Antigravity và Antigravity IDE đã biết để khắc phục lỗi đăng nhập hoặc xác thực phiên bản.',
      clear: 'Xóa bộ nhớ đệm Antigravity',
      dialogTitle: 'Xóa bộ nhớ đệm Antigravity?',
      dialogDescription: 'Các thư mục bộ nhớ đệm hiện có sau đây sẽ bị xóa.',
      pathsLabel: 'Thư mục bộ nhớ đệm',
      noPaths: 'Không tìm thấy thư mục bộ nhớ đệm Antigravity đã biết.',
      warning: 'Hãy đóng Antigravity trước khi xóa để tránh tệp bị khóa.',
      cancel: 'Hủy',
      confirm: 'Xóa bộ nhớ đệm',
      clearing: 'Đang xóa...',
      clearedTitle: 'Đã xóa bộ nhớ đệm',
      clearedDescription: 'Đã xóa {{size}} MB khỏi các thư mục bộ nhớ đệm Antigravity.',
      failedTitle: 'Không thể xóa bộ nhớ đệm',
      notFoundTitle: 'Không tìm thấy bộ nhớ đệm Antigravity',

      'paths-failed': 'Không thể tìm vị trí bộ nhớ đệm',
      'paths-retry-description': 'Vui lòng thử lại trước khi xóa bộ nhớ đệm.',
      'partial-title': 'Không thể xóa một phần bộ nhớ đệm',
      'partial-description':
        'Đã giải phóng {{size}} MB. Chưa xóa được {{count}} vị trí. Hãy đóng Antigravity rồi thử lại.',
    },
    version: 'Phiên bản',
    platform: 'Nền tảng',
    license: 'Giấy phép',
    openLogDir: 'Mở',
    toast: {
      saved: {
        title: 'Đã lưu cài đặt',
        description: 'Cấu hình của bạn đã được cập nhật.',
      },
      saveFailed: {
        title: 'Không thể lưu cài đặt',
      },
    },
    account: {
      'client-setup': 'Vị trí và cách khởi chạy ứng dụng',
      'client-setup-description':
        'Chỉ thay đổi khi Manager không tìm thấy ứng dụng hoặc bạn cần tùy chỉnh cách khởi chạy.',
      'choose-file': 'Chọn tệp',
      'clear-field': 'Xóa nội dung này',
      title: 'Cài đặt tài khoản',
      description: 'Cấu hình tự động làm mới quota và đồng bộ.',
      auto_refresh: 'Tự động làm mới quota',
      auto_refresh_desc: 'Định kỳ cập nhật thông tin quota cho tất cả tài khoản',
      auto_sync: 'Tự động đồng bộ tài khoản hiện tại',
      auto_sync_desc: 'Định kỳ đồng bộ thông tin tài khoản đang hoạt động',
      antigravity_executable: 'Tệp chạy Antigravity',
      antigravity_executable_desc:
        'Đường dẫn tùy chọn dùng để tìm dữ liệu portable mode và khởi chạy Antigravity.',
      antigravity_executable_placeholder: 'Ví dụ: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_cli_executable: 'Tệp thực thi Antigravity CLI',
      antigravity_cli_executable_desc:
        'Đường dẫn đến CLI agy. Bản vá điều kiện chỉ được áp dụng cho tệp này.',
      antigravity_cli_executable_placeholder: 'Ví dụ: C:\\Program Files\\Antigravity\\agy.exe',
      detect_antigravity_cli: 'Phát hiện',
      agy_cli_detected: 'Đã phát hiện Antigravity CLI',
      agy_cli_detect_failed: 'Không tìm thấy Antigravity CLI',
      agy_patch_desc:
        'Sao lưu CLI, xác minh một mẫu ARM64 hoặc x86_64 duy nhất, áp dụng bản vá và ký lại tệp Mach-O trên macOS.',
      agy_patch_action: 'Áp dụng bản vá điều kiện',
      agy_patch_success: 'Đã vá Antigravity CLI',
      agy_patch_already_applied: 'Bản vá đã được áp dụng',
      agy_patch_failed: 'Không thể vá Antigravity CLI',
      agy_patch_result:
        'Định dạng: {{format}}; kiến trúc: {{architectures}}; bản sao lưu: {{backupPath}}',
      agy_patch_no_backup: 'không cần thiết',
      antigravity_ide_executable: 'Tệp chạy Antigravity IDE',
      antigravity_ide_executable_desc:
        'Đường dẫn tùy chọn đến Antigravity IDE. Khi chuyển tài khoản Classic, tiến trình tại đường dẫn này sẽ được bảo vệ khỏi bị tắt.',
      antigravity_ide_executable_placeholder:
        'Ví dụ: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Tham số khởi chạy Antigravity',
      antigravity_args_desc: 'Tham số tùy chọn khi khởi chạy Antigravity, ví dụ --user-data-dir.',
      antigravity_args_placeholder: 'Ví dụ: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Tham số khởi chạy Antigravity IDE',
      antigravity_ide_args_desc:
        'Tham số tùy chọn khi khởi chạy Antigravity IDE, ví dụ --user-data-dir.',
      antigravity_ide_args_placeholder: 'Ví dụ: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Phát hiện',
    },
    startup: {
      title: 'Khởi động',
      description: 'Điều khiển hành vi khởi động cùng hệ thống.',
      auto_startup: 'Khởi động cùng hệ thống',
      auto_startup_desc: 'Chạy khi đăng nhập và ẩn vào khay hệ thống',
      start_in_tray: 'Khởi động trong khay hệ thống',
      start_in_tray_desc: 'Khởi động ứng dụng thu nhỏ trong khay hệ thống',
      macos_hint:
        'macOS cần bản ký ứng dụng để Login Items hoạt động. Nếu tự động khởi động thất bại, hãy ký ứng dụng hoặc bật thủ công trong System Settings.',
    },
    privacy: {
      title: 'Quyền riêng tư',
      description: 'Quản lý cách dữ liệu được sử dụng để cải thiện ứng dụng.',
      error_reporting: 'Báo cáo lỗi',
      error_reporting_desc:
        'Gửi báo cáo lỗi ẩn danh để giúp cải thiện ứng dụng. Không thu thập dữ liệu cá nhân.',
      telemetry: 'Telemetry hiệu năng',
      telemetry_desc:
        'Chia sẻ metric thời gian và trace ẩn danh để chẩn đoán chuyển tài khoản chậm.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Chia sẻ chẩn đoán tương tác ẩn danh, heatmap và phát lại phiên để cải thiện ứng dụng.',
      clarity_unavailable: 'Microsoft Clarity chưa được cấu hình cho bản build này.',
      restart_note:
        'Một số cài đặt nhật ký và chẩn đoán có hiệu lực sau khi khởi động lại ứng dụng.',
    },
    notifications: {
      title: 'Thông báo',
      description: 'Cấu hình cảnh báo trên desktop cho các sự kiện tài khoản.',
      quotaAlert: 'Cảnh báo quota thấp',
      quotaAlertDesc: 'Nhận thông báo khi quota của model giảm xuống dưới ngưỡng đã đặt',
      quotaThreshold: 'Ngưỡng cảnh báo',
      quotaThresholdDesc: 'Phần trăm dùng để kích hoạt cảnh báo',
      saveFailed: 'Không thể lưu cài đặt thông báo',
      thresholdSaveFailed: 'Không thể lưu ngưỡng cảnh báo',
      aiCreditsAlert: 'Cảnh báo tín dụng AI thấp',
      aiCreditsAlertDesc: 'Nhận thông báo khi số dư tín dụng AI đạt hoặc thấp hơn mức đã đặt',
      aiCreditsThreshold: 'Ngưỡng cảnh báo tín dụng AI',
      aiCreditsThresholdDesc: 'Mức tín dụng tại hoặc dưới đó sẽ kích hoạt cảnh báo',
      aiCreditsThresholdSaveFailed: 'Không thể lưu ngưỡng tín dụng AI',
    },
    proxy: {
      title: 'Proxy trung gian',
      description: 'Cấu hình proxy cho các request đi ra Google/Gemini APIs.',
      enable: 'Bật proxy trung gian',
      url: 'Địa chỉ proxy',
      timeout: 'Thời gian chờ request (giây)',
    },
    modelMapping: {
      title: 'Ánh xạ mô hình',
      description:
        'Ánh xạ các model Claude Code sang model Antigravity để tối ưu chi phí và tốc độ.',
      claudeKeyword: 'Từ khóa model Claude',
      targetGemini: 'Model Gemini đích',
      addPlaceholderKey: 'ví dụ: op-3',
      addPlaceholderValue: 'ví dụ: gemini-3-flash',
      noMappings: 'Chưa có ánh xạ tùy chỉnh.',
      mapsTo: 'Ánh xạ tới',
      default: 'Mặc định',
      restoreDefaults: 'Khôi phục mặc định',
    },
    modelVisibility: {
      title: 'Hiển thị mô hình',
      description:
        'Điều khiển model nào được hiện trong thẻ tài khoản. Model bị ẩn sẽ không xuất hiện ở phần quota.',
      searchPlaceholder: 'Tìm mô hình...',
      showAll: 'Hiện tất cả',
      hideAll: 'Ẩn tất cả',
      reset: 'Đặt lại mặc định',
      save: 'Lưu thay đổi',
      noModels: 'Không tìm thấy mô hình',
      modelsShown: 'Đang hiện {{visible}} / {{total}} mô hình',
      quotaManagement: 'Quản lý quota',
      hidden: 'Đã ẩn',
      noModelsFound: 'Không tìm thấy mô hình',
      totalModels: 'Tổng',
      visibleModels: 'Đang hiện',
      hiddenModels: 'Đã ẩn',
      saving: 'Đang lưu...',
    },
    autoSwitchModels: {
      title: 'Auto-Switch Models Config',
      description:
        'Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.',
      searchPlaceholder: 'Search models...',
      noModels: 'No models found.',
      noModelsFound: 'No models found.',
      includeLabel: 'Include',
      priorityLabel: 'Priority',
      save: 'Save Config',
      saving: 'Saving...',
      saved: 'Auto-switch model configuration saved successfully.',
      saveFailed: 'Failed to save auto-switch model configuration.',
    },
    providerGroupings: {
      title: 'Nhóm theo nhà cung cấp',
      description: 'Nhóm model theo nhà cung cấp để dễ quản lý hơn',
      enabled: 'Bật nhóm theo nhà cung cấp',
      models: '{{count}} mô hình',
      avgLabel: 'tb',
      resetLabel: 'reset',
      overall: 'Tổng thể',
      healthy: 'Tốt',
      degraded: 'Giảm',
      limited: 'Giới hạn',
      critical: 'Nghiêm trọng',
    },
    examples: {
      title: 'Ví dụ sử dụng',
      description: 'Ví dụ lệnh để gọi local API proxy.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Sao chép',
      copied: 'Đã sao chép!',
      openai_protocol: 'Giao thức OpenAI',
      anthropic_protocol: 'Giao thức Anthropic',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Nhanh',
      pro: 'Pro',
      flash_preview: 'Xem trước',
      pro_high: 'Tốt nhất',
      sonnet: 'Thinking',
      opus: 'Opus',
    },
    gateway: {
      title: 'Dịch vụ API Proxy',
      description: 'Điều khiển local API proxy server.',
      status_running: 'Đang chạy',
      status_stopped: 'Đã dừng',
      action_start: 'Bắt đầu dịch vụ',
      action_stop: 'Dừng dịch vụ',
      accounts_info: '{{count}} tài khoản khả dụng',
      port: 'Cổng lắng nghe',
      port_hint: 'Mặc định 8045, cần khởi động lại để áp dụng',
      timeout: 'Thời gian chờ request',
      timeout_hint: 'Mặc định 120 giây, khoảng 30-600 giây',
      api_key: 'API Key',
      regenerate_key: 'Tạo lại',
      regenerateConfirm: {
        title: 'Tạo lại API Key?',
        description:
          'API key hiện tại sẽ hết hiệu lực ngay lập tức. Các ứng dụng đang dùng key cũ sẽ ngừng hoạt động.',
        cancel: 'Hủy',
        confirm: 'Tạo lại',
      },
      key_warning: 'Hãy giữ kín API key của bạn. Không chia sẻ với người khác.',
      auto_start: 'Tự động chạy cùng app',
      auto_start_desc: 'Khởi động proxy khi ứng dụng mở lên',
    },
    proxy_tab: 'Proxy',
    save: 'Lưu cài đặt',
  },
  toast: {
    backupSuccess: {
      title: 'Thành công',
      description: 'Đã tạo bản sao lưu tài khoản.',
    },
    backupError: {
      title: 'Lỗi',
      description: 'Không thể tạo bản sao lưu: {{error}}',
    },
    switchSuccess: {
      title: 'Thành công',
      description: 'Chuyển tài khoản thành công.',
    },
    switchError: {
      title: 'Lỗi',
      description: 'Không thể chuyển tài khoản: {{error}}',
    },
    deleteSuccess: {
      title: 'Thành công',
      description: 'Đã xóa bản sao lưu tài khoản.',
    },
    deleteError: {
      title: 'Lỗi',
      description: 'Không thể xóa bản sao lưu: {{error}}',
    },
  },
  cloud: {
    'total-accounts': 'Tổng số tài khoản',
    title: 'Tài khoản',
    description: 'Quản lý các tài khoản Google Gemini của bạn.',
    security: {
      compatibilityMode: {
        title: 'Khóa bảo mật được lưu trên máy tính này',
        description:
          'Kho lưu trữ bảo mật của hệ thống không khả dụng nên khóa được lưu trong tệp trên máy tính. Hãy bảo vệ máy tính và các bản sao lưu.',
      },
    },
    autoSwitch: 'Tự động chuyển',
    providerGroupings: 'Nhóm theo nhà cung cấp',
    addAccount: 'Thêm tài khoản',
    checkQuota: 'Kiểm tra quota ngay',
    polling: 'Đã kích hoạt polling',
    globalQuota: 'Quota tổng',
    layout: {
      auto: 'Tự động',
      twoCol: '2 cột',
      threeCol: '3 cột',
      list: 'Danh sách',
      compact: 'Thu gọn',
    },
    'auto-switch-client': 'Tự đổi tài khoản ứng dụng',
    'auto-switch-description':
      'Đổi tài khoản trong Antigravity, IDE và CLI. Chọn tài khoản cho yêu cầu API trên trang API Proxy.',
    'quota-display': {
      title: 'Hiển thị hạn mức',
      description:
        'Chọn hạn mức hiển thị trên thẻ tài khoản. Không thay đổi hạn mức hay tài khoản dùng cho yêu cầu.',
      'five-hours-gemini': 'Hạn mức Gemini trong 5 giờ',
      'five-hours-claude': 'Hạn mức Claude trong 5 giờ',
      'weekly-gemini': 'Hạn mức Gemini hằng tuần',
      'weekly-claude': 'Hạn mức Claude hằng tuần',
    },
    'quota-window': {
      label: 'Chu kỳ hạn mức',
      'five-hours': 'Hạn mức 5 giờ',
      'five-hours-short': '5 giờ',
      weekly: 'Hạn mức hàng tuần',
      'weekly-short': 'Tuần',
      'compact-weekly-short': 'Tuần',
      'both-short': 'Cả hai',
      'no-weekly-quota': 'Không có dữ liệu hạn mức hàng tuần',
      'weekly-summary-unavailable': 'Dịch vụ mô hình chưa cung cấp thông tin sử dụng hằng tuần.',
      'weekly-bucket-unavailable':
        'Không tìm thấy mức sử dụng hằng tuần trong thông tin nhận được.',
    },
    authDialog: {
      'manual-sign-in': 'Nhập mã thủ công',
      'waiting-for-browser':
        'Hoàn tất đăng nhập trong trình duyệt. Cửa sổ này sẽ tự động cập nhật.',
      title: 'Thêm tài khoản Google',
      description:
        'Chọn cách đăng nhập rồi đăng nhập Google trong trình duyệt. Tài khoản sẽ được thêm tự động.',
      oauthClient: 'Cách đăng nhập',
      oauthClientPlaceholder: 'Chọn cách đăng nhập',
      openLogin: 'Mở trang đăng nhập',
      authCode: 'Mã ủy quyền',
      placeholder: 'Dán mã bắt đầu bằng 4/...',
      instruction: 'Nếu đăng nhập không tự hoàn tất, hãy dán mã từ trình duyệt vào đây.',
      verify: 'Xác thực và thêm',
    },
    card: {
      active: 'Đang hoạt động',
      use: 'Sử dụng',
      rateLimited: 'Bị giới hạn tốc độ',
      validationRiskControlled: 'Rủi ro / Bị giới hạn',
      validationOAuthReauthRequired: 'Cần đăng nhập lại Google',
      validationRequired: 'Cần xác minh',
      completeValidation: 'Hoàn tất xác minh',
      left: 'còn lại',
      used: 'Đã dùng',
      unknown: 'Người dùng không rõ',
      actions: 'Hành động',
      useAccount: 'Dùng tài khoản này',
      identityProfile: 'Hồ sơ định danh',
      refresh: 'Làm mới quota',
      delete: 'Xóa tài khoản',
      noQuota: 'Chưa có dữ liệu quota',
      rateLimitedQuota: 'Bị giới hạn',
      liveLimitModelNotSupported: 'Mô hình không được hỗ trợ',
      liveLimitModelForbidden: 'Mô hình bị từ chối truy cập',
      liveLimitQuotaExhausted: 'Đã hết hạn mức',
      liveLimitRateLimited: 'Bị giới hạn tốc độ',
      liveLimitRemaining: 'còn {{duration}}',
      liveLimitDetectedAgo: 'phát hiện cách đây {{duration}}',
      liveLimitActiveTitle: 'Dịch vụ mô hình tạm thời không khả dụng.',
      liveLimitRecentTitle: 'Dịch vụ mô hình gần đây báo lỗi.',
      liveLimitQuotaSnapshot: 'Lần kiểm tra hạn mức gần nhất có thể vẫn hiển thị {{percentage}}%.',
      liveLimitMessage: 'Thông báo: {{message}}',
      resetPrefix: 'reset',
      resetTime: 'Thời điểm reset',
      resetUnknown: 'Không rõ',
      detailedQuota: 'Quota chi tiết',
      quotaGroupUnknown: 'Nhóm quota',
      gemini3Ready: 'Sẵn sàng cho Gemini 3',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'ví dụ: http://127.0.0.1:7890',
      proxySaved: 'Đã lưu proxy',
      'network-proxy': 'Proxy mạng',
      'network-proxy-description':
        'Tùy chọn: dùng proxy mạng cho tài khoản này. Nhấn Enter hoặc rời ô địa chỉ để lưu.',
      'proxy-replace-placeholder': 'Nhập địa chỉ proxy mới',
      'proxy-remove': 'Xóa proxy',
      'proxy-save-failed': 'Không thể lưu proxy',
      noProxy: 'Không dùng proxy',
      aiCredits: 'AI Credits',
      aiCreditsValue: '{{amount}} credits',
      creditsExpiry: 'hết hạn {{date}}',
      modelVisibility: 'Hiển thị model',
    },
    identity: {
      'profile-errors': {
        'account-not-found': 'Tài khoản này không còn khả dụng.',
        'baseline-unavailable': 'Không có hồ sơ định danh ban đầu để khôi phục.',
        'revision-not-found': 'Không tìm thấy hồ sơ định danh đã chọn.',
        'profile-invalid': 'Không thể dùng hồ sơ định danh này. Hãy chọn hồ sơ khác.',
        'profile-write-failed': 'Không thể lưu hồ sơ danh tính. Vui lòng thử lại.',
        'profile-operation-failed':
          'Không thể hoàn tất thao tác hồ sơ danh tính. Vui lòng thử lại.',
      },
      title: 'Thiết bị của tài khoản',
      loading: 'Đang tải...',
      generateAndBind: 'Tạo thông tin thiết bị mới',
      captureAndBind: 'Dùng thông tin thiết bị hiện tại',
      restoreOriginal: 'Khôi phục thông tin ban đầu',
      openFolder: 'Mở thư mục thông tin thiết bị',
      previewTitle: 'Thông tin thiết bị mới',
      confirm: 'Xác nhận',
      cancel: 'Hủy',
      close: 'Đóng',
      currentStorage: 'Cài đặt thiết bị hiện tại',
      accountBinding: 'Đã lưu cho tài khoản này',
      history: 'Phiên bản đã lưu',
      noHistory: 'Chưa có lịch sử hồ sơ',
      current: 'Đang dùng',
      restore: 'Khôi phục',
      generateSuccess: 'Đã tạo và gán hồ sơ',
      captureSuccess: 'Đã lấy và gán hồ sơ hiện tại',
      restoreOriginalSuccess: 'Đã khôi phục baseline',
      restoreVersionSuccess: 'Đã khôi phục bản lịch sử',
      deleteVersionSuccess: 'Đã xóa bản lịch sử',
      openFolderSuccess: 'Đã mở thư mục lưu hồ sơ',
      baseline: 'Thông tin thiết bị ban đầu',

      description: 'Lưu thông tin thiết bị cho tài khoản này để sử dụng khi chuyển tài khoản.',
      'load-failed': 'Không thể đọc thông tin thiết bị',
      'retry-description': 'Vui lòng thử lại. Thông tin thiết bị đã lưu chưa bị thay đổi.',
      'refresh-failed': 'Không thể làm mới. Thông tin đã đọc trước đó vẫn được hiển thị.',
      updating: 'Đang cập nhật thông tin thiết bị…',
      'device-id': 'Mã thiết bị',
      'mac-device-id': 'Mã thiết bị Mac',
      'installation-id': 'Mã cài đặt',
      'diagnostic-id': 'Mã chẩn đoán',
      'delete-version': 'Xóa phiên bản đã lưu: {{label}}',
    },
    list: {
      noAccounts: 'Chưa có tài khoản cloud nào được thêm.',
      noFilteredAccounts: 'Không có tài khoản nào khớp với tier đã chọn.',
    },
    error: {
      loadFailed: 'Không thể tải danh sách tài khoản cloud.',
      'report-issue': 'Báo cáo sự cố này',
      'report-preparing': 'Đang chuẩn bị thông tin lỗi…',
      'report-copied': 'Đã sao chép thông tin lỗi',
      'report-paste-guide':
        'Dán vào biểu mẫu GitHub, mô tả thao tác trước khi gặp lỗi rồi gửi báo cáo.',
      'report-copy-failed': 'Không thể sao chép thông tin lỗi',
      'report-retry': 'Hãy thử lại. Bạn cũng có thể mở phần chi tiết và sao chép lỗi thủ công.',
      'report-open-failed': 'Không thể mở GitHub',
      'report-manual-open': 'Thông tin đã được sao chép. Mở {{url}} và dán vào báo cáo.',
      dataRepair: {
        stepOpenIssue: 'Báo cáo sự cố trên GitHub. Nhấn để sao chép thông tin lỗi và mở biểu mẫu.',
      },
    },
    toast: {
      validationLinkFailed: {
        title: 'Không thể mở trang xác minh Google',
        codes: {
          'account-not-found': 'Tài khoản này không còn tồn tại.',
          'no-trusted-link': 'Tài khoản này hiện không có trang xác minh Google để mở.',
          'validation-link-failed': 'Không thể mở trang xác minh Google. Hãy thử lại.',
        },
      },
      addSuccess: 'Đã thêm tài khoản thành công!',
      addFailed: {
        title: 'Không thể thêm tài khoản',
        codes: {
          'authorization-denied': 'Chưa cấp quyền truy cập Google. Hãy thử lại.',
          'login-active': 'Đang có một lần đăng nhập Google khác.',
          'login-cancelled': 'Đã hủy đăng nhập.',
          'login-timeout': 'Đăng nhập quá thời gian. Hãy bắt đầu lại.',
          'duplicate-account': 'Tài khoản Google này đã được thêm.',
          'browser-open-failed': 'Không thể mở trình duyệt. Hãy kiểm tra trình duyệt mặc định.',
          'login-failed': 'Không thể thêm tài khoản. Hãy thử lại.',
        },
      },
      quotaRefreshed: 'Đã làm mới quota',
      refreshFailed: 'Không thể làm mới quota',
      pollFailed: 'Không thể polling quota của tất cả tài khoản',
      switched: {
        title: 'Đã chuyển tài khoản!',
        description: 'Đang khởi động lại Antigravity...',
      },
      switchFailed: 'Không thể chuyển tài khoản',
      switchFailureCodes: {
        'account-not-found': 'Tài khoản này không còn tồn tại.',
        'reauth-required': 'Đăng nhập lại tài khoản này trước khi chuyển.',
        'identity-profile-required': 'Thiết lập hồ sơ nhận dạng trước khi chuyển.',
        'process-control-failed': 'Không thể đóng hoặc khởi động lại Antigravity. Hãy thử lại.',
        'target-write-failed': 'Không thể dùng tài khoản đã chọn trong Antigravity. Hãy thử lại.',
        'switch-failed': 'Không thể chuyển tài khoản. Hãy thử lại.',
      },
      deleted: 'Đã xóa tài khoản',
      deleteFailed: 'Không thể xóa tài khoản',
      deleteConfirm: 'Bạn có chắc chắn muốn xóa tài khoản này không?',
      autoSwitchOn: 'Đã bật tự động chuyển',
      autoSwitchOff: 'Đã tắt tự động chuyển',
      updateSettingsFailed: 'Không thể cập nhật cài đặt',
      actionFailed: 'Không thể thực hiện thao tác',
      startAuthFailed: 'Không thể bắt đầu luồng đăng nhập',
      refreshCreditsAvailable: 'AI credits: {{amount}}',
      refreshCreditsUnavailable: 'Không có thông tin AI credits cho lần làm mới này.',
      batchRefreshSuccess: 'Đã làm mới thành công {{count}} tài khoản.',
      batchRefreshPartial: {
        title: 'Làm mới hoàn tất nhưng có lỗi',
        description: 'Đã làm mới {{successful}} tài khoản, {{failed}} tài khoản thất bại.',
      },
      batchDeleteSuccess: 'Đã xóa thành công {{count}} tài khoản.',
      batchDeletePartial: {
        title: 'Xóa hoàn tất nhưng có lỗi',
        description: 'Đã xóa {{successful}} tài khoản, {{failed}} tài khoản thất bại.',
      },
    },
    batch: {
      actions: 'Thao tác với tài khoản đã chọn',
      'delete-title': 'Xóa {{count}} tài khoản?',
      cancel: 'Hủy',
      selected: 'Đã chọn {{count}}',
      delete: 'Xóa mục đã chọn',
      refresh: 'Làm mới mục đã chọn',
      selectAll: 'Chọn tất cả',
      clear: 'Bỏ chọn',
      confirmDelete: 'Bạn có chắc chắn muốn xóa {{count}} tài khoản không?',
    },
    tierFilter: {
      all: 'Tất cả tier',
      reset: 'Đặt lại tất cả',
      selectedCount: '{{count}} tier',
      unknown: 'Không rõ',
    },
    sort: {
      recentlyUsed: 'Dùng gần đây',
      quotaOverall: 'Quota tổng',
      quotaClaude: 'Quota Claude',
      quotaPro3: 'Quota Pro3',
      quotaFlash: 'Quota Flash',
    },
    exportImport: {
      'file-errors': {
        'file-too-large': 'Tệp đã chọn quá lớn. Hãy chọn bản sao lưu tài khoản nhỏ hơn.',
        'invalid-export': 'Không nhận dạng được bản sao lưu tài khoản này. Hãy chọn tệp hợp lệ.',
        'read-failed': 'Không thể mở tệp đã chọn. Hãy kiểm tra xem tệp còn ở vị trí cũ không.',
        'write-failed': 'Không thể lưu bản sao tài khoản. Hãy kiểm tra vị trí lưu.',
        'import-failed': 'Không thể nhập tài khoản. Hãy thử lại.',
        'tokens-missing':
          'Bản sao lưu này thiếu thông tin đăng nhập của tài khoản. Hãy xuất bản sao có kèm thông tin đăng nhập.',
        'account-write-failed': 'Không thể lưu tài khoản.',
      },
      export: 'Xuất',
      import: 'Nhập',
      exportTitle: 'Xuất tài khoản',
      exportDesc:
        'Chọn có đưa thông tin đăng nhập vào bản sao lưu hay không. Hãy giữ riêng tư các bản sao có thông tin này.',
      includeTokens: 'Có thông tin đăng nhập (khôi phục tài khoản)',
      stripTokens: 'Không có thông tin đăng nhập (an toàn hơn khi chia sẻ)',
      exportSuccess: 'Đã xuất tài khoản thành công',
      importTitle: 'Nhập tài khoản',
      importDesc: 'Chọn tệp JSON đã được xuất trước đó.',
      importStrategy: 'Chiến lược nhập',
      strategyMerge: 'Gộp - Cập nhật tài khoản cũ, thêm tài khoản mới',
      strategyOverwrite: 'Ghi đè - Thay thế toàn bộ dữ liệu hiện có',
      strategySkip: 'Bỏ qua - Chỉ thêm tài khoản mới',
      importSuccess: 'Đã nhập {{imported}}, cập nhật {{updated}}, bỏ qua {{skipped}}',
      importErrors: 'Đã nhập xong với {{count}} lỗi',
      selectFile: 'Chọn tệp',
      importing: 'Đang nhập...',
      fileTooLarge: 'Kích thước tệp vượt quá giới hạn 5MB',
      invalidJson: 'Định dạng tệp JSON không hợp lệ',
      readFileFailed: 'Không thể đọc tệp',
    },
    localImport: {
      description: 'Tìm các tài khoản đã đăng nhập trên máy này. Kiểm tra kết quả trước khi nhập.',
      emailCollision: '{{email}} có {{count}} thông tin đăng nhập đã lưu khác nhau.',
      sources: {
        'antigravity-keyring': 'Thông tin đăng nhập do hệ thống lưu',
        'antigravity-classic-db': 'Tài khoản đã lưu trong Antigravity',
        'antigravity-ide-db': 'Tài khoản đã lưu trong Antigravity IDE',
      },
      validationErrors: {
        'credential-unavailable':
          'Thông tin đăng nhập này không còn khả dụng. Hãy đăng nhập lại Antigravity rồi quét lại.',
        'authentication-failed':
          'Google không chấp nhận thông tin đăng nhập này. Hãy đăng nhập lại Antigravity rồi quét lại.',
      },
      discoveryErrors: {
        missing: 'Không tìm thấy thông tin đăng nhập đã lưu tại đây.',
        'permission-denied':
          'Không có quyền đọc thông tin đăng nhập đã lưu. Hãy kiểm tra quyền truy cập rồi thử lại.',
        locked:
          'Thông tin đăng nhập bị khóa hoặc đang được dùng. Hãy mở khóa truy cập hoặc đóng Antigravity rồi quét lại.',
        malformed:
          'Không thể đọc thông tin đăng nhập đã lưu. Hãy đăng nhập lại Antigravity rồi quét lại.',
        'timed-out': 'Đọc thông tin đăng nhập mất quá nhiều thời gian. Vui lòng quét lại.',
        'read-failed': 'Không thể đọc thông tin đăng nhập đã lưu. Vui lòng quét lại.',
      },
      importErrors: {
        'credential-unavailable':
          'Thông tin đăng nhập này không còn khả dụng. Hãy quét lại trước khi nhập.',
        'identity-conflict':
          'Thông tin đăng nhập này không khớp với tài khoản hiện có. Hãy kiểm tra tài khoản trước khi nhập.',
      },
      errors: {
        'session-not-found': 'Kết quả quét này không còn khả dụng. Vui lòng quét lại.',
        'session-expired': 'Kết quả quét này đã hết hạn. Vui lòng quét lại.',
        'session-consumed':
          'Kết quả quét này đã được sử dụng. Hãy quét lại để nhập thêm tài khoản.',
      },

      title: 'Nhập tài khoản từ máy này',

      trigger: 'Nhập tài khoản từ máy này',
    },

    feedback: {
      'loading-title': 'Đang đọc tài khoản',
      'loading-description': 'Thông tin tài khoản sẽ xuất hiện ở đây khi sẵn sàng.',
      'empty-description': 'Chọn Thêm tài khoản để đăng nhập hoặc nhập tệp tài khoản có sẵn.',
      'filtered-description': 'Thử gói khác hoặc xóa bộ lọc để xem thêm tài khoản.',
    },
  },
  proxy: {
    'advanced-options': 'Cài đặt dịch vụ khác',
    'advanced-description': 'Chọn tài khoản, hướng dẫn chung và khả năng tương thích với công cụ.',
    tabs: { tools: 'Công cụ', models: 'Mô hình', records: 'Lịch sử', examples: 'Ví dụ' },
    'account-strategy': {
      'save-failed': 'Không thể lưu lựa chọn. Vui lòng chọn lại để thử lần nữa.',
      title: 'Tài khoản dùng cho yêu cầu API',
      balanced: 'Luân phiên các tài khoản khả dụng',
      'account-first': 'Ưu tiên cùng một tài khoản',
      'balanced-description':
        'Phân bổ cuộc trò chuyện mới cho các tài khoản khả dụng. Cuộc trò chuyện hiện có giữ nguyên tài khoản khi tài khoản đó còn khả dụng.',
      'account-first-description':
        'Với mỗi mô hình, tiếp tục dùng cùng một tài khoản. Đổi tài khoản khi hết hạn mức, bị giới hạn tạm thời hoặc không thể xử lý yêu cầu. Cuộc trò chuyện hiện có giữ tài khoản còn khả dụng.',
      'client-description':
        'Cài đặt này không đổi tài khoản đăng nhập trong Antigravity, IDE hay CLI. Quản lý tự đổi tài khoản ứng dụng trên trang Tài khoản.',
    },
    title: 'API Proxy',
    description: 'Quản lý local API proxy service.',
    save: 'Lưu cài đặt',
    copy: 'Sao chép',
    copied: 'Đã sao chép!',
    regenerate: 'Tạo lại',
    regenerateConfirm: {
      title: 'Tạo lại API Key?',
      description:
        'API key hiện tại sẽ hết hiệu lực ngay lập tức. Các ứng dụng đang dùng key cũ sẽ ngừng hoạt động.',
      cancel: 'Hủy',
      confirm: 'Tạo lại',
    },
    'risk-confirmation': {
      title: 'Xác nhận rủi ro trước khi khởi động proxy',
      description:
        'Kể từ tháng Hai, Google đã tăng cường các biện pháp kiểm soát. Việc chỉ chuyển đổi tài khoản bằng phần mềm này sẽ không ảnh hưởng đến tài khoản Google của bạn.\n\nTuy nhiên, sử dụng phần mềm làm proxy ngược hoặc cho các mục đích tương tự vi phạm Điều khoản dịch vụ của Google và có thể khiến tài khoản bị đình chỉ.',
      'account-advice': 'Chỉ sử dụng những tài khoản mà bạn có thể chấp nhận mất.',
      cancel: 'Hủy',
      confirm: 'Tôi hiểu rủi ro. Khởi động proxy',
    },
    service: {
      title: 'Trạng thái dịch vụ',
      description: 'Điều khiển local API proxy server.',
      running: 'Đang chạy',
      stopped: 'Đã dừng',
      start: 'Bắt đầu dịch vụ',
      stop: 'Dừng dịch vụ',
      start_failed: 'Không thể khởi động dịch vụ',
      port_in_use_title: 'Cổng đã được sử dụng',
      port_in_use_description:
        'Cổng {{port}} đang được một tiến trình khác sử dụng. Hãy đóng tiến trình đó, hoặc đổi cổng lắng nghe API proxy trong Cài đặt rồi thử lại.',
    },
    config: {
      port: 'Cổng lắng nghe',
      timeout: 'Thời gian chờ request',
      api_key: 'API Key',
      auto_start: 'Tự động chạy cùng app',
      auto_start_desc: 'Khởi động proxy khi ứng dụng mở lên',
      'allow-local-video-paths': 'Cho phép đường dẫn video cục bộ',
      'allow-local-video-paths-desc':
        'Cho phép công cụ kết nối đọc các video trên máy tính mà tài khoản của bạn có quyền truy cập. Chỉ bật khi tin tưởng mọi công cụ kết nối.',
      'global-system-prompt-title': 'Hướng dẫn chung cho mọi yêu cầu AI',
      'global-system-prompt-description':
        'Tự động thêm hướng dẫn này trước hướng dẫn của công cụ kết nối trong mỗi yêu cầu gửi qua Manager.',
      'global-system-prompt-placeholder':
        'Nhập lời nhắc hệ thống toàn cục...\nVí dụ: Trả lời bằng tiếng Trung giản thể và giải thích ngắn gọn thay đổi mã.',
      'global-system-prompt-character-count': '{{count}} ký tự',
      'global-system-prompt-long-warning':
        'Hướng dẫn dài hơn 2.000 ký tự sẽ để lại ít chỗ hơn cho lịch sử hội thoại. Hãy cân nhắc rút gọn.',
      local_access: 'Truy cập trong mạng nội bộ:',
      select_ip: 'Chọn IP',
      no_token_warning: 'API key chưa được đặt. Bất kỳ ai trong mạng đều có thể truy cập!',
      show_key: 'Hiện',
      hide_key: 'Ẩn',
      cloud_code_meta: 'Tương thích Cloud Code',
      cloud_code_meta_desc:
        'Thêm thông tin phản hồi cần thiết cho các công cụ Cloud Code cũ. Chỉ bật khi công cụ cần, vì công cụ khác có thể không chấp nhận thông tin này.',
    },
    mapping: {
      title: 'Ánh xạ mô hình',
      description: 'Chọn mô hình Gemini xử lý yêu cầu cho từng mô hình Claude.',
      maps_to: 'Ánh xạ tới',
      restore: 'Khôi phục mặc định',
      'only-raw-quota-models': 'Chỉ liệt kê mô hình tìm thấy trong tài khoản',
      'only-raw-quota-models-desc':
        'Công cụ kết nối chỉ thấy tên mô hình từ lần kiểm tra hạn mức tài khoản gần nhất, không liệt kê tên thay thế bổ sung.',
    },
    'open-code': {
      title: 'Đồng bộ OpenCode',
      description:
        'Kết nối OpenCode với Manager và giữ lại các cài đặt khác, chú thích và định dạng.',
      synced: 'Đã đồng bộ',
      'synced-custom-url': 'Đã đồng bộ bằng URL tùy chỉnh',
      'not-synced': 'Chưa đồng bộ',
      'config-path': 'Cấu hình',
      'configured-models': 'Các model đã cấu hình',
      runtime: 'Cài đặt OpenCode',
      installed: 'Đã cài đặt',
      'not-installed': 'Không phát hiện',
      credential: 'Khóa kết nối OpenCode',
      'key-stored': 'Đã lưu trong kho bảo mật của hệ thống',
      'key-missing': 'Sẽ được tạo trong lần đồng bộ tiếp theo',
      'backup-notice':
        'Bản sao lưu giữ chú thích và định dạng. Khóa Manager được thay bằng giá trị không sử dụng được; khi khôi phục sẽ dùng khóa hiện tại.',
      sync: 'Cấu hình và đồng bộ OpenCode',
      restore: 'Khôi phục bản sao lưu',
      clear: 'Xóa cấu hình được quản lý',
      revoke: 'Thu hồi khóa riêng',
      'model-dialog-title': 'Chọn model OpenCode',
      'model-dialog-description':
        'Các model đã chọn sẽ được thêm hoặc cập nhật. Các model hiện có không được chọn sẽ không bị xóa.',
      'custom-base-url': 'Địa chỉ Manager',
      'reset-base-url': 'Đặt lại',
      'invalid-base-url': 'Nhập URL HTTP hoặc HTTPS hợp lệ.',
      'sync-accounts': 'Sử dụng tài khoản trong tiện ích đăng nhập OpenCode',
      'sync-accounts-description':
        'Khi bật, OpenCode sẽ lưu thông tin giúp các tài khoản này tiếp tục đăng nhập vào một tệp trên máy tính này. Tùy chọn này mặc định tắt. Chỉ bật trên máy tính bạn tin tưởng.',
      'select-models': 'Các model cần thêm hoặc cập nhật',
      'selected-count': 'Đã chọn {{selected}} / {{total}}',
      'select-all': 'Chọn tất cả',
      'deselect-all': 'Bỏ chọn tất cả',
      'confirm-sync': 'Xác nhận đồng bộ',
      'auth-plugin-warning-title': 'Đã phát hiện tiện ích đăng nhập khác',
      'auth-plugin-warning-description':
        'opencode-antigravity-auth có thể dùng kết nối khác. Hãy kiểm tra Manager đã được chọn trong OpenCode trước khi dùng cài đặt này.',
      'view-config': 'Xem cấu hình',
      'restore-confirm-title': 'Khôi phục bản sao lưu OpenCode?',
      'restore-confirm-description':
        'Thay toàn bộ tệp bằng bản sao lưu ban đầu, bao gồm các thay đổi sau đó. Bản sao lưu được xóa sau khi khôi phục.',
      'confirm-restore': 'Xác nhận khôi phục',
      'clear-confirm-title': 'Xóa kết nối Manager?',
      'clear-confirm-description':
        'Xóa kết nối này và khóa riêng của nó. Giữ các dịch vụ, cài đặt khác và bản sao lưu.',
      'confirm-clear': 'Xác nhận xóa',
      'config-viewer-title': 'Cấu hình OpenCode',
      'config-viewer-description': 'Bản xem trước cấu hình chỉ đọc',
      'config-redacted-notice': 'Thông tin riêng tư được ẩn trong bản xem trước.',
      'config-copied': 'Đã sao chép cấu hình và ẩn thông tin riêng tư',
      'config-copy-failed': 'Không thể sao chép cấu hình',
      'config-load-failed': 'Không thể tải cấu hình',
      'copy-config': 'Sao chép cấu hình (ẩn thông tin riêng tư)',
      'success-title': 'Đã cập nhật cấu hình OpenCode',
      'error-title': 'Cập nhật OpenCode thất bại',
      'unknown-error': 'Lỗi cấu hình OpenCode không xác định',

      'choose-model-hint': 'Chọn ít nhất một mô hình để tiếp tục.',
      'config-retry-description': 'Vui lòng thử lại. Cấu hình đã lưu chưa bị thay đổi.',
    },
    examples: {
      title: 'Ví dụ sử dụng',
      description: 'Ví dụ lệnh để gọi local API proxy.',
    },
    persistence: {
      title: 'Request history and reasoning',
      description: 'Inspect bounded local records without slowing model traffic.',
      'audit-title': 'Lịch sử yêu cầu',
      'audit-description':
        'Lưu yêu cầu, phản hồi và các lần gửi tới dịch vụ mô hình trên máy tính này, đồng thời ẩn thông tin nhạy cảm.',
      rows: '{{count}} requests',
      queue: '{{count}} bản ghi đang chờ lưu',
      dropped:
        'Không thể lưu {{count}} bản ghi ({{reason}}). Các yêu cầu mô hình vẫn tiếp tục bình thường.',
      'disk-gib': 'Disk limit (GiB)',
      'body-hours': 'Thời gian giữ nội dung đầy đủ (giờ)',
      'summary-days': 'Summary retention (days)',
      'max-rows': 'Maximum rows',
      'no-audit': 'No traffic records yet.',
      'audit-metadata': 'Chi tiết yêu cầu và các lần gọi dịch vụ mô hình',
      'audit-body-missing': 'Nội dung đầy đủ của yêu cầu hoặc phản hồi không còn được lưu.',
      'audit-body-expired': 'Nội dung đầy đủ đã hết hạn lưu nhưng vẫn có thể xem chi tiết yêu cầu.',
      partial: 'Partial',
      'logical-size': 'Kích thước nội dung',
      'parse-error-offset': 'Vị trí nội dung không thể đọc',
      loading: 'Loading…',
      'copy-progress': 'Preparing full copy: {{value}}%',
      'previous-page': 'Previous page',
      'next-page': 'Next page',
      'copy-full': 'Copy complete body',
      'confirm-copy-full': 'Confirm copying {{size}}',
      'clear-audit': 'Xóa lịch sử yêu cầu',
      'repair-audit': 'Sửa lịch sử yêu cầu',
      'thought-title': 'Reasoning history',
      'thought-description': 'Save reasoning so later turns can continue the conversation.',
      sessions: '{{count}} sessions',
      'hard-limit': 'Mỗi cuộc hội thoại lưu tối đa 200 lượt và 64 MiB nội dung.',
      'retention-days': 'Retention (days)',
      'max-sessions': 'Maximum sessions',
      oversized: 'Nội dung vượt quá 64 MiB nên không được lưu đầy đủ.',
      'no-thought-body': 'No stored thought body.',
      signature: 'Signature',
      'copy-signature': 'Copy signature',
      'no-thought': 'No reasoning history yet.',
      'clear-thought': 'Clear reasoning history',
      'repair-thought': 'Repair reasoning history',
      'confirm-clear': 'Confirm clear',
      'confirm-repair': 'Confirm repair',
    },
  },
  traffic: {
    'detail-load-failed': 'Không tải được yêu cầu này. Vui lòng thử lại.',
    'detail-not-found': 'Bản ghi này không còn khả dụng. Có thể đã bị xóa.',
    fields: {
      category: 'Danh mục',
      method: 'Phương thức yêu cầu',
      'requested-model': 'Mô hình được yêu cầu',
      'mapped-model': 'Tuyến mô hình đã chọn',
      error: 'Chi tiết lỗi',
      affected: 'Số bản ghi bị ảnh hưởng',
      'request-id': 'Mã yêu cầu',
      'client-address': 'Địa chỉ ứng dụng',
      username: 'Người dùng',
      'reasoning-tokens': 'Token suy luận',
      'cached-tokens': 'Token bộ nhớ đệm',
      query: 'Tùy chọn yêu cầu bổ sung',
    },
    outcomes: {
      in_progress: 'Đang xử lý',
      completed: 'Đã hoàn tất',
      client_cancelled: 'Đã hủy',
      client_disconnected: 'Kết nối đã đóng',
      timeout: 'Hết thời gian chờ',
      upstream_error: 'Lỗi dịch vụ mô hình',
      auth_failed: 'Đăng nhập thất bại',
      internal_error: 'Lỗi ứng dụng',
      partial: 'Kết quả một phần',
    },
    'search-metadata': 'Tìm theo mô hình, mã yêu cầu hoặc địa chỉ',
    'copy-upstream-curl':
      'Sao chép yêu cầu tới dịch vụ mô hình dưới dạng cURL (ẩn thông tin riêng tư)',
    'upstream-attempts': 'Yêu cầu đã gửi tới dịch vụ mô hình',
    'no-attempts': 'Chưa gửi yêu cầu nào tới dịch vụ mô hình.',
    upstream: 'Dịch vụ mô hình',
    endpoint: 'Địa chỉ dịch vụ',
    protocol: 'Định dạng API',
    'repair-databases': 'Sửa dữ liệu đã lưu',
    'concise-help':
      'Hiển thị thông tin chính của yêu cầu. Các phần được mở rộng vẫn hiển thị toàn bộ nội dung.',
    'full-help':
      'Hiển thị toàn bộ thông tin đã tải. Nếu nội dung không thể sắp xếp hoặc chưa đầy đủ, hai chế độ có thể giống nhau.',
    'load-next-window': 'Phần tiếp theo',
    offset: 'Vị trí nội dung {{offset}}',
    'parse-error': 'Không thể đọc nội dung tại vị trí {{offset}}.',
    'thought-oversized':
      'Nội dung suy luận vượt quá 64 MiB nên không được lưu đầy đủ. Mã tham chiếu: {{hash}}',

    'loading-description': 'Bản ghi yêu cầu sẽ xuất hiện ở đây khi sẵn sàng.',
    'empty-description':
      'Các yêu cầu gửi qua proxy xuất hiện ở đây. Bạn cũng có thể điều chỉnh bộ lọc.',
    'empty-category-description':
      'Bản ghi của danh mục này xuất hiện ở đây. Thử danh mục khác hoặc điều chỉnh bộ lọc.',
    'load-failed': 'Không thể đọc bản ghi yêu cầu',
    'load-failed-description': 'Vui lòng thử lại. Điều này không có nghĩa là bản ghi đã bị xóa.',
    'refresh-failed': 'Không thể làm mới bản ghi. Dữ liệu đã tải trước đó vẫn được hiển thị.',
  },
};
export default vi;
