const zhCn = {
  'agent-tools': {
    title: '连接你的 AI 编程工具',
    description: '选择常用工具，通过 Antigravity Manager 使用你的可用模型。',
    loading: '正在读取设置…',
    installed: '已安装',
    'not-installed': '未检测到安装',
    'read-error': '无法读取原有设置，请重试后再修改。',
    retry: '重试',
    configured: '配置已保存',
    'custom-address': '正在使用其他地址',
    'not-configured': '尚未配置',
    'not-verified': '尚未验证请求',
    address: 'Manager 地址',
    model: '使用的模型',
    'not-set': '未设置',
    'choose-model': '配置时选择',
    update: '更新配置',
    configure: '一键配置',
    view: '查看配置',
    restore: '恢复备份',
    remove: '移除连接',
    'install-notice': '可以先保存配置。安装后请重开工具，让设置生效。',
    'action-error': '无法更新工具设置',
    saved: '设置已更新',
    reopen: '请重新打开 {{name}}，让设置生效。',
    'configure-title': '连接 {{name}}',
    'configure-description': '确认后，模型请求将通过 Manager。首次修改前会备份原来的设置。',
    'restore-title': '恢复 {{name}} 的配置备份？',
    'restore-description':
      '会用原始备份替换整个设置文件，之后手动修改的内容也会被替换。如果文件由 Manager 新建，则会删除该文件。恢复成功后将移除这份备份。',
    'remove-title': '移除与 Manager 的连接？',
    'remove-description': '恢复之前的连接设置，保留其他设置和已有备份。',
    'preview-title': '{{name}} 的配置',
    'preview-description': '仅显示连接 Manager 所需的设置，连接密钥已隐藏。',
    confirm: '确认',
    advanced: '连接地址与配置文件',
    'reset-address': '使用当前 Manager 地址',
    'backend-files': '这些设置保存在运行 Manager 服务的电脑上，归运行该服务的用户使用。',
    'backup-notice': '更新配置会保留首次修改前的备份。保存后请重开工具。',
    'toml-notice':
      'Codex 设置文件的排版和注释可能变化。修改前会完整备份，方便恢复；已有登录信息和权限设置会保留。',
    'codex-review': '同时配置任务请求与自动复核请求。已有启用的复核模型设置和审批设置会保留。',
    'model-count': '{{count}} 个模型',
    'plugin-notice':
      '检测到直接登录插件，它可能使用不同的连接。请在 OpenCode 中确认选中了 Manager。',
    'revoke-key': '停用 OpenCode 连接密钥',
    errors: {
      unavailable: '暂时无法访问工具设置，请重试。',
      'invalid-config': '设置文件无效或过大，请先修复文件再配置。',
      'read-failed': '无法读取设置文件，请检查访问权限后重试。',
      'write-failed': '无法保存设置，恢复备份仍保留。',
      'backup-failed': '无法创建备份，工具设置尚未修改。',
      'backup-missing': '没有可用于恢复的备份。',
      'configuration-changed': '操作期间设置发生变化，请重新读取后重试。',
      'key-missing': '请先在反代页面生成连接密钥。',
      'review-route-disabled': 'Codex 的自动复核模型已被停用，请先在模型映射中启用。',
    },

    'address-help': '通常使用当前 Manager 地址即可；服务运行在另一台电脑上时才需要修改。',
    'invalid-address':
      '请输入以 http:// 或 https:// 开头的 Manager 地址，不要包含登录信息或额外参数。',
    'model-required': '请先选择一个模型再保存。',
  },
  appName: 'Antigravity 管理器',
  'process-runtime': {
    'update-in-progress': 'Antigravity 正在更新。请先完成更新，再重试。',
    'close-failed': '未能关闭 Antigravity。请先保存聊天和文件，手动关闭应用后重试。',
    'exit-unconfirmed': 'Antigravity 尚未退出。请先保存聊天和文件，手动关闭应用后重试。',
    working: '正在处理…',
    busy: 'Antigravity 正在处理操作，请等待当前操作完成。',
    'missing-executable': '找不到或无法打开 Antigravity。请在设置中检查应用位置。',
    'target-conflict':
      '正在运行的 Antigravity 与设置中选择的不是同一份安装。请先关闭它，或选择对应的安装位置，再切换账号。',
    'directory-conflict':
      'Antigravity 正在使用的资料文件夹与设置中选择的不同。请先关闭它，或核对资料文件夹设置，再切换账号。',
    'probe-failed': '暂时无法确认 Antigravity 的运行状态。请检查应用是否已打开，再重试。',
    'launch-failed': '无法打开 Antigravity。请检查应用位置和访问权限。',
    'startup-unconfirmed':
      '暂时无法确认 Antigravity 是否已打开。为避免重复打开，未再次启动。请检查应用后再重试。',
    'switched-hot-unconfirmed':
      '新账号已保存，但尚未确认 Antigravity IDE 已切换。请先检查 IDE 中显示的账号，再决定是否重试。',
    'switched-startup-unconfirmed':
      '新账号已保存，但尚未确认 Antigravity 已打开，未再次启动。请检查应用后再重试。',
  },
  common: {
    close: '关闭',
    cancel: '取消',
    'core-unavailable-title': '无法连接到 Antigravity Manager',
    'core-unavailable-body':
      '账号和代理功能暂时无法使用。请关闭并重新打开 Antigravity Manager；如果仍无法使用，请安装最新版本。',
    'account-data-unavailable-title': '暂时无法打开已保存的账号',
    'account-data-unavailable-body':
      '暂时无法读取已保存的账号。请确认你使用的是平时登录这台电脑的账号，然后重新打开 Antigravity Manager。现有账号数据没有更改。',
    'already-running-title': 'Antigravity Manager 已在运行',
    'already-running-body': '请先关闭其他 Antigravity Manager 窗口再重试。如果找不到，请重启电脑。',
    loading: '加载中...',
    error: '错误',
    unknown: '未知',
    notAvailable: '不适用',
    openMenu: '打开菜单',

    'dismiss-notification': '关闭通知',
    'reading-settings': '正在读取你的设置…',
  },
  status: {
    services: '客户端',
    dashboard_title: '客户端运行状态',
    open_dashboard: '查看客户端运行状态',
    checking_short: '正在检查…',
    running_short: '运行中',
    stopped_short: '未运行',
    all_running: '客户端均在运行',
    all_stopped: '客户端均未运行',
    partial_running: '{{running}}/{{total}} 个客户端运行中',
    checking: '正在检查状态...',
    running: 'Antigravity 正在后台运行',
    stopped: 'Antigravity 服务已停止',
  },
  action: {
    stop: '停止',
    start: '启动',
    switch: '切换',
    deleteBackup: '删除备份',
    backupCurrent: '备份当前账号',
    retry: '重试',
    details: '详情',
    openLogs: '打开日志目录',
  },
  update: {
    'release-notes': {
      view: '查看更新内容',
      title: '更新说明',
      loading: '正在加载更新说明...',
      failed: '无法加载更新说明。你仍可下载或安装此更新。',
      empty: '此版本未提供更新说明。',
      history: '发布历史',
      'release-page': '发布详情页',
      'link-failed': '无法打开此链接，请重试。',
    },
    title: '更新',
    checking: '正在检查...',
    checkNow: '检查更新',
    checkFailed: '无法检查更新',
    upToDate: '当前已是最新版本。',
    unsupported: '当前平台不支持自动更新检查。',
    available: {
      title: '发现新版本',
      description: 'GitHub 上已有 {{version}} 版本。',
      download: '下载',
      'manual-download': '手动下载',
      'open-download-failed': '无法打开下载页面',
      downloading: '正在下载...',
      dismiss: '关闭',
      macosUnsignedNote:
        'macOS 新版本未进行官方签名。如果系统阻止打开应用，请参考 GitHub README 或相关 issue 中的手动签名方式。',
    },
    downloaded: {
      title: '更新已就绪',
      description: '{{version}} 版本已下载完成。',
      restart: '重启',
    },
  },
  error: {
    logs: {
      title: '脱敏日志预览',
      description:
        '可选：预览最近 10 分钟的日志，保存后手动附到 GitHub。不确定的内容将被移除，原始日志保持不变。',
      generate: '生成脱敏日志附件',
      save: '保存已预览的附件',
      summary: '{{kib}} KiB · {{removed}} 条记录内容已移除 · 总量上限 1 MiB',
      missing: '日志来源缺失或无法读取：{{sources}}。此附件不完整。',
      truncated: '日志因读取或附件大小限制被截断，此附件不完整。',
      generating: '正在生成脱敏日志…',
      saving: '请选择保存位置…',
      saved: '附件已保存，请手动添加到 GitHub Issue。',
      cancelled: '已取消保存，可以重新选择保存位置。',
      expired: '预览已过期，请重新生成附件后保存。',
      failed:
        '没有近期日志，或附件生成、保存失败。可以重试，也可以仅反馈错误详情。不会改用原始日志。',
    },
    toast: {
      'report-issue': '上报到 GitHub',
      'no-details': '当前错误未提供堆栈或更多详情。',
      copied: '错误信息已复制。请在 GitHub 页面粘贴，补充出错前的操作，再提交问题。',
      'copy-failed': '未能复制错误信息，请重试。也可以打开“详情”，手动复制。',
      'open-failed': '未能打开 GitHub，但错误信息已复制。请打开 {{url}}，粘贴后提交问题。',
    },
    generic: '发生未知错误。',
    detailsTitle: '错误详情',
    detailsDescription:
      '以下信息可用于排查问题，可能包含你电脑上的文件位置。分享前请先检查并隐藏私人信息。',
    keychainUnavailable: '暂时无法读取已保存的登录信息。',
    keychainHint: {
      translocation: '请将应用移到“应用程序”文件夹，然后重新打开。',
      keychainDenied: 'macOS 阻止读取已保存的登录信息。请查看应用的安装说明后重试。',
      signNotarize: '如有可用版本，请安装 macOS 已验证的版本。',
    },
    dataMigrationFailed: '无法读取旧版本保存的账号。',
    masterKeyUnavailable: '找到了已保存的账号，但暂时无法打开。现有账号数据没有更改。',
    dataMigrationHint: {
      relogin: '请重新登录或重新添加账号。',
      clearData: '如仍失败，请清理本地账号数据后再登录。',
    },
    antigravityStorageJsonNotFound:
      'Antigravity 尚未完成首次设置。请先打开所选的 Antigravity 应用并登录一次，再回来切换账号。',
    antigravityProjectIdMissing:
      '此账号尚未完成 Antigravity 的使用设置。请先在 Antigravity 中登录该账号一次，再回来重试。',
    antigravityDatabasePermissionDenied:
      '无法保存 Antigravity 的登录信息。请确认其资料文件夹允许修改；也可以先打开一次 Antigravity，再重启 Manager。',
    cloudAccountLoginExpired: '该邮箱的登录信息已过期，请重新登录。',
  },
  nav: {
    navigation: '主导航',
    'collapse-sidebar': '收起侧栏',
    'expand-sidebar': '展开侧栏',
    accounts: '账号',
    proxy: 'API 反代',
    settings: '设置',
    traffic: '流量',
  },
  traffic: {
    'detail-load-failed': '暂时无法读取这条请求，请重试。',
    'detail-not-found': '这条记录已无法查看，可能已被清理。',
    fields: {
      category: '记录分类',
      method: '请求方式',
      'requested-model': '工具请求的模型',
      'mapped-model': '选择的模型路线',
      error: '错误详情',
      affected: '影响的记录数',
      'request-id': '请求编号',
      'client-address': '客户端地址',
      username: '用户',
      'reasoning-tokens': '思考 Token',
      'cached-tokens': '缓存 Token',
      query: '附加请求选项',
    },
    outcomes: {
      in_progress: '处理中',
      completed: '已完成',
      client_cancelled: '已取消',
      client_disconnected: '连接已关闭',
      timeout: '请求超时',
      upstream_error: '模型服务出错',
      auth_failed: '登录失败',
      internal_error: '应用出错',
      partial: '部分结果',
    },
    title: '流量监控',
    description: '查看模型调用和应用活动，快速找到出错的请求。',
    records: '{{count}} 条记录',
    'on-disk': '磁盘占用 {{size}}',
    dropped: '已丢弃 {{count}} 条',
    model: '模型请求',
    auxiliary: '其他请求',
    ipc: '应用操作',
    system: '系统事件',
    'advanced-diagnostics': '高级诊断',
    'search-metadata': '搜索模型、请求编号或地址',
    'date-from': '开始',
    'date-to': '结束',
    account: '反代账号',
    'all-accounts': '全部账号',
    'model-family': '模型系列',
    'all-model-families': '全部模型系列',
    'physical-model': '实际使用的模型',
    'output-type': '输出类型',
    'all-output-types': '全部输出',
    'text-output': '文本',
    'image-output': '图片',
    'mixed-output': '文本 + 图片',
    'no-visible-output': '无可见输出',
    unknown: '未知',
    'tokens-in-out': '输入 / 输出 Token',
    'input-tokens': '输入 Token',
    'output-tokens': '输出 Token',
    'all-statuses': '全部状态',
    'exact-status': '指定状态码',
    unfinished: '未完成',
    'no-status': '无状态码',
    'include-current-credential': '复制 cURL 时包含当前代理密钥',
    'credential-warning':
      '复制后的命令会把当前代理密钥暴露给剪贴板及粘贴位置；更改筛选或离开本页后开关重置。',
    'current-credential': '当前密钥',
    'copy-request-curl': '复制请求为 cURL',
    'copy-upstream-curl': '复制模型服务请求为 cURL（隐藏隐私信息）',
    'curl-copied': '已将 cURL 命令复制到剪贴板。',
    'curl-copy-failed': '复制 cURL 命令失败。',
    'new-records': '{{count}} 条新记录',
    refresh: '刷新',
    'confirm-clear': '确认清空',
    'clear-category': '清空当前分类',
    total: '共 {{count}} 条 · 第 {{page}} 页',
    'loading-records': '正在加载记录…',
    'no-records': '当前分类暂无记录。',
    'detail-title': '流量详情',
    'loading-detail': '正在加载流量详情…',
    'system-operation': '系统操作',
    metadata: '请求信息',
    attempts: '重试记录（{{count}}）',
    payloads: '完整内容（{{count}}）',
    'client-request': '客户端请求',
    'request-headers': '请求头',
    'response-headers': '响应头',
    'upstream-attempts': '发送给模型服务的请求',
    'no-attempts': '没有发送给模型服务的请求。',
    attempt: '第 {{index}} 次尝试',
    running: '运行中',
    client: '客户端',
    upstream: '模型服务',
    request: '请求',
    response: '响应',
    'select-body': '请选择请求或响应正文。',
    concise: '精简',
    full: '完整',
    'view-mode-help': '查看视图模式说明',
    'concise-help': '显示主要请求信息，展开的内容仍会完整显示。',
    'full-help': '显示已加载的全部信息。如果内容无法分类或尚不完整，两种视图可能相同。',
    'search-body': '搜索当前正文',
    'copy-loaded': '复制已加载内容',
    'view-all-body': '查看全部',
    'load-more': '加载更多',
    'load-next-window': '下一段内容',
    'save-full': '保存完整正文',
    matches: '{{count}} 个匹配项',
    'first-100': '前 100 项',
    'parse-error': '无法读取内容的第 {{offset}} 个位置。',
    partial: '部分结果',
    'session-key': '会话标识',
    'select-session': '选择会话后查看保存的思考内容。',
    'no-sessions': '暂无思考记录。',
    'delete-session': '删除会话记录',
    turns: '{{count}} 轮',
    offset: '内容位置 {{offset}}',
    'unknown-model': '未知模型',
    'thought-oversized': '思考内容超过 64 MiB，未完整保存。识别编号：{{hash}}',
    time: '时间',
    operation: '操作',
    'operation-url': '操作 / URL',
    result: '结果',
    duration: '耗时',
    status: '状态码',
    endpoint: '服务地址',
    protocol: 'API 格式',
    'repair-databases': '修复已保存的记录',
    'open-monitor': '打开流量监控',

    'loading-description': '请求记录准备好后会显示在这里。',
    'empty-description': '通过反代发送的请求会显示在这里，也可以调整筛选条件。',
    'empty-category-description': '该分类的记录会显示在这里。试试其他分类，或调整筛选条件。',
    'load-failed': '暂时无法读取请求记录',
    'load-failed-description': '请重试。这不代表你的记录已被删除。',
    'refresh-failed': '暂时无法刷新记录，仍显示上次读取的内容。',
  },
  editionSelection: {
    title: '选择您的 Antigravity 版本',
    description: '选择您正在使用的 Antigravity 版本。这将帮助管理器连接到正确的应用程序。',
    edition1x: {
      name: 'Antigravity 1.x',
      description: '原始 Antigravity 应用程序。如果您使用的是旧版本，请选择此项。',
    },
    edition20: {
      name: 'Antigravity IDE',
      description: '新版 Antigravity IDE (2.0)。如果您使用的是最新的 IDE 版本，请选择此项。',
    },
    confirm: '继续',
  },
  account: {
    current: '当前',
    lastUsed: '上次使用 {{time}}',
    switchToAntigravity: '切换到 Antigravity',
    switchToIde: '切换到 Antigravity IDE',
  },
  home: {
    title: '账号列表',
    description: '管理您的 Antigravity Google Gemini 账号。',
    noBackups: {
      title: '未找到备份',
      description: '备份您当前的 Antigravity 账号以开始使用。',
      action: '备份当前账号',
    },
  },
  settings: {
    'service-unavailable':
      '暂时无法读取或保存设置。请重试；如果仍不行，请关闭并重新打开 Antigravity Manager。',
    'service-retry': '重试',
    'service-restart-required': '设置已保存，但尚未生效。请在应用中关闭代理，再重新开启。',
    'service-save': '保存',
    'service-secret-configured': '已设置代理地址，输入新地址即可替换。',
    'weekly-warmup': {
      error: '无法读取或保存预热设置。',
      retry: '重试',
      'cost-notice':
        '预热会消耗实际模型配额，并可能使用 AI credits。请求被接受不代表每周计时器已成功重启。',
      title: '每周配额预热',
      description: '所选每周配额重置后，为每个配额桶发送一次最小请求，并记录成功周期。',
      enabled: '启用每周配额预热',
      groups: '需要预热的配额组',
      group: { claude: 'Claude 配额组', gemini: 'Gemini 配额组' },
    },
    title: '设置',
    description: '管理应用偏好设置。',
    general: '常规',
    connection: '连接',
    models: '模型',
    appearance: {
      title: '外观',
      description: '自定义 Antigravity 管理器在您设备上的显示方式。',
    },
    darkMode: '深色模式',
    darkModeDescription: '启用深色模式以获得更好的夜间观看体验。',
    language: {
      title: '语言',
      description: '选择您的首选语言。',
      english: '英语',
      chinese: '中文 (简体)',
      russian: '俄语',
      vietnamese: '越南语',
      turkish: '土耳其语',
      french: '法语',
    },
    about: {
      title: '关于',
      description: '应用信息。',
    },
    cache: {
      title: 'Antigravity 缓存',
      description:
        '清理已知的 Antigravity 和 Antigravity IDE 缓存目录，用于解决登录或版本验证问题。',
      clear: '清理 Antigravity 缓存',
      dialogTitle: '清理 Antigravity 缓存？',
      dialogDescription: '将删除以下实际存在的缓存目录。',
      pathsLabel: '缓存目录',
      noPaths: '未发现已知的 Antigravity 缓存目录。',
      warning: '请先关闭 Antigravity，避免缓存文件被占用或在清理过程中重新生成。',
      cancel: '取消',
      confirm: '清理缓存',
      clearing: '正在清理...',
      clearedTitle: '缓存已清理',
      clearedDescription: '已从 Antigravity 缓存目录释放 {{size}} MB。',
      failedTitle: '清理缓存失败',
      notFoundTitle: '未发现 Antigravity 缓存',

      'paths-failed': '暂时无法找到缓存位置',
      'paths-retry-description': '请重试，确认缓存位置后再清理。',
      'partial-title': '部分缓存未能清理',
      'partial-description':
        '已释放 {{size}} MB，仍有 {{count}} 个位置未能清理。请关闭 Antigravity 后重试。',
    },
    version: '版本',
    platform: '平台',
    license: '许可证',
    openLogDir: '打开',
    toast: {
      saved: {
        title: '设置已保存',
        description: '配置已更新。',
      },
      saveFailed: {
        title: '保存设置失败',
      },
    },
    account: {
      'client-setup': '客户端位置与启动设置',
      'client-setup-description': '找不到客户端或需要自定义启动方式时，再展开调整。',
      'choose-file': '选择文件',
      'clear-field': '清空此项',
      title: '账号设置',
      description: '配置自动刷新和同步账号。',
      auto_refresh: '自动刷新配额',
      auto_refresh_desc: '定期自动刷新所有账号的配额信息',
      auto_sync: '自动获取当前账号',
      auto_sync_desc: '定期自动同步当前活跃账号信息',
      antigravity_executable: 'Antigravity 可执行文件',
      antigravity_executable_desc: '可选路径，用于发现便携模式数据目录并启动 Antigravity。',
      antigravity_executable_placeholder: '例如：C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_cli_executable: 'Antigravity CLI 可执行文件',
      antigravity_cli_executable_desc:
        'agy CLI 的独立路径。准入补丁只能作用于此文件，不会修改主程序或 IDE。',
      antigravity_cli_executable_placeholder: '例如：C:\\Program Files\\Antigravity\\agy.exe',
      detect_antigravity_cli: '自动探测',
      agy_cli_detected: '已探测到 Antigravity CLI',
      agy_cli_detect_failed: '未找到 Antigravity CLI',
      agy_patch_desc:
        '备份 CLI，确认 ARM64 或 x86_64 准入模式唯一匹配后写入补丁；macOS Mach-O 会自动重新签名。',
      agy_patch_action: '应用准入补丁',
      agy_patch_success: 'Antigravity CLI 补丁已应用',
      agy_patch_already_applied: '该补丁已经应用',
      agy_patch_failed: '无法修补 Antigravity CLI',
      agy_patch_result: '格式：{{format}}；架构：{{architectures}}；备份：{{backupPath}}',
      agy_patch_no_backup: '无需创建',
      antigravity_ide_executable: 'Antigravity IDE 可执行文件',
      antigravity_ide_executable_desc:
        '可选的 Antigravity IDE 可执行文件路径。切换经典版账号时，会保护此路径下的进程不被终止。',
      antigravity_ide_executable_placeholder:
        '例如：C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Antigravity 启动参数',
      antigravity_args_desc: '启动 Antigravity 时传入的可选参数，例如 --user-data-dir。',
      antigravity_args_placeholder: '例如：--user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Antigravity IDE 启动参数',
      antigravity_ide_args_desc: '启动 Antigravity IDE 时传入的可选参数，例如 --user-data-dir。',
      antigravity_ide_args_placeholder: '例如：--user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: '检测',
    },
    startup: {
      title: '启动',
      description: '控制系统启动时的应用行为。',
      auto_startup: '随系统启动',
      auto_startup_desc: '登录时自动启动并保持在托盘里',
      start_in_tray: '启动时最小化到系统托盘',
      start_in_tray_desc: '在系统托盘中最小化启动应用程序',
      macos_hint: 'macOS 需要应用已签名才可生效。如自启动失败，请自行签名或在系统设置中手动启用。',
    },
    privacy: {
      title: '隐私',
      description: '控制你的数据如何用于改进应用。',
      error_reporting: '错误上报',
      error_reporting_desc: '发送匿名错误报告以帮助我们改进应用。不收集个人数据。',
      telemetry: '性能遥测',
      telemetry_desc: '分享匿名耗时指标和链路数据，用于诊断账号切换变慢问题。',
      clarity: 'Microsoft Clarity',
      clarity_desc: '分享匿名交互诊断、热图和会话回放，帮助改进应用体验。',
      clarity_unavailable: '当前构建未配置 Microsoft Clarity。',
      restart_note: '部分日志和问题排查设置会在重启应用后生效。',
    },
    notifications: {
      title: '通知',
      description: '配置账号事件的桌面提醒。',
      quotaAlert: '低配额提醒',
      quotaAlertDesc: '当模型配额低于设定阈值时收到提醒',
      quotaThreshold: '提醒阈值',
      quotaThresholdDesc: '触发提醒的百分比阈值',
      saveFailed: '保存通知设置失败',
      thresholdSaveFailed: '保存阈值设置失败',
      aiCreditsAlert: 'AI 积分不足提醒',
      aiCreditsAlertDesc: '当 AI 积分余额降至或低于设定值时收到提醒',
      aiCreditsThreshold: 'AI 积分提醒阈值',
      aiCreditsThresholdDesc: '触发提醒的积分余额阈值',
      aiCreditsThresholdSaveFailed: '保存 AI 积分阈值设置失败',
    },
    proxy: {
      title: '上游代理',
      description: '为发往 Google/Gemini API 的请求配置代理。',
      enable: '启用上游代理',
      url: '代理地址',
      'configure-before-enabling':
        '请先保存有效的 HTTP(S) 代理地址，再启用代理。清空地址也会关闭代理。',
      'configuration-invalid': '上游代理已启用，但地址无效。请保存有效地址，或关闭代理。',
      'url-invalid': '请输入有效的 HTTP 或 HTTPS 代理地址。',
      timeout: '请求超时 (秒)',
    },
    modelMapping: {
      title: '模型映射',
      description: '将 Claude Code 模型映射到 Antigravity 模型，智能路由请求以优化成本和速度。',
      claudeKeyword: 'Claude 模型 (关键词)',
      targetGemini: '目标 Gemini 模型',
      addPlaceholderKey: '例如 op-3',
      addPlaceholderValue: '例如 gemini-3-flash',
      noMappings: '暂无自定义映射。',
      mapsTo: '映射到',
      default: '默认',
      restoreDefaults: '恢复默认配置',
    },
    modelVisibility: {
      title: '模型可见性',
      description: '控制哪些模型在账号卡片中可见。隐藏的模型不会在配额显示中出现。',
      searchPlaceholder: '搜索模型...',
      showAll: '显示全部',
      hideAll: '隐藏全部',
      reset: '重置为默认',
      save: '保存更改',
      noModels: '未找到模型',
      modelsShown: '{{visible}} / {{total}} 个模型可见',
      quotaManagement: '配额管理',
      hidden: '已隐藏',
      noModelsFound: '未找到模型',
      totalModels: '总数',
      visibleModels: '可见',
      hiddenModels: '隐藏',
      saving: '保存中...',
    },
    autoSwitchModels: {
      title: 'Auto-Switch Models Config',
      description:
        'Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.',
      searchPlaceholder: 'Search models...',
      noModels: 'No models found.',
      noModelsFound: 'No models found.',
      includeLabel: 'Include',
      priorityLabel: 'Priority',
      save: 'Save Config',
      saving: 'Saving...',
      saved: 'Auto-switch model configuration saved successfully.',
      saveFailed: 'Failed to save auto-switch model configuration.',
    },
    providerGroupings: {
      title: '模型分组',
      description: '按供应商分组模型以便更好地管理',
      enabled: '启用供应商分组',
      models: '{{count}} 个模型',
      avgLabel: '平均',
      resetLabel: '重置',
      overall: '总览',
      healthy: '正常',
      degraded: '降级',
      limited: '受限',
      critical: '严重',
    },
    examples: {
      title: '使用示例',
      description: '调用本地 API 代理的示例命令。',
      curl: 'cURL',
      python: 'Python',
      copy: '复制',
      copied: '已复制!',
      openai_protocol: 'OpenAI 协议',
      anthropic_protocol: 'Anthropic 协议',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: '极速',
      pro: '专业版',
      flash_preview: '预览版',
      pro_high: '最强',
      sonnet: '思维链',
      opus: 'Opus',
    },
    gateway: {
      title: 'API 反代服务',
      description: '控制本地 API 代理服务器。',
      status_running: '运行中',
      status_stopped: '已停止',
      action_start: '启动服务',
      action_stop: '停止服务',
      accounts_info: '{{count}} 个账号可用',
      port: '监听端口',
      port_hint: '默认 8045，修改端口需重启服务',
      timeout: '请求超时',
      timeout_hint: '默认 120 秒，范围 30-600 秒',
      api_key: 'API 密钥',
      regenerate_key: '重新生成',
      regenerateConfirm: {
        title: '重新生成 API 密钥？',
        description: '这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。',
        cancel: '取消',
        confirm: '重新生成',
      },
      key_warning: '请妥善保管您的 API 密钥，不要泄露给他人。',
      auto_start: '跟随应用自动启动',
      auto_start_desc: '应用启动时自动启动代理服务',
    },
    proxy_tab: '反代',
    save: '保存设置',
  },
  toast: {
    backupSuccess: {
      title: '成功',
      description: '账号备份创建成功。',
    },
    backupError: {
      title: '错误',
      description: '创建备份失败：{{error}}',
    },
    switchSuccess: {
      title: '成功',
      description: '切换账号成功。',
    },
    switchError: {
      title: '错误',
      description: '切换账号失败：{{error}}',
    },
    deleteSuccess: {
      title: '成功',
      description: '账号备份删除成功。',
    },
    deleteError: {
      title: '错误',
      description: '删除备份失败：{{error}}',
    },
  },
  cloud: {
    'total-accounts': '账号总数',
    title: '账号列表',
    description: '管理你的 Google Gemini 账号。',
    security: {
      compatibilityMode: {
        title: '安全密钥保存在这台电脑上',
        description:
          '系统的安全存储暂时不可用，安全密钥改为保存在本机文件中。请妥善保管这台电脑及其备份。',
      },
    },
    autoSwitch: '自动切换',
    providerGroupings: '提供商分组',
    addAccount: '添加账号',
    checkQuota: '立即检查配额',
    polling: '已触发轮询',
    globalQuota: '全局配额',
    layout: {
      auto: '自动',
      twoCol: '2 列',
      threeCol: '3 列',
      list: '列表',
      compact: '紧凑',
    },
    'auto-switch-client': '客户端自动换号',
    'auto-switch-description':
      '控制 Antigravity、IDE 和 CLI 的账号切换。API 请求使用哪些账号，请在 API 反代页面设置。',
    'quota-display': {
      title: '额度显示',
      description: '选择账号卡片显示哪些额度。仅影响显示，不改变实际额度或请求使用的账号。',
      'five-hours-gemini': 'Gemini 5 小时额度',
      'five-hours-claude': 'Claude 5 小时额度',
      'weekly-gemini': 'Gemini 每周额度',
      'weekly-claude': 'Claude 每周额度',
    },
    'quota-window': {
      label: '配额周期',
      'five-hours': '5 小时配额',
      'five-hours-short': '5 小时',
      weekly: '每周配额',
      'weekly-short': '每周',
      'compact-weekly-short': '周',
      'both-short': '全部',
      'no-weekly-quota': '暂无每周配额数据',
      'weekly-summary-unavailable': '模型服务暂未提供本周用量信息。',
      'weekly-bucket-unavailable': '返回的信息中未找到本周用量。',
    },
    recommendation: {
      badge: '推荐下一个',
      description: '根据最近一次获取的 {{context}} 配额自动推荐。',
      context: {
        overall: '综合',
        claude: 'Claude',
        pro3: 'Gemini Pro',
        flash: 'Gemini Flash',
      },
    },
    authDialog: {
      'manual-sign-in': '手动填写授权码',
      'waiting-for-browser': '请在浏览器中完成登录。完成后，此窗口会自动更新。',
      title: '添加 Google 账号',
      description: '选择登录方式，在浏览器中登录 Google 账号，完成后会自动添加。',
      oauthClient: '登录方式',
      oauthClientPlaceholder: '请选择登录方式',
      openLogin: '打开登录页面',
      authCode: '授权码',
      placeholder: '粘贴以 4/ 开头的代码...',
      instruction: '如果未能自动完成登录，可将浏览器中的授权码粘贴到这里。',
      verify: '验证并添加',
    },
    localImport: {
      trigger: '从本机导入账号',
      title: '从本机导入账号',
      description: '查找这台电脑上已登录的账号，核对结果后再导入。',
      scanning: '正在扫描并验证本地账号…',
      importing: '正在导入已确认的账号…',
      summary: '本地账号扫描摘要',
      accounts: '可导入账号',
      validationFailures: '验证失败',
      discoveryFailures: '来源失败',
      merged: '已合并',
      noAccounts: '没有发现可验证的本地账号。',
      issues: '以下项目不会导入',
      project: '项目',
      emailCollision: '{{email}} 找到了 {{count}} 份不同的登录信息。',
      rescan: '重新扫描',
      cancel: '取消',
      close: '关闭',
      confirm: '导入 {{count}} 个账号',
      resultTitle: '本地账号导入完成',
      resultDescription: '账号列表已按本次确认结果更新。',
      imported: '已导入 {{count}}',
      skipped: '已跳过 {{count}}',
      failed: '失败 {{count}}',
      sources: {
        'antigravity-keyring': '系统保存的登录信息',
        'antigravity-classic-db': 'Antigravity 已保存的账号',
        'antigravity-ide-db': 'Antigravity IDE 已保存的账号',
        'legacy-agent': '旧版 Agent 数据',
      },
      validationErrors: {
        'credential-unavailable': '这份登录信息已不可用。请在 Antigravity 中重新登录，再扫描一次。',
        'authentication-failed':
          'Google 未接受这份登录信息。请在 Antigravity 中重新登录，再扫描一次。',
        'network-failed': '网络错误导致账号验证失败。',
        'timed-out': '账号验证超时。',
        'unverified-email': 'Google 账号邮箱尚未验证。',
        'invalid-profile': 'Google 返回了无效的账号资料。',
      },
      discoveryErrors: {
        missing: '此处未找到已保存的登录信息。',
        'permission-denied': '没有权限读取已保存的登录信息。请检查访问权限后重试。',
        locked: '登录信息已锁定或正在使用。请解锁访问，或关闭 Antigravity 后重新扫描。',
        malformed: '无法识别已保存的登录信息。请在 Antigravity 中重新登录，再扫描一次。',
        'timed-out': '读取登录信息超时，请重新扫描。',
        'read-failed': '暂时无法读取登录信息，请重新扫描。',
      },
      importErrors: {
        'credential-unavailable': '这份登录信息已不可用，请重新扫描后导入。',
        'identity-required': '导入需要经过验证的账号身份。',
        'identity-conflict': '这份登录信息与已有账号不一致，请核对账号后再导入。',
        'persistence-failed': '账号保存失败。',
      },
      errors: {
        'preview-failed': '无法生成本地账号预览。',
        'session-not-found': '这次扫描结果已不可用，请重新扫描。',
        'session-expired': '这次扫描结果已过期，请重新扫描。',
        'session-consumed': '这次扫描结果已使用，如需继续导入，请重新扫描。',
        'confirmation-failed': '无法完成本地账号导入。',
        'internal-error': '本地账号导入请求失败。',
      },
    },
    card: {
      active: '活跃',
      use: '使用',
      rateLimited: '受限',
      validationRiskControlled: '风控 / 限流',
      validationOAuthReauthRequired: '需要重新登录 Google',
      validationRequired: '需要校验',
      completeValidation: '完成验证',
      left: '剩余',
      used: '已用',
      unknown: '未知用户',
      actions: '操作',
      useAccount: '使用账号',
      identityProfile: '身份配置',
      refresh: '刷新配额',
      delete: '删除账号',
      noQuota: '无配额数据',
      rateLimitedQuota: '已达限额',
      liveLimitModelNotSupported: '模型不受支持',
      liveLimitModelForbidden: '模型访问被拒绝',
      liveLimitQuotaExhausted: '配额已耗尽',
      liveLimitRateLimited: '请求受限',
      liveLimitRemaining: '剩余 {{duration}}',
      liveLimitDetectedAgo: '{{duration}} 前检测到',
      liveLimitActiveTitle: '模型服务暂时无法使用。',
      liveLimitRecentTitle: '模型服务最近出现过错误。',
      liveLimitQuotaSnapshot: '上次检查的剩余额度可能仍显示为 {{percentage}}%。',
      liveLimitMessage: '消息：{{message}}',
      resetPrefix: '重置',
      resetTime: '重置时间',
      resetUnknown: '未知',
      detailedQuota: '详细配额',
      quotaGroupUnknown: '配额组',
      gemini3Ready: 'Gemini 3 就绪',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: '代理',
      proxyPlaceholder: '例如 http://127.0.0.1:7890',
      proxySaved: '代理已保存',
      'network-proxy': '网络代理',
      'network-proxy-description':
        '可选：为此账号单独设置网络代理。填写地址后按 Enter 或离开输入框即可保存。',
      'proxy-replace-placeholder': '输入新的代理地址',
      'proxy-remove': '移除代理',
      'proxy-save-failed': '无法保存代理',
      noProxy: '无代理',
      aiCredits: 'AI 积分',
      aiCreditsValue: '{{amount}} 积分',
      creditsExpiry: '{{date}} 过期',
      modelVisibility: '模型可见性',
    },
    identity: {
      'profile-errors': {
        'account-not-found': '账号已不存在。',
        'baseline-unavailable': '没有可恢复的原始身份配置。',
        'revision-not-found': '找不到所选的身份配置记录。',
        'profile-invalid': '无法使用这份身份配置，请选择其他配置。',
        'profile-write-failed': '保存身份配置失败，请重试。',
        'profile-operation-failed': '身份配置操作失败，请重试。',
      },
      title: '账号设备信息',
      loading: '加载中...',
      generateAndBind: '生成新的设备信息',
      captureAndBind: '使用当前设备信息',
      restoreOriginal: '恢复原始设备信息',
      openFolder: '打开设备信息文件夹',
      previewTitle: '新的设备信息',
      confirm: '确认',
      cancel: '取消',
      close: '关闭',
      currentStorage: '当前设备设置',
      accountBinding: '为此账号保存的信息',
      history: '已保存的记录',
      noHistory: '暂无配置历史',
      current: '当前生效',
      restore: '恢复',
      generateSuccess: '生成并绑定成功',
      captureSuccess: '采集当前并绑定成功',
      restoreOriginalSuccess: '基线配置已恢复',
      restoreVersionSuccess: '历史配置已恢复',
      deleteVersionSuccess: '历史配置已删除',
      openFolderSuccess: '身份存储目录已打开',
      baseline: '原始设备信息',

      description: '为这个账号保存设备信息，在切换账号时使用。',
      'load-failed': '暂时无法读取设备信息',
      'retry-description': '请重试。已保存的设备信息没有被修改。',
      'refresh-failed': '暂时无法刷新，仍显示上次读取的设备信息。',
      updating: '正在更新设备信息…',
      'device-id': '设备编号',
      'mac-device-id': 'Mac 设备编号',
      'installation-id': '安装编号',
      'diagnostic-id': '诊断编号',
      'delete-version': '删除已保存的记录：{{label}}',
    },
    list: {
      noAccounts: '暂无云账号。',
      noFilteredAccounts: '没有账号匹配所选套餐。',
    },
    error: {
      loadFailed: '加载云账号失败。',
      'report-issue': '反馈这个问题',
      'report-preparing': '正在准备错误信息…',
      'report-copied': '错误信息已复制',
      'report-paste-guide': '请在 GitHub 反馈页面粘贴，补充出错前的操作，再提交问题。',
      'report-copy-failed': '未能复制错误信息',
      'report-retry': '请重试。你也可以打开“详情”，手动复制错误信息。',
      'report-open-failed': '未能打开 GitHub',
      'report-manual-open': '错误信息已复制。请打开 {{url}}，粘贴后提交问题。',
      dataRepair: {
        title: '无法打开已保存的账号',
        description:
          '应用无法读取部分已保存的账号。更换电脑登录账号或本地文件损坏后，可能会发生这种情况。',
        stepReLogin:
          '如果重新打开应用后仍无法使用，请重新登录或重新添加受影响的账号。在确认账号恢复前，请保留现有应用数据。',
        stepMacPrivacy:
          '在 macOS 上，请检查系统是否弹出权限提示，并将应用移到“应用程序”文件夹后重新打开。',
        stepCheckGithub: '查看 GitHub 仓库首页 README 中最新的排查步骤。',
        stepOpenIssue: '向我们反馈这个问题。点击后会复制错误信息，并打开 GitHub 问题反馈页面。',
        openRepository: '打开 GitHub 仓库',
      },
    },
    toast: {
      validationLinkFailed: {
        title: '无法打开 Google 验证页面',
        codes: {
          'account-not-found': '此账号已不存在。',
          'no-trusted-link': '此账号目前没有可打开的 Google 验证页面。',
          'validation-link-failed': '无法打开 Google 验证页面，请重试。',
        },
      },
      addSuccess: '账号添加成功！',
      addFailed: {
        title: '添加账号失败',
        codes: {
          'authorization-denied': 'Google 授权被拒绝，请重试。',
          'login-active': '已有 Google 登录正在进行。',
          'login-cancelled': '登录已取消。',
          'login-timeout': '登录已超时，请重新开始。',
          'duplicate-account': '此 Google 账号已添加。',
          'browser-open-failed': '无法打开浏览器，请检查默认浏览器后重试。',
          'login-failed': '无法添加账号，请重试。',
          'proxy-configuration-invalid':
            '请在设置中保存有效的上游代理地址，或关闭上游代理，然后重新登录。',
        },
      },
      quotaRefreshed: '配额已刷新',
      refreshFailed: '刷新配额失败',
      pollFailed: '轮询所有账号配额失败',
      switched: {
        title: '账号已切换！',
        description: '正在重启 Antigravity...',
      },
      switchFailed: '切换账号失败',
      switchFailureCodes: {
        'account-not-found': '此账号已不存在。',
        'reauth-required': '请重新登录此账号后再切换。',
        'identity-profile-required': '请先设置身份配置再切换。',
        'process-close-failed':
          '无法确认 Antigravity 已退出。请保存工作、处理确认窗口并关闭 Antigravity，再切换账号。',
        'process-control-failed': '无法关闭或重启 Antigravity，请重试。',
        'target-write-failed': '无法将所选账号应用到 Antigravity，请重试。',
        'switch-failed': '无法切换账号，请重试。',
      },
      deleted: '账号已删除',
      deleteFailed: '删除账号失败',
      deleteConfirm: '确定要删除此账号吗？',
      autoSwitchOn: '自动切换已启用',
      autoSwitchOff: '自动切换已禁用',
      updateSettingsFailed: '更新设置失败',
      actionFailed: '操作失败',
      startAuthFailed: '启动登录流程失败',
      refreshCreditsAvailable: 'AI 积分：{{amount}}',
      refreshCreditsUnavailable: '本次刷新没有可用的 AI 积分信息。',
      batchRefreshSuccess: '成功刷新 {{count}} 个账号。',
      batchRefreshPartial: {
        title: '刷新已完成，但存在问题',
        description: '已刷新 {{successful}} 个账号，{{failed}} 个失败。',
      },
      batchDeleteSuccess: '成功删除 {{count}} 个账号。',
      batchDeletePartial: {
        title: '删除已完成，但存在问题',
        description: '已删除 {{successful}} 个账号，{{failed}} 个失败。',
      },
    },
    batch: {
      actions: '已选账号操作',
      'delete-title': '删除 {{count}} 个账号？',
      cancel: '取消',
      selected: '已选 {{count}} 项',
      delete: '删除选中',
      refresh: '刷新选中',
      selectAll: '全选',
      clear: '取消选择',
      confirmDelete: '确定要删除选中的 {{count}} 个账号吗？',
    },
    tierFilter: {
      all: '全部套餐',
      reset: '重置为全部',
      selectedCount: '{{count}} 个套餐',
      unknown: '未知',
    },
    sort: {
      recentlyUsed: '最近使用',
      quotaOverall: '总体配额',
      quotaClaude: 'Claude 配额',
      quotaPro3: 'Pro3 配额',
      quotaFlash: 'Flash 配额',
    },
    exportImport: {
      'file-errors': {
        'file-too-large': '所选文件太大，请选择更小的账号备份文件。',
        'invalid-export': '无法识别此账号备份文件，请选择有效的备份文件。',
        'read-failed': '无法打开所选文件，请确认文件仍在原位置。',
        'write-failed': '无法保存账号备份，请检查保存位置后重试。',
        'import-failed': '无法导入账号，请重试。',
        'tokens-missing': '此账号的备份缺少登录信息，请重新导出包含登录信息的备份。',
        'account-write-failed': '无法保存此账号。',
      },
      export: '导出',
      import: '导入',
      exportTitle: '导出账号',
      exportDesc:
        '选择是否在备份中包含账号登录信息；包含登录信息的文件可用于恢复账号，请妥善保管。',
      includeTokens: '包含登录信息（可恢复账号）',
      stripTokens: '不包含登录信息（适合分享）',
      exportSuccess: '账号导出成功',
      importTitle: '导入账号',
      importDesc: '选择之前导出的 JSON 文件。',
      importStrategy: '导入策略',
      strategyMerge: '合并 - 更新已有，添加新账号',
      strategyOverwrite: '覆盖 - 替换所有已有数据',
      strategySkip: '跳过 - 仅添加新账号',
      importSuccess: '导入 {{imported}}，更新 {{updated}}，跳过 {{skipped}}',
      importErrors: '导入完成，但有 {{count}} 个错误',
      selectFile: '选择文件',
      importing: '导入中...',
      fileTooLarge: '文件大小超过 5MB 限制',
      invalidJson: 'JSON 文件格式无效',
      readFileFailed: '读取文件失败',
    },

    feedback: {
      'loading-title': '正在读取账号',
      'loading-description': '账号信息准备好后会显示在这里。',
      'empty-description': '点击“添加账号”登录，或导入已有的账号文件。',
      'filtered-description': '试试其他套餐，或清除筛选条件查看更多账号。',
    },
  },
  proxy: {
    'advanced-options': '更多服务设置',
    'advanced-description': '设置请求使用的账号、统一提示词和工具兼容选项。',
    tabs: { tools: '工具配置', models: '模型设置', records: '请求记录', examples: '调用示例' },
    'account-strategy': {
      'save-failed': '未能保存设置，请重新选择后再试一次。',
      title: 'API 请求使用账号的方式',
      balanced: '轮流使用可用账号',
      'account-first': '优先使用同一账号',
      'balanced-description': '将新对话分配给不同的可用账号。已有对话在账号可用时继续使用原账号。',
      'account-first-description':
        '每个模型优先继续使用同一账号。额度用完、暂时受限或无法处理请求时，换用其他账号。已有对话会保留仍可用的原账号。',
      'client-description':
        '此设置不会改变 Antigravity、IDE 或 CLI 当前登录的账号。客户端自动换号请在账号页面设置。',
    },
    title: 'API 反代',
    description: '管理本地 API 代理服务。',
    save: '保存设置',
    copy: '复制',
    copied: '已复制!',
    regenerate: '重新生成',
    regenerateConfirm: {
      title: '重新生成 API 密钥？',
      description: '这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。',
      cancel: '取消',
      confirm: '重新生成',
    },
    'risk-confirmation': {
      title: '开启反向代理前，请确认风险',
      description:
        '自二月份以来，谷歌已加大打击力度。在使用此软件期间，仅仅切换账户不会对您的谷歌账户造成任何影响。\n\n但是，如果您将其用于反向代理等用途，则违反了谷歌的服务条款，并可能导致账户被暂停。',
      'account-advice': '请使用您可以承受损失的账户。',
      cancel: '取消',
      confirm: '我已了解风险，开启反向代理',
    },
    service: {
      title: '服务状态',
      description: '控制本地 API 代理服务器。',
      running: '运行中',
      stopped: '已停止',
      start: '启动服务',
      stop: '停止服务',
      start_failed: '启动服务失败',
      port_in_use_title: '端口已被占用',
      port_in_use_description:
        '端口 {{port}} 已被其他进程占用。请关闭占用该端口的程序，或在设置中修改 API 反代监听端口后重试。',
    },
    config: {
      port: '监听端口',
      timeout: '请求超时',
      api_key: 'API 密钥',
      auto_start: '随应用启动',
      auto_start_desc: '应用启动时自动启动代理服务',
      cloud_code_meta: '兼容 Cloud Code',
      cloud_code_meta_desc:
        '为较旧的 Cloud Code 工具添加所需的额外回复信息。仅在工具需要时开启，其他工具可能不接受这些信息。',
      'allow-local-video-paths': '允许本地视频路径',
      'allow-local-video-paths-desc':
        '允许连接的工具读取这台电脑上你有权限访问的视频文件。请只在信任所有连接工具时开启。',
      'global-system-prompt-title': '所有 AI 请求的统一提示词',
      'global-system-prompt-description':
        '每次通过 Manager 请求模型时，都会先添加这段提示词，再添加所用工具的提示词。',
      'global-system-prompt-placeholder':
        '输入全局系统提示词...\n例如：请使用简体中文回复，并简洁说明代码变更。',
      'global-system-prompt-character-count': '{{count}} 个字符',
      'global-system-prompt-long-warning':
        '提示词超过 2,000 字符会占用更多对话空间，建议适当缩短。',
      local_access: '局域网访问:',
      select_ip: '选择 IP',
      no_token_warning: '⚠️ 未设置 API 密钥。服务对公网开放！',
      show_key: '显示密钥',
      hide_key: '隐藏密钥',
    },
    mapping: {
      title: '模型映射',
      description: '选择每种 Claude 模型请求实际使用的 Gemini 模型。',
      maps_to: '映射到',
      restore: '恢复默认',
      'only-raw-quota-models': '只列出账号中已有的模型',
      'only-raw-quota-models-desc':
        '连接的工具只会看到最近检查账号额度时返回的模型名称，不再列出额外的模型别名。',
    },
    'open-code': {
      title: 'OpenCode 同步',
      description: '将 OpenCode 连接到 Manager，保留其他设置、注释和原有排版。',
      synced: '已同步',
      'synced-custom-url': '已使用自定义 URL 同步',
      'not-synced': '未同步',
      'config-path': '配置文件',
      'configured-models': '已配置模型',
      runtime: 'OpenCode 安装情况',
      installed: '已安装',
      'not-installed': '未检测到',
      credential: 'OpenCode 连接密钥',
      'key-stored': '已由系统安全保存',
      'key-missing': '将在下次同步时创建',
      'backup-notice':
        '备份会保留注释和排版，其中的 Manager 连接密钥会替换为无法使用的内容；恢复时会使用当前密钥。',
      sync: '配置并同步 OpenCode',
      restore: '恢复备份',
      clear: '清除托管配置',
      revoke: '撤销专用 Key',
      'model-dialog-title': '选择 OpenCode 模型',
      'model-dialog-description': '所选模型会被添加或更新；未选择的已有模型不会被删除。',
      'custom-base-url': 'Manager 地址',
      'reset-base-url': '重置',
      'invalid-base-url': '请输入有效的 HTTP 或 HTTPS URL。',
      'sync-accounts': '在 OpenCode 登录插件中使用这些账号',
      'sync-accounts-description':
        '开启后，OpenCode 会将用于保持账号登录的信息保存到这台电脑的文件中。此选项默认关闭，请只在信任这台电脑时开启。',
      'select-models': '要添加或更新的模型',
      'selected-count': '已选择 {{selected}} / {{total}} 个模型',
      'select-all': '全选',
      'deselect-all': '取消全选',
      'confirm-sync': '确认同步',
      'auth-plugin-warning-title': '检测到其他登录插件',
      'auth-plugin-warning-description':
        'opencode-antigravity-auth 可能使用其他连接。使用这些设置前，请在 OpenCode 中确认选中了 Manager。',
      'view-config': '查看配置',
      'restore-confirm-title': '恢复 OpenCode 备份？',
      'restore-confirm-description':
        '将整个设置文件恢复为首次备份，之后的修改也会被覆盖。备份恢复成功后会移除。',
      'confirm-restore': '确认恢复',
      'clear-confirm-title': '移除 Manager 连接？',
      'clear-confirm-description': '移除此连接及其专用密钥，保留其他服务、设置和备份。',
      'confirm-clear': '确认清除',
      'config-viewer-title': 'OpenCode 配置',
      'config-viewer-description': '只读配置预览',
      'config-redacted-notice': '预览中的隐私信息已隐藏。',
      'config-copied': '已复制配置，隐私信息已隐藏',
      'config-copy-failed': '复制配置失败',
      'config-load-failed': '加载配置失败',
      'copy-config': '复制配置（隐藏隐私信息）',
      'success-title': 'OpenCode 配置已更新',
      'error-title': 'OpenCode 更新失败',
      'unknown-error': '未知的 OpenCode 配置错误',

      'choose-model-hint': '请至少选择一个模型后再继续。',
      'config-retry-description': '请重试。已保存的配置没有被修改。',
    },
    examples: {
      title: '使用示例',
      description: '调用本地 API 代理的示例命令。',
    },
    persistence: {
      title: '请求记录与会话思考',
      description: '在本机保存请求和会话记录，方便排查问题。',
      'audit-title': '请求记录',
      'audit-description': '在这台电脑上保存请求、回复及向模型服务发送请求的记录，并隐藏敏感信息。',
      rows: '{{count}} 条请求',
      queue: '{{count}} 条记录等待保存',
      dropped: '{{count}} 条记录未能保存（{{reason}}），不影响模型请求继续处理。',
      'disk-gib': '磁盘上限（GiB）',
      'body-hours': '完整内容保留时间（小时）',
      'summary-days': '摘要保留（天）',
      'max-rows': '最大记录数',
      'no-audit': '暂无流量记录。',
      'audit-metadata': '请求详情与模型服务调用记录',
      'audit-body-missing': '完整请求或回复内容已不再保存。',
      'audit-body-expired': '完整内容已过期，请求详情仍可查看。',
      partial: '部分保存',
      'logical-size': '内容大小',
      'parse-error-offset': '无法读取的内容位置',
      loading: '正在加载…',
      'copy-progress': '正在准备完整复制：{{value}}%',
      'previous-page': '上一页',
      'next-page': '下一页',
      'copy-full': '复制完整正文',
      'confirm-copy-full': '确认复制 {{size}}',
      'clear-audit': '清空请求记录',
      'repair-audit': '修复请求记录',
      'thought-title': '会话思考记录',
      'thought-description': '保存对话中的思考内容，供后续对话继续使用。',
      sessions: '{{count}} 个会话',
      'hard-limit': '每段对话最多保存 200 轮、64 MiB 的内容。',
      'retention-days': '保留天数',
      'max-sessions': '最大会话数',
      oversized: '内容超过 64 MiB，未完整保存。',
      'no-thought-body': '没有保存的思考内容。',
      signature: '签名',
      'copy-signature': '复制签名',
      'no-thought': '暂无思考记录。',
      'clear-thought': '清空思考记录',
      'repair-thought': '修复思考记录',
      'confirm-clear': '确认清空',
      'confirm-repair': '确认修复',
    },
  },
};
export default zhCn;
